### ISSUE TITLE
Add API docs sphinx builder

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#101]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-101

This will help validate the format of the API docs are correct.

Insofar as our internal API is not stable (and perhaps might never be, perhaps only external HTTP API will be), probably not necessary for first release.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-101. You are welcome to file additional issues in GitHub if that's easier for you.
