### ISSUE TITLE
Setting up project python Flask with requeriments.txt file

### ISSUE THREAD

**Issue by thanhan312** [ClusterHQ/flocker#1017]
Could someone point me how to setting up Flask project. I try with fig-compatible configuration but i don't know how to run file python (Just is environment for application).
Please suggest a specific solution. Thank a lot !

**Comment by binocarlos** [comment]
@thanhan312 I'm closing this issue but please re-open or contact us on #clusterhq on irc.freenode.net if you want any further assistance.
