### ISSUE TITLE
ZFS on CoreOS 440.0.0 (alpha)

### ISSUE THREAD

**Issue by MaheshRudrachar** [ClusterHQ/flocker#1023]
Not able to run zfs on CoreOS 440.0.0 (alpha). Also tried with vagrant, unfortunately throwing error:
Failed to load ZFS module stack.
Load the module manually by running 'insmod <location>/zfs.ko' as root.

Any changes need to be done?

**Comment by binocarlos** [comment]
@MaheshRudrachar I'm assuming this issue has been resolved so am closing it.  Please re-open if it still needs some attention.
