### ISSUE TITLE
Installing flocker-node on Fedora20 node

### ISSUE THREAD

**Issue by dooburt** [ClusterHQ/flocker#1027]
Hello there,

I can see this issue has been raised in some other issues, but I couldn't source a solution. I am working through the Fedora20 installation tutorial:  https://docs.clusterhq.com/en/latest/gettingstarted/installation.html#fedora-20-install

I've got everything as far as installing the RPMs:-

```
yum install -y https://s3.amazonaws.com/archive.zfsonlinux.org/fedora/zfs-release$(rpm -E %dist).noarch.rpm
yum install -y http://archive.clusterhq.com/fedora/clusterhq-release$(rpm -E %dist).noarch.rpm
yum install -y flocker-node
```

zfs installs correctly, but the following occurs on the clusterhq-release:-

```
[root@aws ~]# yum install -y http://archive.clusterhq.com/fedora/clusterhq-release$(rpm -E %dist).noarch.rpm
Cannot open: http://archive.clusterhq.com/fedora/clusterhq-release.fc21.noarch.rpm. Skipping.
Error: Nothing to do
```

I looked https://storage.googleapis.com/archive.clusterhq.com/ and found ```fc20```, but not fc21, so I'm unsure where I lost the path. Any advice?

Thanks

**Comment by lukemarsden** [comment]
Hi there, thanks for trying out Flocker!

Are you installing on Fedora 20 or Fedora 21? Only Fedora 20 is supported at this time, I believe.

Thanks,
Luke

**Comment by dooburt** [comment]
Hey Luke,  thanks for the reply. Flocker looks really interesting and it'd solve a lot of headaches we have with using our data with our Dockerised app.

It does indeed look like I have ended up with Fedora21. Curses.

Looking back through the documentation, I got to this point:-
```
Choose an AMI for your EC2 Instance
Visit https://fedoraproject.org/en/get-fedora#clouds
In the EC2 Fedora 20 section choose your local region and 64 Bit and click the “Launch it!” button.
```
But that link does not work and only provides download options for 21. AWS doesn't list an AMI for Fedora20 (or 21 for that matter), so I'm (as I'm not a sysadmin), unsure how to proceed! Help appreciated :)

**Comment by exarkun** [comment]
Looks like Fedora got rid of the AWS integration page we were referring to.  They may also have gotten rid of the Fedora 20 AMIs.  We'll have to revisit the documentation for how to run Flocker on AWS.

**Comment by lukemarsden** [comment]
@tomprince can you figure out what AMI we were previously getting, and see if it's still around? If so, we could update the docs to specify that precise AMI (listing AMIs for each region, unfortunately).

This would be great to get into the upcoming 0.4 release.

**Comment by dooburt** [comment]
I guess I'll be unable to get flocker-node running on AWS before 0.4?

**Comment by lukemarsden** [comment]
I've had a dig in the internet archive and you could try this link:
https://web.archive.org/web/20141209060135/http://fedoraproject.org/get-fedora#clouds

@dooburt Would you mind seeing if that works for you? Looks like you'll need to copy and paste the AMI that the archived javascript widget shows you into the AWS web console AMI search... not the greatest user experience, sorry about that!

**Comment by dooburt** [comment]
Thanks Luke, giving it a try. Will report back shortly.

**Comment by dooburt** [comment]
This was just the ticket and all is now going as planned. Thank you guys. Looking forward to see Flocker in action! :)
