### ISSUE TITLE
fix the python-versioneer metadata stuff in setup.py

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#103]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-103

setup.py says the project name is "Flocker" but python-versioneer is told that the resulting packages will have a name like "flocker-...".

These probably need to be in agreement or ... something in python-versioneer will break.  I'm not clear on what, exactly.  Probably that should be figured out before fixing this.  Possibly we also want a BuildBot configuration that tests whatever area of functionality this is (perhaps that just means building an sdist and then doing an install from that and running the tests?  dunno!  work it out.)

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-103. You are welcome to file additional issues in GitHub if that's easier for you.
