### ISSUE TITLE
flocker-cli inspect: Report the topology of the cluster

### ISSUE THREAD

**Issue by robhaswell** [ClusterHQ/flocker#107]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-107

It would be useful for users to be able to see the current state of the cluster, rather than just being able to change it.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-107. You are welcome to file additional issues in GitHub if that's easier for you.
