### ISSUE TITLE
Support encrypting the ZFS volumes on disk

### ISSUE THREAD

**Issue by cancan101** [ClusterHQ/flocker#1108]
eCryptfs can be used with ZFS: https://github.com/zfsonlinux/zfs/issues/494#issuecomment-3343441
Also see [this writeup on ZFS encryption](http://www.ubuntu-user.com/Magazine/Archive/2013/16/Encrypted-ZFS-with-Ubuntu).

**Comment by itamarst** [comment]
Hi,
Thank you for your feedback. We'll take that idea into account as we plan our product roadmap.
As an open source project you are also of course welcome to contribute to Flocker with a pull request to add these changes.

**Comment by binocarlos** [comment]
@cancan101 Hi - it doesn't look like we will implement this feature in the near future - our product roadmap is focused on a number of other things.

However it would be great for a PR to appear along these lines :-)

I'm going to close this issue but please feel free to re-open it.
