### ISSUE TITLE
How to implement flocker on existing docker environment 

### ISSUE THREAD

**Issue by moturi12** [ClusterHQ/flocker#1139]
Hi,

How to implement flocker on existing docker environment which has an data-only containers.

Thanks,
Naran

**Comment by exarkun** [comment]
Hi Naran,

Thanks for your interest in Flocker.  Currently, Flocker does not support managing Docker containers that were deployed without using Flocker.  Flocker can only manage Docker containers that it deploys itself.

Also, Flocker can only manage volumes that it creates.  It cannot manage the volumes that Docker creates automatically when Docker creates a data-only volume.

Work is on-going to improve Flocker's integration with Docker and other Docker-related tools so it's possible this situation will change at some point - but for the near term, you'll have to use Flocker to create anything you want to use Flocker to manage.
