### ISSUE TITLE
Fig latest release file format changes from fig.yml to docker-compose.yml

### ISSUE THREAD

**Issue by dockerstack** [ClusterHQ/flocker#1153]
I see that for the latest release they are making the fig to docker-compose and file format from fig.yml to docker-compose.yml so does flocker support this for the next releases.

reference url

https://github.com/docker/fig/releases/

Fig has been renamed to Docker Compose, or just Compose for short. This has several implications for you:

The command you type is now docker-compose, not fig.
You should rename your fig.yml to docker-compose.yml.
The PyPi package is now docker-compose.
This is a release candidate for Docker Compose 1.1.0. To try it out, install via curl:

curl -L https://github.com/docker/fig/releases/download/1.1.0-rc1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose; chmod +x /usr/local/bin/docker-compose
(If you install via PyPi, use pip install docker-compose==1.1.0-rc1.)

Besides the rename, there’s a lot of new stuff:

We’ve made a few small changes to ensure that Compose will work with Swarm, Docker’s new clustering tool (https://github.com/docker/swarm). Eventually you'll be able to point Compose at a Swarm cluster instead of a standalone Docker host and it’ll run your containers on the cluster with no extra work from you. As Swarm is still developing, integration is rough and lots of Compose features don't work yet.

docker-compose run now has a --service-ports flag for exposing ports on the given service. This is useful for e.g. running your webapp with an interactive debugger.

You can now link to containers outside your app with the external_links option in docker-compose.yml.

You can now prevent docker-compose up from automatically building images with the --no-build option. This will make fewer API calls and run faster.

If you don’t specify a tag when using the image key, Compose will default to the latest tag, rather than pulling all tags.

docker-compose kill now supports the -s flag, allowing you to specify the exact signal you want to send to a service’s containers.

docker-compose.yml now has an env_file key, analogous to docker run --env-file, letting you specify multiple environment variables in a separate file. This is great if you have a lot of them, or if you want to keep sensitive information out of version control.

docker-compose.yml now supports the dns_search, cap_add, cap_drop and restart options, analogous to docker run’s --dns-search, --cap-add, --cap-drop and --restart options.

A number of bugs have been fixed - see the milestone for details: https://github.com/docker/fig/issues?q=milestone%3A1.1.0+

**Comment by binocarlos** [comment]
Hi,

thanks for this - thankfully flocker is compatible with these changes because:

 * we don't actually run fig/compose - we just handle a subset of a particular version of its configuration format
 * you pass the name of the fig configuration file to `flocker-deploy` - this means that either `fig.yml` or `docker-compose.yml` will work with flocker

We are going to update our documentation to reflect this however to thanks for pointing it out :-)
