### ISSUE TITLE
Create a clusterhq/test-http-server docker container for use in functional tests

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#120]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-120

We're currently using `openshift/busybox-http-app` in our `geard` functional tests.
 * https://github.com/hybridlogic/flocker/blob/master/flocker/node/functional/test_gear.py#L63

But it's an externally controlled container and could change (or go away) at any time, breaking our functional tests.

The test http server also seems to return non-compliant headers which makes it difficult for us to parse its response using standards compliant tools like twisted.web.

```
(flocker-91)[vagrant@localhost vagrant]$ trial flocker.node.functional.test_gear.GearClientTests.test_add_with_port
flocker.node.functional.test_gear
  GearClientTests
    test_add_with_port ...                                               [FAIL]

===============================================================================
[FAIL]
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/flocker-91/lib/python2.7/site-packages/twisted/trial/_synctest.py", line 356, in assertEqual
    % (msg, pformat(first), pformat(second)))
twisted.trial.unittest.FailTest: not equal:
a = 'HTTP/1.1 200 OK\nContent-Type: text/plain;charset=utf-8\nContent-Length: 12\n\nHello world!\n'
b = 'Hello world'


flocker.node.functional.test_gear.GearClientTests.test_add_with_port
-------------------------------------------------------------------------------
Ran 1 tests in 22.254s
```

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-120. You are welcome to file additional issues in GitHub if that's easier for you.
