### ISSUE TITLE
Fake filesystem should log errors if `writer()` data processing fails

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#122]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-122

Currently errors are swallowed silently.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-122. You are welcome to file additional issues in GitHub if that's easier for you.
