### ISSUE TITLE
Stop using tight version dependencies.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#123]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-123

Since we aren't planning on building a base system, we should be more lenient in which package versions we specify.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-123. You are welcome to file additional issues in GitHub if that's easier for you.
