### ISSUE TITLE
Figure out a good way to specify custom pool when using `flocker-volume`, while having a good default

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#125]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-125

When running in normal mode we probably just want to use a pre-created "flocker" pool. In order to allow functional testing of push, it's useful to have `flocker-volume` use a non-default pool name. The current way the tests do this is not good.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-125. You are welcome to file additional issues in GitHub if that's easier for you.
