### ISSUE TITLE
Can't install flocker-node on RHEL/CentOS 7

### ISSUE THREAD

**Issue by gcharot** [ClusterHQ/flocker#1344]
Hello,

I'm trying to install flocker-node from https://docs.clusterhq.com/en/0.4.0/indepth/installation.html#installing-on-centos-7

I have an issue when adding clusterhq repository :
```
# yum install -y https://s3.amazonaws.com/clusterhq-archive/centos/clusterhq-release$(rpm -E %dist).noarch.rpm
Cannot open: https://s3.amazonaws.com/clusterhq-archive/centos/clusterhq-release.el7.noarch.rpm. Skipping.
Error: Nothing to do
```

Looks like the link is invalid, I've god a 404 response when curling the URL : 
```
curl -I https://s3.amazonaws.com/clusterhq-archive/centos/clusterhq-release$(rpm -E %dist).noarch.rpm
HTTP/1.1 403 Forbidden
x-amz-request-id: 39E91C9CFE0CCCC3
x-amz-id-2: tBQn/q0kKwoJh61cIHG4eZPIY5dfYR7CeSbhczQVAmu1UJBOQRaHP2XMgvPKnQfy
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Tue, 28 Apr 2015 16:04:09 GMT
Server: AmazonS3
```

Did I miss something ?
Cheers,
Greg

**Comment by binocarlos** [comment]
Hi - thanks for the report - I think it is to do with the output of the following command that is causing the problem:

```
$ rpm -E %dist
```

On my box (`CentOS Linux release 7.0.1406 (Core)`) the output is `.el7.centos` which leads to the following URL:

```
https://s3.amazonaws.com/clusterhq-archive/centos/clusterhq-release.el7.centos.noarch.rpm
```

which exists.

Can I confirm that the output of `rpm -E %dist` is only `.el7`?

In which case can you confirm if you are using RHEL or CentOS7?

Thanks!

**Comment by gcharot** [comment]
Hi,
Thanks for the quick answer ! I am indeed using RHEL 7.1
````
$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.1 (Maipo)
````
The output of the rpm command is : 
````
$ rpm -E %dist
.el7
````
I thought about that (diff between CentOS/RHEL) and try this on a CentOS 6.6 and the output is : 
````
$ cat /etc/redhat-release 
CentOS release 6.6 (Final)

$ rpm -E %dist
.el6
````

Cheers

**Comment by binocarlos** [comment]
Hey - thanks for the reply...

Currently our installation instructions are only for CentOS 7 - we have not tested it on 6.6...

Is it possible for you to install Flocker on CentOS7 or are you fixed to RHEL?

**Comment by gcharot** [comment]
Hi,
I have successfully installed flocker-node on RHEL 7.1 by using your RPM URL as well as changing the baseurl in /etc/yum.repos.d/clusterhq.repo

Your minimal example seems to work properly. Flocker-deploy is also working on RHEL 7.1

Cheers

**Comment by binocarlos** [comment]
@gcharot thanks for the feedback! I'm glad you got it working and that there seems to be a minimal difference between the CentOS and RHEL installation paths.

Although we don't officially support RHEL at the moment, it would be great if you could report back any other problems that you find with your RHEL 7.1 installation.

Thanks again :-)

**Comment by gcharot** [comment]
Sure I'll report any problem I face. For now I have tested the following scenario : 
3 instances on OpenStack IceHouse : 
* Flocker-deploy on RHEL 7.1
* node01 on RHEL 7.1
* node02 on CentOS 7.1.1503

The deployment as well as migrating containers (with volumes) from CentOS node to RHEL works fine for now (unstressed conditions). Client TCP connections are dropped though, conntrackd could be an interesting
feature.

Have you considered supporting flocker-node on CentOS/RHEL Atomic ? Goal is to provide a CentOS/RHEL equivalent to CoreOS (i.e minimal OS focused on running containers).
http://www.projectatomic.io/download/

Concerning RHEL 7, I can try to deploy template for you if you need testing.

Cheers,
Greg

**Comment by binocarlos** [comment]
@gcharot Great thanks for the feedback.  It's interesting for example that you've mixed the OS on the 2 nodes.  

Regarding the dropped client TCP connections - do you mean that long-lived connections are being dropped once you migrate or that initiating new connections after the migration are being dropped?

We don't currently have plans for Atomic - we have been playing with getting Flocker to work on CoreOS but only as an experiment.  It opens issues like how to compile ZFS and how to run the Flocker processes inside containers - I would imagine Atomic has similar issues.

As per your kind offer of running RHEL 7 tests, if/when we start focusing on RHEL then it would be great to get your feedback on deploying the getting started guide templates for example.

Many thanks!

**Comment by gcharot** [comment]
Atomic will indeed have the same challenges as CoreOS :)

Concerning the TCP connections, I mean long-lived connections are being dropped once I migrate, for example the MongoDB example : 
````
> db.records.find({})
{ "_id" : ObjectId("5541f7fb85f77adab2604094"), "flocker" : "foo" }

#### MIGRATE TO node02 ####

> db.records.find({})
2015-04-30T10:31:35.336-0400 DBClientCursor::init call() failed
Error: error doing query: failed
2015-04-30T10:31:35.338-0400 trying reconnect to node01:27017 (192.168.1.145) failed
2015-04-30T10:31:35.340-0400 reconnect node01:27017 (192.168.1.145) ok
> 
> db.records.find({})
{ "_id" : ObjectId("5541f7fb85f77adab2604094"), "flocker" : "foo" }
````
Which I guess is normal if there is no connection tracking exchange between the nodes.

Let me know if I can be of any help.
Cheers,
Greg

**Comment by binocarlos** [comment]
@gcharot indeed we don't currently have connection tracking so yes that is normal (as it currently stands)...

I was checking that you didn't mean that new connections were being dropped because Flocker should certainly be re-routing traffic to the new location (which it seems to be doing)

Thanks again for the feedback - appreciated :-)

**Comment by gcharot** [comment]
Yep make sence !

Concerning the documention on how to install flocker-deploy decribed in your doc [1], I would rather use yum to install it via your repository (yum install clusterhq-flocker-cli.noarch).

Using linux-install.sh is not really a clean way to proceed :)

I think you can close the issue, thanks for your help !

[1] https://docs.clusterhq.com/en/0.4.0/indepth/installation.html#linux

**Comment by binocarlos** [comment]
@gcharot many thanks for the valuable feedback :)

I'm going to close the issue but please feel free to re-open it!

**Comment by akamalov** [comment]
Documentation is wrong. Can we get proper repo URL ??

**Comment by wallnerryan** [comment]
Hi, what part of documentation is wrong?

**Comment by akamalov** [comment]
Hey Ryan, this is Alex from BNYM. So sorry. I, for some reason automatically assumed that RHEL7 is also supported (since there is a support for CentOS7). I see that a user "gcharot" has used RHEL7 succesfully, I am wondering if someone can share their modified clusterhq.repo file which makes it work with RHEL7.

**Comment by gcharot** [comment]
Hi,
As far as I remember I used the following URL : 
https://s3.amazonaws.com/clusterhq-archive/centos/clusterhq-release.el7.centos.noarch.rpm

Doing a yum install on this URL should work.

**Comment by akamalov** [comment]
Hey  Gregory and Thanks so much for the reply. I used this URL from the get go, but I am using RHEL7 to install. This RPM installs the following clusterhq.repo file:

```
[clusterhq]
name=ClusterHQ for CentOS $releasever
baseurl=https://s3.amazonaws.com/clusterhq-archive/centos/$releasever/$basearch/
enabled=1
gpgcheck=0

[clusterhq-testing]
name=ClusterHQ development for CentOS $releasever
baseurl=https://s3.amazonaws.com/clusterhq-archive/centos-testing/$releasever/$basearch/
enabled=0
gpgcheck=0
```
However, when tried to install flocker-node, it exits with an error:

```
[root@node1 yum.repos.d]# yum install -y clusterhq-flocker-node
Loaded plugins: langpacks, product-id, rhnplugin, search-disabled-repos, subscription-manager
This system is receiving updates from RHN Classic or Red Hat Satellite.
https://s3.amazonaws.com/clusterhq-archive/centos/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/solutions/69319

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.



 One of the configured repositories failed (ClusterHQ for CentOS 7Server),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable clusterhq

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=clusterhq.skip_if_unavailable=true

failure: repodata/repomd.xml from clusterhq: [Errno 256] No more mirrors to try.
https://s3.amazonaws.com/clusterhq-archive/centos/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
```
In one of your messages in this thread, you mentioned that you've modified your repo file to get it to work, do you mind sharing the entries you've changed?

Thanks!!

Alex

**Comment by gcharot** [comment]
Same problem as before $releaserver doesn't have the same output on RHEL and CentOS. You should change your .repo to use the following URL : 
https://s3.amazonaws.com/clusterhq-archive/centos/7/x86_64/repodata/repomd.xml

As you can see, just need to change 7server to 7, a simple sed should do the trick if you're lazy.
```# sed -i 's/7server/7/g' /etc/yum.repos.d/clusterhq.repo```

I destroyed my testing VMs so i"m not sure if this is going to work but i'm pretty confident though :)

Cheers,
Greg

**Comment by gcharot** [comment]
My bad the repo file doesn't containt 7server proper sed would be : 

```sed -i  's/$releasever/7/g' /etc/yum.repos.d/clusterhq.repo```

**Comment by akamalov** [comment]
Thanks so much Greg! Successfully installed :+1:

**Comment by wallnerryan** [comment]
Glad to see this, was just speaking with a customer who uses RHEL 7 who alternatively wgets the RPMS and then installs them directly. Thanks @gcharot and @akamalov

**Comment by gcharot** [comment]
You're welcome ! Glad I could help.

Cheers,
Greg

**Comment by wallnerryan** [comment]
FYI: https://docs.clusterhq.com/en/latest/flocker-standalone/install-node.html#rhel-7-install-standalone-flocker

**Comment by gcharot** [comment]
good to know, cheers !

**Comment by akamalov** [comment]
Awesome. Thanks Ryan!

**Comment by tiwarishrijan** [comment]
Getting 404 while accessing repo
https://clusterhq-archive.s3.amazonaws.com/centos/clusterhq-release.el7.centos.centos.noarch.rpm

![image](https://user-images.githubusercontent.com/6523607/32608698-36f1d890-c583-11e7-962c-a368b3420f33.png)
