### ISSUE TITLE
flocker.route functional tests depend too strongly on the specific network configuration used.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#135]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-135

* `flocker.route.functional.test_iptables_create.CreateTests.test_connection` depends on the server listening on the loopback device.
* `flocker.route.functional.test_iptables_create.CreateTests.test_remote_connections_unaffected` creates a network namespace by shelling out to `ip(8)` rather than using nomenclature.
* None of the test appear to test the case where the packets are being generated by the local network stack.

All the tests should be improved to use multiple network stacks, that are hooked up as they would be in production, rather than using multiple local addresses.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-135. You are welcome to file additional issues in GitHub if that's easier for you.
