### ISSUE TITLE
docs incorrectly say only fedora 20 supported

### ISSUE THREAD

**Issue by lukemarsden** [ClusterHQ/flocker#1350]
> These instructions describe the installation of clusterhq-flocker-node on a Fedora 20 operating system. This is the only supported node operating system right now.

https://docs.clusterhq.com/en/0.4.0/indepth/installation.html

This should be amended to include "or CentOS 7", I think.

**Comment by binocarlos** [comment]
Thanks for the feedback! I've created a [jira issue](https://clusterhq.atlassian.net/browse/FLOC-1778) for this.
