### ISSUE TITLE
Get buildbot to build pullrequests from outside contributors.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#136]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-136

It currently builds all pull requests by virtue of the fact that it builds all commits in the repository.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-136. You are welcome to file additional issues in GitHub if that's easier for you.
