### ISSUE TITLE
Can't use hostnames in deployment yaml file.

### ISSUE THREAD

**Issue by gcharot** [ClusterHQ/flocker#1366]
Hi,

I tried to switch IP to hostnames in your mongoDB example. The IP version works fine however when I use hostnames, flocker fails to deploy the stack. It seems to be related to the iptables redirection rule.
My hostname resolution is working fine (via hosts file). 

The deployment yaml looks like :
````
"version": 1
"nodes":
  "flocker01": []
  "flocker02": ["mongodb-example"] 
````
The interesting part of the stacktrace :

````
iptables v1.4.21: Bad IP address "flocker02"

Try `iptables -h' or 'iptables --help' for more information.
Unhandled Error

...
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['iptables', '--table', 'nat', '--append', 'PREROUTING', '--protocol', 'tcp', '--destination-port', '27017', '--match', 'addrtype', '--dst-type', 'LOCAL', '--match', 'comment', '--comment', 'flocker create_proxy_to', '--jump', 'DNAT', '--to-destination', 'flocker02']' returned non-zero exit status 2
Unhandled Error
...
````
As far as i known you can't specify hostname after the --to-destination option. Trying to manually run the iptables gives the same error :

````
# iptables --table nat --append PREROUTING --protocol tcp --destination-port 27017 --match addrtype --dst-type LOCAL --match comment  --comment "flocker create_proxy_to" --jump DNAT --to-destination flocker02
iptables v1.4.21: Bad IP address "flocker02"
````

Are hostname supported ? Using IPs is fine for testing but can become quite problematic in production. I agree that using hostnames with Iptables rules is not really advised for performances but you could do a gethostname before the rule insertion which is fine as long as the DNS reccord doesn't change over time... 

If you decide not to support hostname, it might be a good idea to check if the value is an IP (before SSHing to the nodes) and if not raise an "human readable" error to the user.

Cheers,
Greg

**Comment by itamarst** [comment]
1. For more production-oriented use we have a new HTTP API for interacting with the cluster; in next release it will use stable UUIDs for identifying nodes rather than IPs (http://doc-dev.clusterhq.com/advanced/api.html#api-details).

2. `flocker-deploy` will continue to use IPs until we have a replacement client, so we'll probably wait to see what that UI looks like before adding this.

**Comment by itamarst** [comment]
Or rather, `flocker-deploy` won't use UUIDs but might be extended to use hostnames (or the new command line client might).

**Comment by gcharot** [comment]
All right just wanted to pinpoint the fact that hostnames are not supported and exception is not really handled.

Cheers

**Comment by exarkun** [comment]
https://github.com/ClusterHQ/flocker/pull/1676 fixes some documentation relating to this.  It also adds some checks to the config parser to check for hostname vs IP address and report a clear error when the value isn't an IP address.  Thanks!

**Comment by gcharot** [comment]
Great ! Thanks for the fix !

**Comment by dwgebler** [comment]
Closing as the fix has now been merged.
