### ISSUE TITLE
Implement a DockerClient.get method which returns a record of the current state of a container

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#137]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-137

In #132 I need a way to test / check that the container that I've created has been configured with the requested internal and external ports.

We can call `docker inspect` to retrieve the rest of the information.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-137. You are welcome to file additional issues in GitHub if that's easier for you.
