### ISSUE TITLE
Configure buildbot to run flake8

### ISSUE THREAD

**Issue by dwgebler** [ClusterHQ/flocker#138]
pyflakes has been switched out for flake8 as per issue:

https://github.com/hybridlogic/flocker/issues/35

Buildbot needs to be able to run `flake8 flocker`

**Comment by jwitheford** [comment]
> Work is ongoing at https://github.com/hybridlogic/FlockerBuildbot/tree/flake8-138. This was rolled out yesterday but the work is no longer live because the more important change of the repository URL was made and rolled out.
> 
> One (the?) issue with that branch as it stands is that flake8 failures are shown as warnings and do not cause the build to fail.

Did you ever happen to find a way to force flake8 to fail the build? I have just run into the same issue on a project I am working on
