### ISSUE TITLE
Delete a volume

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#14]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-14

Delete a volume on the local node.

See also #55 and #75.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-14. You are welcome to file additional issues in GitHub if that's easier for you.
