### ISSUE TITLE
Automate testing an installed RPM.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#143]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-143

We build an RPM, but we don't have any tests for it.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-143. You are welcome to file additional issues in GitHub if that's easier for you.
