### ISSUE TITLE
Figure out how test (automatically) the vagrant images we build.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#144]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-144

Blocked by
- [ ] #144

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-144. You are welcome to file additional issues in GitHub if that's easier for you.
