### ISSUE TITLE
First time functional test run can be quite slow due to image downloads

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#152]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-152

The tests initially take disconcertingly long to run because you're waiting for Docker to download various images in the background.

Some potential solutions:
1. Pre-install them as part of functional test suite, so we can give some output telling humans what's going on.
2. Development Vagrant image could pre-install Docker images used in tests. This doesn't help people not using vagrant, which will be happening in longer term.

We could do both.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-152. You are welcome to file additional issues in GitHub if that's easier for you.
