### ISSUE TITLE
GearClient.add should raise an exception when the chosen external port is in use.

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#157]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-157

``GearClient.add`` should raise a custom exception if the chosen external port is already in use.

See:
 * https://github.com/ClusterHQ/flocker/pull/149#discussion_r14247046 and
 * https://github.com/ClusterHQ/flocker/commit/cce686392ceffd0292720d2307428db26909c283
 * https://github.com/ClusterHQ/flocker/issues/158

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-157. You are welcome to file additional issues in GitHub if that's easier for you.
