### ISSUE TITLE
Clean up the junk spewed at the beginning a test suite run

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#167]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-167

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-167. You are welcome to file additional issues in GitHub if that's easier for you.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-167. You are welcome to file additional issues in GitHub if that's easier for you.
