### ISSUE TITLE
When will CoreOS be supported ?

### ISSUE THREAD

**Issue by charlesa101** [ClusterHQ/flocker#1672]

**Comment by lukemarsden** [comment]
Hey, thanks for your interest in Flocker. CoreOS presents a few challenges, insofar as handling mount namespaces for containers *from* a container is tricky. This is not currently high priority for us, but feedback such as yours is how we make product decisions to prioritize features, so consider the request taken as input.

Out of interest, what is your use-case for Flocker on CoreOS? Which applications or databases would you be interested in running on it?

**Comment by charlesa101** [comment]
Thanks @lukemarsden, basically looking at zfs backup of docker container data,

i.e Database, HDFS, Kafka without relying on replication

**Comment by lukemarsden** [comment]
@charlesa101 Cool - thanks for the feedback. Is there a reason you want to use ZFS specifically?

**Comment by charlesa101** [comment]
based on the MongoDB example tutorial, where container + data was migrated, i thought this could be applicable to all other containers withe CoreOS as well.

I want to have a more effective backup strategy for disaster recovery and not have to rely on data replication alone

**Comment by lukemarsden** [comment]
Yes, Flocker definitely works with any app that writes to a filesystem. Thanks for the feedback - we will work this into our roadmap. If you sign up for updates in the footer of our website at https://clusterhq.com/ you'll get an email when new features such as CoreOS support and backup/restore functionality are announced. Meanwhile, you can try out Flocker for stateful container migration on Ubuntu or CentOS. Thanks!

**Comment by tobiasmcnulty** [comment]
+1 for prioritizing CoreOS support

**Comment by lukemarsden** [comment]
Hey folks, we are happy to announce this working  here: https://clusterhq.com/2015/09/01/flocker-runs-on-coreos/

Check it out and please send feedback!

cc @tobiasmcnulty @charlesa101

**Comment by rimusz** [comment]
+1 for CoreOS cloud agnostic support

**Comment by lukemarsden** [comment]
@rimusz hey!

In principle Flocker supports any of these: https://docs.clusterhq.com/en/1.8.0/introduction/flocker-supports.html and you could use the experimental Flocker containers that we run on CoreOS on any of those infrastructures.

Which other infrastructures are you interested in supporting? We are currently working on adding GCE and Ceph as options.

@wallnerryan and @davidoliverSP2 are working on documenting the experimental containerized Flocker.

**Comment by rimusz** [comment]
@lukemarsden GCE support sounds good to me :+1: 
What about bare-metal based CoreOS installs?

**Comment by lukemarsden** [comment]
@rimusz cool, will bump GCE priority up a notch!

Regarding bare metal:
The problem with the ZFS driver is that it doesn't give you failover, so if you lose a node you wouldn't be able to recover the data that was on it. Would that be a problem for your use case?

Failover/HA use cases on bare metal could be enabled by the Ceph integration we're [working on](https://github.com/ClusterHQ/ceph-flocker-driver) (unfinished project! testing needed! cc @robhaswell). Or there are other commercial "software defined storage" solutions that could work, like ScaleIO, Hedvig or ConvergeIO, just to name a few. I'm not sure if any of these support CoreOS but they do have Flocker drivers. Let me know if you're interested and I can find out from them! (They all wrote Flocker drivers).

**Comment by rimusz** [comment]
@lukemarsden ok, cool regarding GCE :+1: 

If bare-metal node gets lost and data was already replicated to others nodes, I do not see it as big problem.

Failover/HA if that is based on the Ceph it is fine as I would prefer to have the open source version.
Commercial versions are more for enterprise companies :)
Have you looked into http://minio.io/ or http://basho.com/products/riak-s2/ for object storage?

**Comment by lukemarsden** [comment]
Great, thanks for the feedback @rimusz!

You can sign up for our newsletter here to get updates when we release Ceph support in officially supported version of Flocker https://clusterhq.com/newsletter/

Or if you want to test a more experimental version of the Ceph backend then @robhaswell can help out :)

**Comment by mateeyow** [comment]
Is there an implementation on coreos for digitalocean?

**Comment by wallnerryan** [comment]
@mateeyow we havent run it on digital ocean but we do [work with installing on coreos](https://docs.clusterhq.com/en/latest/flocker-standalone/installer.html#experimental-configurations) via and you can also use try and use our [containers to install](https://docs.clusterhq.com/en/latest/supported/flockercontainers.html#flocker-containers)

**Comment by maxa4e** [comment]
@wallnerryan 
The only solution at the moment for CoreOS is to use AWS as the persistant data storage?
How about latency with this cloud based storage. IF one would save database for example

**Comment by wallnerryan** [comment]
@maxa4e you can run coreos and use it with any of our backends. Backends supported include a number of different solutions from SDS, Enterprise Arrays and cloud storage. more details here https://docs.clusterhq.com/en/latest/supported/index.html#supported-infrastructure-storage

Yes, using cloud storage does mean some latency but this is usually defined by the cloud storage provider with different levels of performance and network throughput. In the case for AWS, there are provisioned IOPs, general SSD, provisioned IOPs SSD and magnetic. See more http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html. You can access these through flocker profiles.

If the above specs /performance don't work for you, look to use an on-prem, sds solution.

R

**Comment by wallnerryan** [comment]
@rimusz
