### ISSUE TITLE
Clean up the junk spewed by the flocker.volume.functional.test_script suite

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#171]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-171

Many of these dump stuff onto stderr.  For example:

```
  ReceiveTests
    test_creates_files ... cannot open 'testpool_c7fb14d9-49d5-4a3e-ad35-4043e6f281a9/e68b4669-9884-476f-a4ec-c551c0788c94.thevolume': dataset does not exist
[OK]
```

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-171. You are welcome to file additional issues in GitHub if that's easier for you.
