### ISSUE TITLE
Proposal: Allow using CFSSL to generate all certificates

### ISSUE THREAD

**Issue by ekristen** [ClusterHQ/flocker#1741]
CloudFlare has released a very powerful TLS certificate management utility that can be run as a tool or as an API service, it would be really powerful if `flocker-ca` could leverage a CFSSL instance to generate all certificates.

**Comment by binocarlos** [comment]
@ekristen thanks for the info!  I will inform our product team about this to see if `flocker-ca` could make use of it

**Comment by wallnerryan** [comment]
Thanks, we've brought this back to our engineering team as a suggestion, closing this now.
