### ISSUE TITLE
Flocker deploy with error about Twisted/ SSL

### ISSUE THREAD

**Issue by sukenneth** [ClusterHQ/flocker#1783]
Hello,

I tried to install Flocker on Ubuntu 14.04, but I have problem when run the below flocker-deploy
I google but no lucky to find out what maybe the issue. My flocker is 1.0.0

I have two Flocker-node ( one flocker control service and flocker agent, the second one is flocker agent)

# flocker-deploy 192.168.xxx.xxx  minimal-deployment.yml minimal-application.yml
Traceback (most recent call last):
Failure: twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]
main function encountered error
Traceback (most recent call last):
Failure: twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]

Appreciate if someone could guide me where to first check!

Kenneth

**Comment by binocarlos** [comment]
@sukenneth Hi - thanks for the info...

So, the first thing would be to look in the Flocker logs for the control service - which is where `flocker-deploy` is POSTing the configuration to.  The logs can be searched for errors using the following command on the control service node:

```
$ sudo cat /var/log/upstart/flocker-control.log | grep 'error": true'
```

If you could paste the output of the above command that would be great.

Your error seems to be related to OpenSSL because of this line:

```
Failure: twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]
```

Question - what IP/hostname did you use when generating the control-service TLS certificates?

The IP/hostname **must** be the same as the IP/hostname you specify when using `flocker-deploy` (so `192.168.xxx.xxx` in your case).

**Comment by sukenneth** [comment]
Hi Kai ,

thanks for quick response. what I look at the error on the file "flocker-control.log"? I tried to grep 'error": true', but no in the file. 

the IP/hostname is the same when I generate the control-service TLS certificates. If something wrong on the TLS certificate, can I just regenerate it ?

Thanks!

Kenneth

**Comment by itamarst** [comment]
The most likely cause of failure, as @binocarlos said, is that the control certificate address does not match what you are connecting to. 

> Question - what IP/hostname did you use when generating the control-service TLS certificates?
> The IP/hostname must be the same as the IP/hostname you specify when using flocker-deploy (so 192.168.xxx.xxx in your case).

**Comment by sukenneth** [comment]
Thanks everyone, I think the problem would be on the SSL as I redo the certificate generation and replaces all the new key still have the problem. I will fix SSL first and then back to this connection problem. Will keep it post!

**Comment by itamarst** [comment]
What command did you run to generate the certificate?

**Comment by sukenneth** [comment]
*ON the flocker control node=======================# flocker-ca
create-control-certificate myserver1*




*# flocker-ca create-node-certificate*

**Comment by itamarst** [comment]
The IP/hostname must be the same as the IP/hostname you specify when using flocker-deploy; `myserver1` is not the same as `192.168.X.X`. Remember that this TLS hostname verification: as with websites, the hostname in the certificate has to  match the hostname the HTTP client is connecting to.

**Comment by sukenneth** [comment]
Thanks everyone's input, I recreate the Cluster / control-service certificate / Node certificate and it finally works fine.
