### ISSUE TITLE
Attempt to gather usage statistics

### ISSUE THREAD

**Issue by robhaswell** [ClusterHQ/flocker#179]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-179

We want to be able to measure the number of installations of Flocker for business reasons. 

Reporting usage information without requesting permission from the user is a clear violation of privacy. However, if the install methods necessitates communication with services operated by us, this could be use as an indicator. Alternatively we must request permission to report usage information.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-179. You are welcome to file additional issues in GitHub if that's easier for you.
