### ISSUE TITLE
How the flocker handles the things when control node downtime

### ISSUE THREAD

**Issue by TejaNagaSrikanth** [ClusterHQ/flocker#1799]
Hello Flocker!
Thanks to flocker team for data persistence enabled. I'm not understanding, How the flocker handles the things when control node down for sometime. Is there any backup control node that can take care everything automatically?. Can you please elaborate.

**Comment by binocarlos** [comment]
@TejaNagaSrikanth HI thanks for your question!

the `flocker-control` process currently does not have High Availability - however it is something we are considering in our product roadmap as we are asked this fairly regularly.

FYI - regarding a backup control service - there is a [jira issue](https://clusterhq.atlassian.net/browse/FLOC-2613) that talks about restoring the control service from a backup file.  The data for the control service lives in `/var/lib/flocker` so it should be possible to restore a process using that data.

Thanks!  You can keep an eye on our [mailing list](https://groups.google.com/forum/#!forum/flocker-users) for updates about new versions.

**Comment by mawfollett** [comment]
Also worth pointing out that if the contol node is down, the containers on
the agent nodes won't be affected. They will carry on running. You just
won't be able to move datasets/containers around.
