### ISSUE TITLE
Configure buildbot to run tests inside vagrant.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#180]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-180

#173 introduced a decorator that detects if the tests are running on a vagrant share, to skip ones that deal with permissions. We should run tests on buildbot under these circumstances to detect when we need to add that decorator.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-180. You are welcome to file additional issues in GitHub if that's easier for you.
