### ISSUE TITLE
Have instructions for running tests in vagrant outside of the shared folder.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#181]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-181

Vagrant's shared folder behaves oddly with regard to permissions (#111, #173). We should have instructions on how to run the tests inside vagrant that doesn't run into that problem.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-181. You are welcome to file additional issues in GitHub if that's easier for you.
