### ISSUE TITLE
Change EBS default type to GP2 instead of standard

### ISSUE THREAD

**Issue by preflightsiren** [ClusterHQ/flocker#1865]
I know that #1553 is currently being discussed, but a short term improvement would be to change the EBS volume type from standard to gp2 as this would significantly improve disk performance at minimal cost to users.

Once the discussion for increased configuration has concluded, users will be able to select the cheaper, standard, magnetic disks for EBS.

**Comment by lukemarsden** [comment]
Thanks for the suggestion! I'm supportive of this small change that would improve our users' experience with EBS, over to @robhaswell to evaluate it.

**Comment by robhaswell** [comment]
Hi, thanks for your suggestion. I'm wary of pulling the rug out from people who are happily using the current instance types - we do or do not know whether that would be a problem for our users. Certainly, performance isn't the primary concern of everybody. GP SSDs are twice as expensive as magnetic which could be a huge factor for some people.

However, I do agree that a short term solution would be useful - it might even be the first correct step. We're discussing with our engineers at the moment about offering specific AWS parameters as config options in the first pass, and this will be one of them. I'll update this ticket when we start working on them.

Thanks!

**Comment by wallnerryan** [comment]
This is the case now. https://github.com/ClusterHQ/flocker/blob/master/flocker/node/agents/ebs.py#L127
