### ISSUE TITLE
why not provide docker image to distribute service??

### ISSUE THREAD

**Issue by moypray** [ClusterHQ/flocker#1867]
I began to use flocker and not familiar with it.  And the configure and distribution for me is very difficult for a new user.

So I wander why not provide a Docker Image to run flocker service and agent. If  he/she wants to use flocker, he/she must know docker.

User just use this command:
 git clone  http://xxx/flocker.git
 docker build . -t  flocker_service:latest
 docker run -ti -v  xx:/config  -v xx:/cert   -p  4235:4235  flocker_service:latest

Ok, I don't case about the python environment such as virtualenv   bla,bla.

Just  a suggestion.

**Comment by adamtheturtle** [comment]
Hi @moypray , thanks for your interest in Flocker. Running Flocker in a container is something that we are looking into and I agree that it could improve the user experience.

To help us improve even more, could you describe what your goals are, and how you intend to use Flocker to achieve them. Also, how did you try to install Flocker (e.g. Ubuntu on AWS) and what were the particular pain points.

Thanks,
Adam

**Comment by itamarst** [comment]
https://twitter.com/lmarsden/status/633978496969220096

**Comment by moypray** [comment]
Hi, @adamtheturtle  & @itamarst  sorry for late to reply. My goals are: 
 * I need fast-clean move data volume across Hosts for docker containers.  Just like 
"Flocker Docker plugin" in Labs Project.

Now I can run control service, dataset-agent/container-agent and plugin in one server.

I success to run container using flocker plugin:( Node A)
" docker run -ti -v mysql-volume-example:/var/test  --volume-driver=flocker   busybox sh"

But I can not setup another node,(nodeB )
on another node: I success to run dataset-agent/container-agent and flocker-dockre-plugin (config the control service address as the former one).  but I failed to  start container in node B

Do you know why?   I have tried "Loopback backend" and  "zfs backend" , my target is to run this on openstack..


thanks very much.

**Comment by moypray** [comment]
Hi, 
I see "The Loopback backend uses node-local storage as storage for datasets. It has no data movement functionality."   I wonder if zfs support data movement functionality??

I mean setup control service in master node,  node A and Node B could use volume from control service.

thanks

**Comment by adamtheturtle** [comment]
Hi,

For data movement to work across nodes the backend types must match. The ZFS backend supports the data movement functionality but the loopback backend does not. As is mentioned in the documentation title for the loopback backend (https://docs.clusterhq.com/en/1.1.0/config/configuring-nodes-storage.html#loopback-block-device-backend-configuration-internal-testing) this backend is only for internal testing purposes.

Try setting up both nodes with ZFS and let us know how it goes. We also very much welcome feedback on how we could make the documentation clearer.

Thanks,
Adam

**Comment by moypray** [comment]
hi @adamtheturtle ,
You mean I need to setup both of nodes to be zfs?

In my understanding,  the data is only store in control master, not in node.  why do I need to setup zfs in another the nodes?  And how they sync the data volumes.

I have a scenery:
  
Node A  <--  Data Center(Mater Node)  --> Node X

but one day I do not want to use Node A anymore, but use Node B instead.
I need all the Data in Data Center(Master Node) to mount to Node B and start container.

so I think Node B or A should store data in local storage.

If I am wrong, correct me?  thanks!

**Comment by itamarst** [comment]
The control service only coordinates, it does not store data. In general storage configuration has to be the same on all nodes:

1. With ZFS backend data is stored on node's local hard drive; data is moved by copying. Nodes need to be able to SSH to each other as root (one of the many reasons it's marked "experimental").
2. With OpenStack backend the data is stored on OpenStack Cinder volumes, and the data is moved by detaching the volume and reattaching it on destination node.

Perhaps you should consider the OpenStack backend? You can try it out on Rackspace if your test system isn't on OpenStack.

**Comment by moypray** [comment]
@itamarst , thanks for your suggestion,  I won't try zfs backend anymore. 

BTW, could you tell me what is the "auth_plugin", and "api_key" mean?  and how to config it ??

**Comment by x1022as** [comment]
@adamtheturtle @itamarst .I am using zfs as backend for both nodes as moypray did.

 I've done some failing trial to migrate volume from one node to another. each trial would result in docker hanging up. flocker service will cost about 30% CPU. I temporarily restart docker service and perform "flocker-volumes destroy xxx" to restore my enviroment.

As I have destroy all the dataset and 'flocker-volumes list' return nothing.  what confuse me is that '/flocker' directory is not empty even if i initialize the flocker pool again. and when I watch ps command, get this message repeatedly:
···
root@flocker-1:~/clusters# ps aux | grep flocker
root      4894  0.0  2.9 123352 60816 ?        Ss   07:21   0:08 /usr/bin/python /usr/local/bin/twistd -noy /usr/local/lib/python2.7/dist-packages/flockerdockerplugin/flockerdockerplugin.tac
root     27214  5.5  3.2 205656 66440 ?        Ssl  Aug24  78:53 /usr/bin/python /usr/local/bin/flocker-control -p tcp:4523 -a tcp:4524 --logfile=/var/log/flocker/flocker-control.log
root     30993  0.0  0.0  28804  1344 ?        D    11:28   0:00 zfs destroy flocker/39ff6b4a-7428-4e8c-bbbe-899b74f37335.default.84a91aab-2c88-4d2c-873a-4d9734f6f442
root     30996  0.0  0.0  28804  1344 ?        D    11:28   0:00 zfs destroy flocker/39ff6b4a-7428-4e8c-bbbe-899b74f37335.default.5c99d6cf-063a-4f4f-9463-5e6d83f00102
root     30997  0.0  0.0  28804  1340 ?        D    11:28   0:00 zfs destroy flocker/39ff6b4a-7428-4e8c-bbbe-899b74f37335.default.819a59d3-ef95-4592-85cd-85606061f679
root     31000  0.0  0.0  28804  1344 ?        D    11:28   0:00 zfs destroy flocker/39ff6b4a-7428-4e8c-bbbe-899b74f37335.default.0ed64ccd-3402-4e90-a232-84862185b1fb
root     31002  0.0  0.0  28804  1348 ?        D    11:28   0:00 zfs destroy flocker/39ff6b4a-7428-4e8c-bbbe-899b74f37335.default.afd6b96b-7b40-4a4a-badf-c18f9562c309
root     31003  0.0  0.0  28804  1340 ?        D    11:28   0:00 zfs destroy flocker/39ff6b4a-7428-4e8c-bbbe-899b74f37335.default.cd5771d3-194e-4557-88c9-0ea780d8f48c
···
···
root@flocker-1:~/clusters# ps aux | grep flocker
root      4894  0.0  2.9 123352 60816 ?        Ss   07:21   0:08 /usr/bin/python /usr/local/bin/twistd -noy /usr/local/lib/python2.7/dist-packages/flockerdockerplugin/flockerdockerplugin.tac
root     27214  5.5  3.2 205656 66440 ?        Ssl  Aug24  78:52 /usr/bin/python /usr/local/bin/flocker-control -p tcp:4523 -a tcp:4524 --logfile=/var/log/flocker/flocker-control.log
root     30404  0.0  0.0  28796  1344 ?        R    11:28   0:00 zfs create -o mountpoint /flocker/39ff6b4a-7428-4e8c-bbbe-899b74f37335.default.5c99d6cf-063a-4f4f-9463-5e6d83f00102 -o readonly off -o refquota 107374182400 flocker/39ff6b4a-7428-4e8c-bbbe-899b74f37335.default.5c99d6cf-063a-4f4f-9463-5e6d83f00102
root     30408  0.0  0.0  28900  1656 ?        R    11:28   0:00 zfs create -o mountpoint /flocker/39ff6b4a-7428-4e8c-bbbe-899b74f37335.default.cd5771d3-194e-4557-88c9-0ea780d8f48c -o readonly off -o refquota 107374182400 flocker/39ff6b4a-7428-4e8c-bbbe-899b74f37335.default.cd5771d3-194e-4557-88c9-0ea780d8f48c
···

It seems flocker is trying to create and destroy some zfs volumes repeatedly. I don't know what these volumes are and why is flocker doing this. 

Flocker services produce plenty of logs, which is really hard for a newbie to debug :( It will be great if you can show us a better way to address problems.

**Comment by itamarst** [comment]
Hi,

As mentioned above and in the documentation, keep in mind that the ZFS backend is experimental.  If we decide to make this backend non-experimental we will improve the various problems with its design.

In this particular case it sounds like you're encountering this issue: https://clusterhq.atlassian.net/browse/FLOC-2013

**Comment by jayfk** [comment]
I tried to set up flocker yesterday on 4 nodes using the online documentation and ended up frustrated because the initial setup is too time consuming. Don't get me wrong, the documentation is really good, but most of the stuff could - and in my opinion should - be automated.

I always thought, that this could be so much easier if they just used `docker-machine` to create a node and provide a little script that does the initial setup.

**Comment by lukemarsden** [comment]
You might all like to try this unofficial installer, which speeds up installation, but is experimental. This is available here: https://docs.clusterhq.com/en/latest/labs/installer.html

Let us know what you think!

**Comment by jayfk** [comment]
@lukemarsden thanks, that looks promising.

**Comment by moypray** [comment]
Hi , I try to setup 2 nodes, but the second can not run containers with docker stuck.

Now when I startup the 2 node, the Server Name is the same. So there is only one NODE could register to control server:

NODE A:  (with control service) (IP: 10.170.193.197)

root@ubuntu:~/flocker/cert# flocker-volumes --control-service localhost list-nodes -l
SERVER                                 ADDRESS
9a13836e-249c-433a-9dd1-def2a54eefa2   127.0.0.1
root@ubuntu:~/flocker/cert#
root@ubuntu:~/flocker/cert# flocker-volumes --control-service localhost list-nodes -l
SERVER                                 ADDRESS
9a13836e-249c-433a-9dd1-def2a54eefa2   10.107.193.200
root@ubuntu:~/flocker/cert#

NODE B: (10.170.193.200)
process:


on Node A, I could run container with flocker-plugin volumes. but on node B I can't.
And it seems the two use the same SERVER NAME..  

 BTW:    The two servers use the VMs which created by virtualbox. maybe some config is the same.
And how does Nodes choose their Server Name??


thanks

**Comment by wallnerryan** [comment]
Closing this because its stale. Please continue discussions on IRC, and flocker-users(google group). The initial issue pointed to distributing flocker as containers, which we experimentally do (https://hub.docker.com/u/clusterhq/)
