### ISSUE TITLE
change agent trying to create when volumes already created.

### ISSUE THREAD

**Issue by wallnerryan** [ClusterHQ/flocker#1872]
I am running into an issue where I create a volume, and its successfully created on the system and attached. Though when I look into the logs, it looks like the convergence loop is telling the dataset agent to try to create it again? 

Flocker Version 1.0.0
Storage Driver version 1.0.0 (ScaleIO)
3 Node Cluster 

Command to create volume
```
/opt/flocker/flocker-1.0.0/flocker-tools/bin/flocker-volumes --control-service=tb.scaleio.local create --node=912bc800 --size=8589934592 --metadata="requester=ryan"
created dataset in configuration, manually poll state with 'flocker-volumes list' to see it show up.
```

See that its attached
```
/opt/flocker/flocker-1.0.0/flocker-tools/bin/flocker-volumes --control-service=tb.scaleio.local list 
{u'483df2c8-92fa-46b3-bebd-79aba44b3910': {u'deleted': False, u'dataset_id': u'483df2c8-92fa-46b3-bebd-79aba44b3910', u'metadata': {u'requester': u'ryan'}, u'maximum_size': 8589934592, u'pr
DATASET                                SIZE    METADATA         STATUS         SERVER               
483df2c8-92fa-46b3-bebd-79aba44b3910   8.00G   requester=ryan   attached ✅   912bc800 (127.0.0.1) 
```

Thought the logs report this message, and looks like it prevents it from moving form one node to the other.
```
{"exception": "flocker.node.agents.blockdevice.DatasetExists", "task_level": [2, 15, 13], "action_type": "agent:blockdevice:create", "reason": "BlockDeviceVolume(blockdevice_id=u'74c48a6600000001', dataset_id=UUID('483df2c8-92fa-46b3-bebd-79aba44b3910'), attached_to=u'5a274f1b-622d-4a97-ae59-856be676cb89', size=8589934592)", "timestamp": 1440403417.60718, "task_uuid": "95f4ec97-3547-4148-8d28-e89be4740a85", "action_status": "failed"}
{"task_uuid": "95f4ec97-3547-4148-8d28-e89be4740a85", "error": true, "timestamp": 1440403417.607512, "message": "Unhandled Error\nTraceback (most recent call last):\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py\", line 75, in run_state_change\n    for subchange in change.changes\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py\", line 75, in <genexpr>\n    for subchange in change.changes\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py\", line 88, in run_state_change\n    context = DeferredContext(maybeDeferred(change.run, deployer))\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py\", line 140, in maybeDeferre
{"exception": "twisted.internet.defer.FirstError", "task_uuid": "95f4ec97-3547-4148-8d28-e89be4740a85", "timestamp": 1440403417.608418, "traceback": "Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'flocker.node.agents.blockdevice.DatasetExists'>: BlockDeviceVolume(blockdevice_id=u'74c48a6600000001', dataset_id=UUID('483df2c8-92fa-46b3-bebd-79aba44b3910'), attached_to=u'5a274f1b-622d-4a97-ae59-856be676cb89', size=8589934592)\n/opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py:75:run_state_change\n/opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py:75:<genexpr>\n/opt/flocker/lib/python2.7/site-packages/flock
{"timestamp": 1440403417.60855, "task_uuid": "95f4ec97-3547-4148-8d28-e89be4740a85", "action_type": "flocker:agent:converge", "action_status": "succeeded", "task_level": [2, 18]}

```

Right before the ```DatasetExsits``` message I am seeing the convergence agent call to create again, and I dont know why its doing so.

```
{"local_changes": "[NodeState(used_ports=None, applications=None, paths=UnicodeFilepathPMap({}), manifestations=UnicodeManifestationPMap({}), hostname=u'192.168.50.12', uuid=UUID('bb3662c3-8470-44ad-a8be-89c0de82f080'), devices=UuidF
{"timestamp": 1440404244.291024, "task_uuid": "163209e8-2852-48a9-9857-b034f60af57f", "action_type": "flocker:agent:send_to_control_service", "action_status": "succeeded", "task_level": [2, 15, 3]}
{"timestamp": 1440404244.292076, "task_uuid": "163209e8-2852-48a9-9857-b034f60af57f", "message_type": "flocker:agent:converge:actions", "calculated_actions": "_InParallel(changes=pvector([CreateBlockDeviceDataset(mountpoint=FilePath(
{"task_uuid": "163209e8-2852-48a9-9857-b034f60af57f", "task_level": [2, 17, 1], "action_type": "agent:blockdevice:create", "mountpoint": "/flocker/2dd8dda6-8371-42a1-9699-c0f54b243457", "timestamp": 1440404244.292317, "action_status"

```

Why might this be happening?

**Comment by itamarst** [comment]
Hi, the logs you pasted are truncated so a bit hard to see (if you're using `journalctl` it truncates terminal output, try piping to file or to `cat`). Could you re-post them?

There are a few cases where this can happen; one of them is that some failure in between creation of volume and creation of filesystem means the volume is not usable. Can't find the JIRA issue offhand but that in particular is a known issue due to creation not being broken up into atomic operations just yet. So it can happen if you move a dataset too soon after it's created.

**Comment by wallnerryan** [comment]
Hi @itamarst thanks, will repost logs.

Few things. In this case, I am not moving dataset, only creating.

- Create Dataset, (Success) I can see its attached and mounted. but errors in logs can be seen upon first convergence loop.

**Comment by itamarst** [comment]
When you say "see it's attached and mounted", how do you see that?

**Comment by wallnerryan** [comment]
I use the storage CLI
```
/usr/bin/emc/scaleio/drv_cfg --query_vols
Retrieved 2 volume(s)
VOL-ID 74c48a6700000002 MDM-ID 2caeb4e8461b8113
```
Which maps to this on the host
```
ls -lah /dev/disk/by-id/emc-vol-2caeb4e8461b8113-74c48a6700000002 
lrwxrwxrwx. 1 root root 12 Aug 24 08:14 /dev/disk/by-id/emc-vol-2caeb4e8461b8113-74c48a6700000002 -> ../../scinib
```

Which can track to here 
```
 df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/scinib              7.8G   36M  7.3G   1% /flocker/2dd8dda6-8371-42a1-9699-c0f54b243457
```

**Comment by itamarst** [comment]
Hm. Hard to say without more logs.

**Comment by wallnerryan** [comment]
using logfile and pip and still truncating, working on getting the logs still

**Comment by itamarst** [comment]
Is this CentOS or Ubuntu?

**Comment by wallnerryan** [comment]
centos

**Comment by itamarst** [comment]
Try `journald -u flocker-dataset-agent > my.log`; some of the lines will be wrapped due to a bug in systemd, so you may need to include the lines after the relevant ones to include all the info.

**Comment by wallnerryan** [comment]
-bash: journald: command not found

**Comment by itamarst** [comment]
Sorry, `journalctl`

**Comment by wallnerryan** [comment]
only seeing these type of logs in my.log with journalctl

```
-- Logs begin at Sun 2015-08-23 01:04:02 UTC, end at Mon 2015-08-24 08:58:09 UTC. --
Aug 24 08:27:01 mdm1.scaleio.local systemd[1]: Stopping Flocker Dataset Agent...
Aug 24 08:27:01 mdm1.scaleio.local systemd[1]: Starting Flocker Dataset Agent...
Aug 24 08:27:01 mdm1.scaleio.local systemd[1]: Started Flocker Dataset Agent.
Aug 24 08:37:43 mdm1.scaleio.local systemd[1]: Stopping Flocker Dataset Agent...
Aug 24 08:37:43 mdm1.scaleio.local systemd[1]: Stopped Flocker Dataset Agent.
Aug 24 08:55:55 mdm1.scaleio.local systemd[1]: Starting Flocker Dataset Agent...
Aug 24 08:55:55 mdm1.scaleio.local systemd[1]: Started Flocker Dataset Agent.
```

**Comment by itamarst** [comment]
So where did the logs above come from?

**Comment by wallnerryan** [comment]
changed the systemd service to use this ```ExecStart=/usr/sbin/flocker-dataset-agent --verbose --logfile=/opt/flocker/dataset.log```

**Comment by itamarst** [comment]
ah

**Comment by itamarst** [comment]
no idea why logs would be truncated then.

**Comment by wallnerryan** [comment]
think its my term, trying on the vnc 1 sec

**Comment by wallnerryan** [comment]
https://gist.github.com/anonymous/40ab10fd5c4759bcb125

**Comment by wallnerryan** [comment]
mind the ```error=true``` bits from the task logs specific to scaleio, this is  bug in how logs are created.

**Comment by wallnerryan** [comment]
Also, there are other volumes on the ending in 0000000<#>, this gist shows your one created with ```..0008``` and there are errors at the bottom pertaining to the other volumes, note that the same error happens for  ```..0008``` as well, looks like the below.

```
{"exception": "flocker.node.agents.blockdevice.DatasetExists", "task_level": [2, 32, 27], "action_type": "agent:blockdevice:create", "reason": "BlockDeviceVolume(blockdevice_id=u'74c48a6d00000008', dataset_id=UUID('d52e985c-a2d3-410b-9f40-0a1122661956'), attached_to=u'55560c76-c23d-4a71-ad7a-6df6636a4f10', size=8589934592)", "timestamp": 1440408085.076184, "task_uuid": "cf0a3582-32cf-4a74-af26-1ae574729c48", "action_status": "failed"}
{"task_uuid": "cf0a3582-32cf-4a74-af26-1ae574729c48", "error": true, "timestamp": 1440408085.076949, "message": "Unhandled Error\nTraceback (most recent call last):\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py\", line 75, in run_state_change\n    for subchange in change.changes\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py\", line 75, in <genexpr>\n    for subchange in change.changes\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/_change.py\", line 88, in run_state_change\n    context = DeferredContext(maybeDeferred(change.run, deployer))\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py\", line 140, in maybeDeferred\n    result = f(*args, **kw)\n--- <exception caught here> ---\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py\", line 751, in run\n    check_for_existing_dataset(api, UUID(hex=self.dataset.dataset_id))\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py\", line 1097, in check_for_existing_dataset\n    raise DatasetExists(volume)\nflocker.node.agents.blockdevice.DatasetExists: BlockDeviceVolume(blockdevice_id=u'74c48a6d00000008', dataset_id=UUID('d52e985c-a2d3-410b-9f40-0a1122661956'), attached_to=u'55560c76-c23d-4a71-ad7a-6df6636a4f10', size=8589934592)\n", "message_type": "twisted:log", "task_level": [2, 35]}
```

**Comment by itamarst** [comment]
Thanks, I'll take a look at those and see if it's sufficient to figure out.

**Comment by itamarst** [comment]
That's still insufficient info, sorry. In particular I need the log message *before* the calculated_changes one, otherwise I can't figure out why it calculated those particular changes. The ones with "local_changes", and the ones where it gets the configuration from the control service so dumps the `Deployment` contents.

**Comment by wallnerryan** [comment]
something I can grep for during creation? logs are hard to catch/sift through

**Comment by itamarst** [comment]
Find the task_uuid of the particular thing manifesting the issue, grep for only messages with that particular task_uuid. You can email me a tarball if it's too big for a gist.

**Comment by wallnerryan** [comment]
@itamarst  here is the new dump https://gist.github.com/wallnerryan/d2cb46991210f5044eb9, this is everything before and after volume creation

Looks for ```0898d0ca-cb58-48f6-8af8-90a24ff9b709``` if you want the dataset ID and look for ```0fa8a232-a711-4a99-ac61-3d5217e80432``` as the task_uuid, you can see all that is relevant, then you can see it start up again and shortly after the ```DatasetExists``` error.

**Comment by itamarst** [comment]
Ok, so first thing I did was:

```
$ cat /tmp/out.md | grep 0fa8a232-a711-4a99-ac61-3d5217e80432 | eliot-tree -l 0 | less
```

And that gives a nice readable tree where you can see what's happening. It detects need for dataset, creates volume on backend, mounts it. All is well. Next I will find the next task_uuid where the problem is occurring and read that output.

**Comment by itamarst** [comment]
See https://warehouse.python.org/project/eliot-tree/

**Comment by itamarst** [comment]
Looking at task_uuid `e7843fb7-cb08-40a5-975d-986a33030f0e`, where `DatasetExists` error happens, the notable log message is this:

> {"local_changes": "[NodeState(used_ports=None, applications=None, paths=UnicodeFilepathPMap({}), manifestations=UnicodeManifestationPMap({}), hostname=u'192.168.50.12', uuid=UUID('5849f3e9-ef2c-4b9f-bd57-13587983b125'), devices=UuidFilepathPMap({})), NonManifestDatasets(datasets=UnicodeDatasetPMap({}))]", "connection": "<AgentAMP at 0x1d89e90>", "task_level": [2, 15, 1], "action_type": "flocker:agent:send_to_control_service", "timestamp": 1440486776.442869, "task_uuid": "e7843fb7-cb08-40a5-975d-986a33030f0e", "action_status": "started"}

Notice that's saying that as far as it's concerned there are no datasets on the node at all.

**Comment by itamarst** [comment]
Question then is, why is nothing being discovered on the node? The error we're getting is:

> {"exception": "flocker.node.agents.blockdevice.DatasetExists", "task_level": [2, 17, 16], "action_type": "agent:blockdevice:create", "reason": "BlockDeviceVolume(blockdevice_id=u'dc54ae9c00000002', dataset_id=UUID('0898d0ca-cb58-48f6-8af8-90a24ff9b709'), attached_to=u'30d3fb6d-470a-424b-af46-c8a2f05fd6f2', size=8589934592)", "timestamp": 1440486777.712715, "task_uuid": "4bd7d311-07db-46dd-b451-a39f36e5a4d1", "action_status": "failed"}

Elsewhere I see that:

> {"block_device_compute_instance_id": "30D3FB6D-470A-424B-AF46-C8A2F05FD6F2", "timestamp": 1440486775.36178, "task_uuid": "0fa8a232-a711-4a99-ac61-3d5217e80432", "block_device_size": 8589934592, "block_device_path": "/dev/scinib", "dataset_id": "0898d0ca-cb58-48f6-8af8-90a24ff9b709", "block_device_id": "dc54ae9c00000002", "message_type": "agent:blockdevice:created", "task_level": [2, 15, 86]}

Notice the compute_instance_id between the two is the same... but one is capitalized and one is lower-case.

**Comment by wallnerryan** [comment]
hmmm, any ideas why this could be? Tried on ```1.0.0pre1``` as well, did run into this during our testing for 1.0, just when I started prototyping on centos 7 for something else.

Could the capital / lowercase be an issue?

**Comment by itamarst** [comment]
Yep, cause we compare them as opaque strings.

**Comment by itamarst** [comment]
And they only come out of the IBlockDeviceAPI layer, we don't modify them, so the bug is somewhere in there.

**Comment by wallnerryan** [comment]
hmm, looks like a driver issue then, let me look, thanks for helping track it this far

**Comment by wallnerryan** [comment]
ah, i think I found the issue, let me make a patch and try it again, will close it if it fixes it
