### ISSUE TITLE
The flocker-dataset-agent log format is in a mess

### ISSUE THREAD

**Issue by yang1992** [ClusterHQ/flocker#1889]
The log message "\n" is not prased,so the log format is in a mess!
Exp:
"task_uuid": "bb7690ea-e81b-40d5-8283-1b5bfb51b3a4", "error": true, "timestamp": 1440646734.109415, "message": "main function encountered error\nTraceback (most recent call last):\n  File \"/root/flocker-client/lib/python2.7/site-packages/flocker/node/script.py\", line 65, in flocker_dataset_agent_main\n    options=options,\n  File \"/root/flocker-client/lib/python2.7/site-packages/flocker/common/script.py\", line 221, in main\n    self._react(run_and_log, [], _reactor=self._reactor)\n  File \"/root/flocker-client/lib/python2.7/site-packages/twisted/internet/task.py\", line 882, in react\n..........................

**Comment by itamarst** [comment]
The logs are in JSON, so that is JSON quoting. You can pipe a log line into a tool like `jq` to make it more readable/

**Comment by itamarst** [comment]
Alternatively, https://warehouse.python.org/project/eliot-tree/ will allow you to see a whole tree of messages from Flocker.

**Comment by lukemarsden** [comment]
@yang1992 hi there, thanks for trying Flocker! Were you able to resolve the underlying issue that led you to you filing this bug?
