### ISSUE TITLE
Parameterize the username accepted by _InMemoryPublicKeyChecker

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#189]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-189

It's confusing and unnecessarily complicated to use the username of the user running the process.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-189. You are welcome to file additional issues in GitHub if that's easier for you.
