### ISSUE TITLE
Failed to move data volume from NodeA to NodeB.

### ISSUE THREAD

**Issue by moypray** [ClusterHQ/flocker#1895]
Hi, I success to setup the Docker Plugin Project.

on Node A: (run control service and run flocker-docker-plugin & Agent as Node A):
root@ubuntu:~/flocker/cert# ps -ef | grep flocker
root      1722     1 32 22:12 pts/0    00:30:59 /usr/bin/python /usr/local/bin/flocker-control
root      1727     1  4 22:12 pts/0    00:04:11 /usr/bin/python /usr/local/bin/flocker-dataset-agent
root      1741     1 10 22:12 pts/0    00:10:29 /usr/bin/python /usr/local/bin/flocker-container-agent
root      1749     1 18 22:12 ?        00:17:34 /usr/bin/python /usr/local/bin/twistd -noy /usr/local/lib/python2.7/dist-packages/flockerdockerplugin/flockerdockerplugin.tac

  on Node B: (only plugin & flocker agent)
root@ubuntu:~/flocker/cert# ps -ef | grep flocker
root      1722     1 32 22:12 pts/0    00:30:59 /usr/bin/python /usr/local/bin/flocker-control
root      1727     1  4 22:12 pts/0    00:04:11 /usr/bin/python /usr/local/bin/flocker-dataset-agent
root      1741     1 10 22:12 pts/0    00:10:29 /usr/bin/python /usr/local/bin/flocker-container-agent
root      1749     1 18 22:12 ?        00:17:34 /usr/bin/python /usr/local/bin/twistd -noy /usr/local/lib/python2.7/dist-packages/flockerdockerplugin/flockerdockerplugin.tac

After that I start some containers on both Node A and Node B:

On NodeA(control service) we can see the zfs dataset:

root@ubuntu:~/flocker/cert# docker run -ti -v node1_test1:/test  --volume-driver=flocker  busybox sh

And it success on both of the two Nodes.

DATASET                                SIZE      METADATA           STATUS         SERVER
d7612dfc-cc14-48c9-80b3-6f2b15919be0   100.00G   name=node1_test1   attached ✅   9a13836e (10.107.193.197)
599f099c-cd1d-47ca-976e-deef14b33e8b   100.00G   name=node2_test1   attached ✅   cbb8da36 (10.107.193.200)
d5de32a8-b1ab-462a-a7d6-ff2036bba03d   100.00G   name=node2_test3   attached ✅   cbb8da36 (10.107.193.200)
af066ddd-757d-4c3f-b621-6aafa6c5db2a   100.00G   name=node2_test    attached ✅   cbb8da36 (10.107.193.200)

But when I tried to use NodeA dataset on NodeB, I got failure.

Below is the Log:  // seems to move volume to NodeB failed.
Could you have time to have a look at it ?? thanks.

=======================================================================
{"exception": "exceptions.IOError", "task_level": [2, 4, 2], "action_type": "flocker:p2pdeployer:handoff", "reason": "('Bad exit', ['flocker-volume', '--config', '/etc/flocker/volume.json', 'snapshots', '210c6c33-686e-4c89-a305-1638ed1824d2', 'default.af066ddd-757d-4c3f-b621-6aafa6c5db2a'], 255, '')", "timestamp": 1440772994.958445, "task_uuid": "ce9a6565-466c-4e4a-ae60-93d958d14d70", "action_status": "failed"}
{"task_uuid": "ce9a6565-466c-4e4a-ae60-93d958d14d70", "error": true, "timestamp": 1440772995.011083, "message": "Unhandled Error\nTraceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/flocker/node/_change.py\", line 88, in run_state_change\n    context = DeferredContext(maybeDeferred(change.run, deployer))\n  File \"/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py\", line 140, in maybeDeferred\n    result = f(*args, **kw)\n  File \"/usr/local/lib/python2.7/dist-packages/flocker/node/_deploy.py\", line 303, in run\n    RemoteVolumeManager(destination))\n  File \"/usr/local/lib/python2.7/dist-packages/flocker/volume/service.py\", line 347, in handoff\n    pushing = maybeDeferred(self.push, volume, destination)\n--- <exception caught here> ---\n  File \"/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py\", line 140, in maybeDeferred\n    result = f(*args, **kw)\n  File \"/usr/local/lib/python2.7/dist-packages/flocker/volume/service.py\", line 275, in push\n    getting_snapshots = destination.snapshots(volume)\n  File \"/usr/local/lib/python2.7/dist-packages/flocker/volume/_ipc.py\", line 123, in snapshots\n    volume.name.to_bytes()]\n  File \"/usr/local/lib/python2.7/dist-packages/flocker/common/_ipc.py\", line 90, in get_output\n    raise IOError(\"Bad exit\", remote_command, e.returncode, e.output)\nexceptions.IOError: ('Bad exit', ['flocker-volume', '--config', '/etc/flocker/volume.json', 'snapshots', '210c6c33-686e-4c89-a305-1638ed1824d2', 'default.af066ddd-757d-4c3f-b621-6aafa6c5db2a'], 255, '')\n", "message_type": "twisted:log", "task_level": [2, 5]}
{"exception": "twisted.internet.defer.FirstError", "task_uuid": "ce9a6565-466c-4e4a-ae60-93d958d14d70", "timestamp": 1440772995.01149, "traceback": "Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <type 'exceptions.IOError'>: ('Bad exit', ['flocker-volume', '--config', '/etc/flocker/volume.json', 'snapshots', '210c6c33-686e-4c89-a305-1638ed1824d2', 'default.af066ddd-757d-4c3f-b621-6aafa6c5db2a'], 255, '')\n/usr/local/lib/python2.7/dist-packages/flocker/node/_change.py:88:run_state_change\n/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:140:maybeDeferred\n/usr/local/lib/python2.7/dist-packages/flocker/node/_deploy.py:303:run\n/usr/local/lib/python2.7/dist-packages/flocker/volume/service.py:347:handoff\n--- <exception caught here> ---\n/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:140:maybeDeferred\n/usr/local/lib/python2.7/dist-packages/flocker/volume/service.py:275:push\n/usr/local/lib/python2.7/dist-packages/flocker/volume/_ipc.py:123:snapshots\n/usr/local/lib/python2.7/dist-packages/flocker/common/_ipc.py:90:get_output\n]]\n", "message_type": "eliot:traceback", "reason": "FirstError[#0, [Failure instance: Traceback: <type 'exceptions.IOError'>: ('Bad exit', ['flocker-volume', '--config', '/etc/flocker/volume.json', 'snapshots', '210c6c33-686e-4c89-a305-1638ed1824d2', 'default.af066ddd-757d-4c3f-b621-6aafa6c5db2a'], 255, '')\n/usr/local/lib/python2.7/dist-packages/flocker/node/_change.py:88:run_state_change\n/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:140:maybeDeferred\n/usr/local/lib/python2.7/dist-packages/flocker/node/_deploy.py:303:run\n/usr/local/lib/python2.7/dist-packages/flocker/volume/service.py:347:handoff\n--- <exception caught here> ---\n/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py:140:maybeDeferred\n/usr/local/lib/python2.7/dist-packages/flocker/volume/service.py:275:push\n/usr/local/lib/python2.7/dist-packages/flocker/volume/_ipc.py:123:snapshots\n/usr/local/lib/python2.7/dist-packages/flocker/common/_ipc.py:90:get_output\n]]", "task_level": [2, 6]}
{"timestamp": 1440772995.011819, "task_uuid": "ce9a6565-466c-4e4a-ae60-93d958d14d70", "action_type": "flocker:agent:converge", "action_status": "succeeded", "task_level": [2, 7]}

**Comment by lukemarsden** [comment]
Thanks for writing this up! It looks like you're using the ZFS backend, is that right? Where are these machines, are they on AWS or OpenStack or otherwise connected to a supported storage backend? Or are they bare metal with local storage?

If possible, it would be better if you could use one of the [supported storage backends](https://docs.clusterhq.com/en/1.2.0/introduction/index.html#supported-storage-backends). If that's not possible, we can still try to help you debug the issues you're seeing with the ZFS backend, but please note that this is experimental and we don't yet recommend it for production usage.

**Comment by moypray** [comment]
Yes, zfs  backend.  Linux Server is ubntu14.04.

And @lukemarsden ,which backend do you recommend?  thanks for you kind supports.

it seems to excute "ssh -q -i /etc/flocker/id_rsa_flocker -l root -o StrictHostKeyChecking=no -o ControlMaster=no -o PreferredAuthentications=publickey -p 22 10.107.193.197 flocker-volume --config /etc/flocker/volume.json snapshots 210c6c33-686e-4c89-a305-1638ed1824d2 default.af066ddd-757d-4c3f-b621-6aafa6c5db2a"  .

I am checking it why.

**Comment by lukemarsden** [comment]
Is it a VM running on cloud infrastructure or a bare metal server with local storage? If it's cloud, which cloud?

**Comment by moypray** [comment]
It is a VM created by virtualbox.  when I execute that command in shell. it failed too.

Maybe the sshkey is not correct.  thanks again.

**Comment by lukemarsden** [comment]
OK, in VirtualBox ZFS is the only backend you can use :)

Can you paste the complete output of what happens when the command fails when you run it manually? How did you provision these VMs by the way? Did you do it manually or with Vagrant?

**Comment by moypray** [comment]
ah. success, the ssh key copied to /etc/flocker/id_rsa_flocker  is not correct.
I can run containers with data volumes on other node.
thanks~~

**Comment by lukemarsden** [comment]
Great! I presume you saw the setup docs here? https://docs.clusterhq.com/en/1.2.0/config/zfs-configuration.html#creating-a-zfs-pool

How could they be improved? Would it have helped to have an example of what commands to run, and if so, what commands did *you* run? :)

**Comment by lukemarsden** [comment]
I'm thinking something like this:
```
--> open a terminal window on each node, then, on each node, run:
$ ssh-keygen -f /etc/flocker/id_rsa_flocker
--> then cat the id_rsa_flocker.pub key on each node
$ cat /etc/flocker/id_rsa_flocker.pub
--> paste it into the /root/.ssh/authorized_keys file on **every other node**
$ echo "<public key from other node>" >> /root/.ssh/authorized_keys
```

**Comment by moypray** [comment]
Yes, the more detailed the more helpful.
Actually the docs of flocker is very good.  As the beginner don't know what would happen, so I missed some rules in docs, for example ,could config nodes as 127.0.0.1 or localhost, but I do not know why and config as 127.0.0.1, when I see the "ssh xxx" command I know, Ah. it will use this IP address.

Maybe the tips like this should be highlight.  It may cause mistake for new user.

**Comment by lukemarsden** [comment]
Ah, this is really useful feedback, thanks! Where in the docs do we talk about localhost/127.0.0.1, can you post a link please?

**Comment by moypray** [comment]
Actually the docs say it . But I missed.  I see it when I read it, but forget when config the Node.  Ah.....It is ugly mistake made by myself.

https://docs.clusterhq.com/en/1.1.0/config/configuring-nodes-storage.html

**Comment by moypray** [comment]
And BTW, do you have openstack backend config docs?? I mean the openstack side, not the flocker side. 
As openstack env is very complex, some config is wrong, maybe can not work.

thanks~

**Comment by lukemarsden** [comment]
I'm curious to know if the [experimental installer](https://docs.clusterhq.com/en/latest/labs/installer.html) would have made your installation experience smoother. It tries to automate a lot of the steps, which should help reduce configuration mistakes.

I'm afraid we don't have any docs on how to configure OpenStack itself. We are still learning how to configure it ourselves. If you figure out any tips, we'd be happy to add them to our docs.

**Comment by moypray** [comment]
OK.  And maybe I will work on flocker for a long time. Keep in touch. thanks .

For service and CLI/agent auth key and configs , why not save to ~/.flocker/cert  ~/.flocker/config bla bla.

When I run flocker-volumes I must set the control-service address. And if config in user home folder, for different user, could setup different configs..

Just a suggestion, maybe you have other considering.

**Comment by lukemarsden** [comment]
Thanks for the suggestion. If you use the [unofficial installer](https://docs.clusterhq.com/en/latest/labs/installer.html), it recommends making a "clusters" directory and then `cd`ing into the directory where the `cluster.yml` file is for your specific cluster, then you can just run `flocker-volumes` with no optional args. Please give it a try and please let us know what your feedback is on the user experience compared to the long-form installation instructions!
