### ISSUE TITLE
Using existing uuid for identifying machines.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#190]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-190

systemd provides a [machine-id](http://www.freedesktop.org/software/systemd/man/machine-id.html) and zfs provides an guid for each pool. We should probably re-use one or the other of these id's rather than creating our own. (At least by default)

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-190. You are welcome to file additional issues in GitHub if that's easier for you.
