### ISSUE TITLE
Add eliot logging for ssh commands run by `_sshconfig.py`

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#192]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-192

make it possible to debug failures by exposing all of the ssh commands we run and their output and exit status

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-192. You are welcome to file additional issues in GitHub if that's easier for you.
