### ISSUE TITLE
`flocker-node configure-ssh`

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#193]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-193

Replace the big piles of shell scripts in `_sshconfig.py` with a Python program installed on nodes.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-193. You are welcome to file additional issues in GitHub if that's easier for you.
