### ISSUE TITLE
Functional tests leave behind Docker containers and images

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#195]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-195

* Remove all containers `docker ps --all --quiet | xargs docker rm`
* Remove all images `docker images --quiet | xargs docker rmi`
* run functional tests `trial flocker`
* Note the list of images and containers that have been left behind.

```
(flocker-150)[vagrant@localhost vagrant]$ docker images --quiet
757c87bf57eb
6801e08a9709
d200959a3e91
37fca75d01ff
fd5373b3d938
a9eb17255234
a9eb17255234

(flocker-150)[vagrant@localhost vagrant]$ docker ps --all --quiet
13829d92757d
7f2a89d68598
fe204b5edc87
1dc24a636c2a
39807bf6161e
```

I guess the images aren't so bad and they help to speed up subsequent tests, but the containers won't be used again and should probably be cleaned up.

Or else perhaps it's worth cleaning up all the containers from tox before running the tests.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-195. You are welcome to file additional issues in GitHub if that's easier for you.
