### ISSUE TITLE
dataset agent log: The Service Catalog is empty (using latest devstack)

### ISSUE THREAD

**Issue by garthmbooth** [ClusterHQ/flocker#1964]
I'm running a devstack setup stacked on 9/19, it's default Identity API is V2. Apparently, endpoints in devstack are now created with the v3 API. So, when you run "openstack endpoint list" returns null. The patch for this issue is "Review in progress" here: https://review.openstack.org/#/c/215870/5. I've applied it to my environment and it did fix this particular issue.

Full exception error is attached.

Garth

flocker-dataset-agent.log.4:{"task_uuid": "34d3d8fd-c3cf-4e3d-a127-9a307ef68a6a", "error": true, "timestamp": 1442812479.493094, "message": "Unhandled Error\nTraceback (most recent call last):\n  File \"/opt/flocker/local/lib/python2.7/site-packages/twisted/protocols/amp.py\", line 889, in _commandReceived\n    deferred = self.dispatchCommand(box)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/twisted/protocols/amp.py\", line 946, in dispatchCommand\n    return maybeDeferred(responder, box)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 140, in maybeDeferred\n    result = f(*args, **kw)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/twisted/protocols/amp.py\", line 1035, in doit\n    return maybeDeferred(aCallable, **kw).addCallback(\n--- <exception caught here> ---\n  File \"/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 140, in maybeDeferred\n    result = f(*args, **kw)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/flocker/control/_protocol.py\", line 410, in cluster_updated\n    self.agent.cluster_updated(configuration, state)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/flocker/node/_loop.py\", line 446, in cluster_updated\n    state=cluster_state))\n  File \"/opt/flocker/local/lib/python2.7/site-packages/machinist/_logging.py\", line 102, in receive\n    output = super(FiniteStateLogger, self).receive(input)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/machinist/_fsm.py\", line 534, in receive\n    self._world.output(output, adapter(input))\n  File \"/opt/flocker/local/lib/python2.7/site-packages/machinist/_fsm.py\", line 592, in output\n    method(context)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/flocker/node/_loop.py\", line 127, in output_UPDATE_STATUS\n    state=context.state))\n  File \"/opt/flocker/local/lib/python2.7/site-packages/machinist/_logging.py\", line 102, in receive\n    output = super(FiniteStateLogger, self).receive(input)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/machinist/_fsm.py\", line 534, in receive\n    self._world.output(output, adapter(input))\n  File \"/opt/flocker/local/lib/python2.7/site-packages/machinist/_fsm.py\", line 592, in output\n    method(context)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/flocker/node/_loop.py\", line 314, in output_CONVERGE\n    self.deployer.discover_state(known_local_state))\n  File \"/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py\", line 1472, in discover_state\n    compute_instance_id = api.compute_instance_id()\n  File \"/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py\", line 1804, in compute_instance_id\n    self._instance_id = self._api.compute_instance_id()\n  File \"/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/cinder.py\", line 337, in compute_instance_id\n    for server in self.nova_server_manager.list():\n  File \"/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/cinder.py\", line 74, in _run_with_logging\n    return method(*args, **kwargs)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/novaclient/v2/servers.py\", line 591, in list\n    return self._list(\"/servers%s%s\" % (detail, query_string), \"servers\")\n  File \"/opt/flocker/local/lib/python2.7/site-packages/novaclient/base.py\", line 64, in _list\n    _resp, body = self.api.client.get(url)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/keystoneclient/adapter.py\", line 170, in get\n    return self.request(url, 'GET', **kwargs)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/novaclient/client.py\", line 90, in request\n    **kwargs)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/keystoneclient/adapter.py\", line 206, in request\n    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/keystoneclient/adapter.py\", line 95, in request\n    return self.session.request(url, method, **kwargs)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/keystoneclient/utils.py\", line 318, in inner\n    return func(*args, **kwargs)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/keystoneclient/session.py\", line 334, in request\n    base_url = self.get_endpoint(auth, **endpoint_filter)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/keystoneclient/session.py\", line 635, in get_endpoint\n    return auth.get_endpoint(self, **kwargs)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/keystoneclient/auth/identity/base.py\", line 220, in get_endpoint\n    service_name=service_name)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/keystoneclient/utils.py\", line 318, in inner\n    return func(*args, **kwargs)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/keystoneclient/service_catalog.py\", line 216, in url_for\n    raise exceptions.EmptyCatalog(_('The service catalog is empty.'))\nkeystoneclient.exceptions.EmptyCatalog: The service catalog is empty.\n", "message_type": "twisted:log", "task_level": [1]}

**Comment by wallnerryan** [comment]
hi @garthmbooth have you retried this? Is this still an issues?

**Comment by garthmbooth** [comment]
I'm no longer see this issue w/ more recent versions of devstack, so it's been fixed.

**Comment by xmik** [comment]
I've got this error when using OpenStack backend. It went away after I set `tenant_id` in `/etc/flocker/agent.yml`.
