### ISSUE TITLE
Enhancements: Application Volume Parameters

### ISSUE THREAD

**Issue by garthmbooth** [ClusterHQ/flocker#1965]
Can the application volume parameters (or something equivalent) be extended to support the following:

1. Ability to name the volume that is created for the container. 
2. Ability to specify attachment of a specific volume (i.e. don't assume a new volume needs to be created every time the app is deployed).

**Comment by wallnerryan** [comment]
You can do this with flocker docker plugin today.

`docker volume create --name=yourvolumename -d flocker`
`docker run -v yourvolumename:/path/in/container ...`

**Comment by garthmbooth** [comment]
The original enhancement was not specific enough (my bad). The request is directed to the Flocker yml file attributes available for defining the containerized application. How would one do this via the Flocker deployment application yml file? Maybe those attributes are just missing from the Flocker documentation or I missed them, here https://docs.clusterhq.com/en/1.6.1/control/cli/application-config.html

**Comment by wallnerryan** [comment]
thanks I have re-opened this one.

**Comment by wallnerryan** [comment]
@garthmbooth as a note, using `flocker-deploy` will be going away, please user our [integrations with docker cli](https://docs.clusterhq.com/en/1.8.0/control/plugin/index.html) and this way you can use docker compose directly with all attributes.
