### ISSUE TITLE
Unable to deploy application with attached volume

### ISSUE THREAD

**Issue by garthmbooth** [ClusterHQ/flocker#1967]
I'm not sure if this is a defect or an issue w/ my configuration. So, I'm primarily looking for suggestions on how to debug this issue further. The log files are way too large to create paste entries, I can certainly ftp them if you have a location l can drop them in. If you need additional information, just let me know.

Here's the details:

I'm running a devstack setup stacked on 9/19. I have 2 VMs, 1 running the Flocker Control Service and 1 running the Flocker Agent Node. I'm running Flocker version 1.3. My app and deployment yml files are listed below. I have ~6GB of free memory on the agent node.

I don't see any obvious errors on the control service node, /var/log/flocker/flocker-control.log the agent node, /var/log/flocker-dataset-agent.log or /var/log/flocker/flocker-container-agent.log.

The agent node is showing 0 containers spun up.

The cinder volume only gets created if I stop and restart the dataset-agent and then it posts the following error:

{"task_uuid": "498f50b3-fe25-4e52-99a4-de4f5b217b6f", "error": true, "timestamp": 1442945801.265162, "message": "Unhandled Error\nTraceback (most recent call last):\n  File \"/opt/flocker/local/lib/python2.7/site-packages/flocker/common/script.py\", line 221, in main\n    self._react(run_and_log, [], _reactor=self._reactor)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/task.py\", line 903, in react\n    _reactor.run()\n  File \"/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/base.py\", line 1192, in run\n    self.mainLoop()\n  File \"/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/base.py\", line 1201, in mainLoop\n    self.runUntilCurrent()\n--- <exception caught here> ---\n  File \"/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/base.py\", line 824, in runUntilCurrent\n    call.func(*call.args, **call.kw)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/machinist/_logging.py\", line 102, in receive\n    output = super(FiniteStateLogger, self).receive(input)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/machinist/_fsm.py\", line 534, in receive\n    self._world.output(output, adapter(input))\n  File \"/opt/flocker/local/lib/python2.7/site-packages/machinist/_fsm.py\", line 592, in output\n    method(context)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/flocker/node/_loop.py\", line 314, in output_CONVERGE\n    self.deployer.discover_state(known_local_state))\n  File \"/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py\", line 1494, in discover_state\n    device_path = api.get_device_path(volume.blockdevice_id)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py\", line 1813, in get_device_path\n    blockdevice_id)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/cinder.py\", line 551, in get_device_path\n    device_path = self._get_device_path_api(cinder_volume)\n  File \"/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/cinder.py\", line 534, in _get_device_path_api\n    raise UnattachedVolume(volume.id)\nflocker.node.agents.blockdevice.UnattachedVolume: 39214b59-a0e7-4264-9baf-b16c342a542a\n", "message_type": "twisted:log", "task_level": [1]}

ubuntu@flocker-control-service:~/Flocker$ cat ubuntu-application.yml
"version": 1
"applications":
  "ubuntu-picasso-vol":
    "image": "ubuntu"
    "mem_limit": 2000000000
    "volume":
       "mountpoint": "/var/lib/mysql"
       "maximum_size": "1G"
ubuntu@flocker-control-service:~/Flocker$ cat ubuntu-deployment.yml
"version": 1
"nodes":
   "10.0.0.4": ["ubuntu-picasso-vol"]
ubuntu@flocker-control-service:~/Flocker$

I've deployed the app as follows:

ubuntu@flocker-control-service:~/Flocker$ sudo flocker-deploy flocker-control-service.cxo.hp.com ubuntu-deployment.yml ubuntu-application.yml
The cluster configuration has been updated. It may take a short while for changes to take effect, in particular if Docker images need to be pulled

The list of containers and datasets is listed below:

ubuntu@flocker-control-service:~/Flocker$ sudo curl --cacert /etc/flocker/cluster.crt --cert /etc/flocker/user.crt --key /etc/flocker/user.key https://flocker-control-service.cxo.hp.com:4523/v1/configuration/datasets
[{"deleted": false, "dataset_id": "495d6cd7-441c-4bb0-9f12-b346337f7f86", "maximum_size": 1073741824, "primary": "a7a1c44c-4ff0-43e0-9292-4506c44b822b", "metadata": {"name": "ubuntu-picasso-vol"}}]
ubuntu@flocker-control-service:~/Flocker$
ubuntu@flocker-control-service:~/Flocker$
ubuntu@flocker-control-service:~/Flocker$ sudo curl --cacert /etc/flocker/cluster.crt --cert /etc/flocker/user.crt --key /etc/flocker/user.key https://flocker-control-service.cxo.hp.com:4523/v1/configuration/containers
[{"memory_limit": 2000000000, "node_uuid": "a7a1c44c-4ff0-43e0-9292-4506c44b822b", "name": "ubuntu-picasso-vol", "image": "ubuntu:latest", "restart_policy": {"name": "never"}, "volumes": [{"mountpoint": "/var/lib/mysql", "dataset_id": "495d6cd7-441c-4bb0-9f12-b346337f7f86"}]}]

**Comment by garthmbooth** [comment]
Additional details:
1. Docker Version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:19:00 UTC 2015
 OS/Arch:      linux/amd64

2. Flocker-Control-Service and Flocker-agent-node-1 OS release
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

3. Flocker version
1.3.1

4. ip addr on flocker-control-service and hostname
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:76:ef:22 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.3/24 brd 10.0.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fdbe:3023:f947:0:f816:3eff:fe76:ef22/64 scope global dynamic
       valid_lft 86396sec preferred_lft 14396sec
    inet6 fe80::f816:3eff:fe76:ef22/64 scope link
       valid_lft forever preferred_lft foreve

hostname flocker-control-service

5. ip addrs on flocker-agent-node-1 and hostname
 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether fa:16:3e:28:78:2c brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.4/24 brd 10.0.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fdbe:3023:f947:0:f816:3eff:fe28:782c/64 scope global dynamic
       valid_lft 86399sec preferred_lft 14399sec
    inet6 fe80::f816:3eff:fe28:782c/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:f9:9f:5f:1a brd ff:ff:ff:ff:ff:ff
    inet 172.17.42.1/16 scope global docker0
       valid_lft forever preferred_lft forever

hostname flocker-agent-node-1

6. fdisk and lsblk for flocker-control-service
ubuntu@flocker-control-service:~/Flocker$ sudo fdisk -l

Disk /dev/vda: 21.5 GB, 21474836480 bytes
4 heads, 32 sectors/track, 327680 cylinders, total 41943040 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x000b4c0a

   Device Boot      Start         End      Blocks   Id  System
/dev/vda1   *        2048    41943039    20970496   83  Linux
ubuntu@flocker-control-service:~/Flocker$ sudo lsblk --all
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sr0     11:0    1   418K  0 rom
vda    253:0    0    20G  0 disk
└─vda1 253:1    0    20G  0 part /
ram0     1:0    0    64M  0 disk
ram1     1:1    0    64M  0 disk
ram2     1:2    0    64M  0 disk
ram3     1:3    0    64M  0 disk
ram4     1:4    0    64M  0 disk
ram5     1:5    0    64M  0 disk
ram6     1:6    0    64M  0 disk
ram7     1:7    0    64M  0 disk
ram8     1:8    0    64M  0 disk
ram9     1:9    0    64M  0 disk
loop0    7:0    0         0 loop
loop1    7:1    0         0 loop
loop2    7:2    0         0 loop
loop3    7:3    0         0 loop
loop4    7:4    0         0 loop
loop5    7:5    0         0 loop
loop6    7:6    0         0 loop
loop7    7:7    0         0 loop
ram10    1:10   0    64M  0 disk
ram11    1:11   0    64M  0 disk
ram12    1:12   0    64M  0 disk
ram13    1:13   0    64M  0 disk
ram14    1:14   0    64M  0 disk
ram15    1:15   0    64M  0 disk

7. fdisk and lsblk for flocker-agent-node-1
ubuntu@flocker-agent-node-1:/var/log/flocker$ sudo fdisk -l

Disk /dev/vda: 85.9 GB, 85899345920 bytes
4 heads, 32 sectors/track, 1310720 cylinders, total 167772160 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x000b4c0a

   Device Boot      Start         End      Blocks   Id  System
/dev/vda1   *        2048   167772159    83885056   83  Linux
ubuntu@flocker-agent-node-1:/var/log/flocker$ sudo lsblk --all
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sr0     11:0    1   418K  0 rom
vda    253:0    0    80G  0 disk
└─vda1 253:1    0    80G  0 part /
ram0     1:0    0    64M  0 disk
ram1     1:1    0    64M  0 disk
ram2     1:2    0    64M  0 disk
ram3     1:3    0    64M  0 disk
ram4     1:4    0    64M  0 disk
ram5     1:5    0    64M  0 disk
ram6     1:6    0    64M  0 disk
ram7     1:7    0    64M  0 disk
ram8     1:8    0    64M  0 disk
ram9     1:9    0    64M  0 disk
loop0    7:0    0         0 loop
loop1    7:1    0         0 loop
loop2    7:2    0         0 loop
loop3    7:3    0         0 loop
loop4    7:4    0         0 loop
loop5    7:5    0         0 loop
loop6    7:6    0         0 loop
loop7    7:7    0         0 loop
ram10    1:10   0    64M  0 disk
ram11    1:11   0    64M  0 disk
ram12    1:12   0    64M  0 disk
ram13    1:13   0    64M  0 disk
ram14    1:14   0    64M  0 disk
ram15    1:15   0    64M  0 disk

**Comment by garthmbooth** [comment]
Here's what I'm seeing (continously) in the flocker-control-agent.log on the flocker-agent-node-1:

{
  "fsm_next_state": "<ConvergenceLoopStates=CONVERGING>",
  "task_level": [
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2,
    2
  ],
  "action_type": "fsm:transition",
  "timestamp": 1442963802.650624,
  "fsm_output": [
    "<ConvergenceLoopOutputs=STORE_INFO>"
  ],
  "task_uuid": "49d8e3e6-3250-4d21-8384-9ea707f5c72f",
  "action_status": "succeeded"
}

Here's what I'm seeing in the flocker-dataset-agent.log on the flocker-agent-node:
{"fsm_next_state": "<ConvergenceLoopStates=CONVERGING>", "task_level": [2, 3, 2, 2, 2, 2], "action_type": "fsm:transition", "timestamp": 1442963970.936903, "fsm_output": ["<ConvergenceLoopOutputs=STORE_INFO>"], "task_uuid": "7d3c817f-46ae-4fe6-bb6a-32f7ee703d35", "action_status": "succeeded"}
{"fsm_next_state": "<ClusterStatusStates=KNOWLEDGEABLE>", "task_level": [2, 3, 2, 2, 3], "action_type": "fsm:transition", "timestamp": 1442963970.93759, "fsm_output": ["<ClusterStatusOutputs=UPDATE_STATUS>"], "task_uuid": "7d3c817f-46ae-4fe6-bb6a-32f7ee703d35", "action_status": "succeeded"}

Here's what I'm seeing in the flocker-control-service.log on the control-service node:

{"task_uuid": "8cb9637f-14d9-4712-b0e9-f537b236230e", "task_level": [2, 2, 2, 2, 1], "action_type": "flocker:controlservice:send_cluster_state", "timestamp": 1442964094.012424, "configuration": "Deployment(nodes=NodePSet([Node(applications=ApplicationPSet([Application(environment=pmap({}), volume=AttachedVolume(mountpoint=FilePath(u'/var/lib/mysql'), manifestation=Manifestation(primary=True, dataset=Dataset(deleted=False, dataset_id=u'bf83b3cc-8f1f-4257-a8e4-1432ac2ca49b', maximum_size=1073741824, metadata=pmap({u'name': u'mysql-picasso-vol-2'})))), memory_limit=2000000000, running=True, image=DockerImage(tag=u'5.6.17', repository=u'mysql'), restart_policy=RestartOnFailure(maximum_retry_count=1), command_line=None, ports=PortPSet([]), name=u'mysql-picasso-vol-2', links=LinkPSet([]), cpu_shares=None)]), manifestations=UnicodeManifestationPMap({u'bf83b3cc-8f1f-4257-a8e4-1432ac2ca49b': Manifestation(primary=True, dataset=Dataset(deleted=False, dataset_id=u'bf83b3cc-8f1f-4257-a8e4-1432ac2ca49b', maximum_size=1073741824, metadata=pmap({u'name': u'mysql-picasso-vol-2'})))}), uuid=UUID('a7a1c44c-4ff0-43e0-9292-4506c44b822b'))]), leases=Leases({}))", "state": "DeploymentState(nodes=NodestatePSet([NodeState(used_ports=None, applications=None, paths=None, manifestations=None, hostname=u'10.0.0.4', uuid=UUID('a7a1c44c-4ff0-43e0-9292-4506c44b822b'), devices=None)]), nonmanifest_datasets=UnicodeDatasetPMap({}))", "action_status": "started"}
{"task_uuid": "8cb9637f-14d9-4712-b0e9-f537b236230e", "action_status": "started", "action_type": "flocker:controlservice:send_state_to_agent", "timestamp": 1442964094.014429, "agent": "<ControlAMP at 0x7f6b15687e90>", "task_level": [2, 2, 2, 2, 2, 1]}
{"task_uuid": "8cb9637f-14d9-4712-b0e9-f537b236230e", "action_status": "started", "action_type": "flocker:controlservice:send_state_to_agent", "timestamp": 1442964094.017091, "agent": "<ControlAMP at 0x7f6b1556e690>", "task_level": [2, 2, 2, 2, 3, 1]}
{"timestamp": 1442964094.019513, "task_uuid": "8cb9637f-14d9-4712-b0e9-f537b236230e", "action_type": "flocker:controlservice:send_cluster_state", "action_status": "succeeded", "task_level": [2, 2, 2, 2, 4]}
{"timestamp": 1442964094.020334, "task_uuid": "8cb9637f-14d9-4712-b0e9-f537b236230e", "action_type": "eliot:remote_task", "action_status": "succeeded", "task_level": [2, 2, 2, 3]}
{"timestamp": 1442964094.030224, "task_uuid": "8cb9637f-14d9-4712-b0e9-f537b236230e", "action_type": "flocker:controlservice:send_state_to_agent", "action_status": "succeeded", "task_level": [2, 2, 2, 2, 2, 3]}
{"timestamp": 1442964094.0311, "task_uuid": "8cb9637f-14d9-4712-b0e9-f537b236230e", "action_type": "flocker:controlservice:send_state_to_agent", "action_status": "succeeded", "task_level": [2, 2, 2, 2, 3, 3]}

**Comment by binocarlos** [comment]
@garthmbooth Hi - many thanks for the feedback :-) @lukemarsden has kindly offered to take a look at this with you as I'm a bit racked up with other things - thanks again

**Comment by lukemarsden** [comment]
Hi @garthmbooth - sorry for the latency on this - we are all insanely busy working on several customer deployments this week. Maybe we can schedule some time to work on this together next week?

**Comment by garthmbooth** [comment]
Hi @lukemarsden - thanks for the follow-up here. I definitely understand the need to focus on your customer deployments. Yes, I'd definitely like to setup some time early next week to work on this together. My schedule is pretty open Mon-Wed, so just let me know a time and I'll cancel any conflicting meetings I may have to meet. This is definitely a fairly high priority for me to close out this investigation.

In the meantime, I'm basically seeing that "fsm_next_state": "<ConvergenceLoopStates=CONVERGING>" continuously recurring in the dataset-agent node log file. I do see a volume get automatically created. As a test, I tried manually attaching that volume to the agent node VM and that does work.

 I don't see any errors in the log files, so I've been digging through some of the Flocker python code to try and debug, but no luck so far. Any pointers to investigate prior to us talking next week, I may be able to triage a bit further.

Thanks,
Garth

**Comment by lukemarsden** [comment]
Hey @garthmbooth - how about 3pm on Wednesday? Send me an email to luke@clusterhq.com and we'll get something scheduled.

**Comment by aedades** [comment]
Was there any resolution to this?  I am also having trouble deploying a single application to a node:

**Comment by exarkun** [comment]
> but the flocker-container-agent will not start on one of the instances (though both node instances are set up the same way).

It sounds like this is probably a different issue than @garthmbooth encountered.  Would you mind opening a new issue and describing your deployment there?  It would also help to include any information you have about the container agent not starting (its log output, for example).  Details about how you set up the cluster are definitely useful as well.

Thanks.

**Comment by exarkun** [comment]
Also, mainly as a note to future readers, it's normal for Flocker (~1.x) agents to loop on those FSM tasks.  The agents spend all their time in that loop looking for work to do.

**Comment by garthmbooth** [comment]
Just a quick note here, I was able to get this working by moving to 1.4.0 AND manually applying the fix for the floating IP issue, https://github.com/ClusterHQ/flocker/issues/1903.

**Comment by wallnerryan** [comment]
Closing because this issue is stale. If the users on this issue have further issues please open a new one with your specific issue or contact us on IRC _(#clusterhq on freenode)_ and [flocker-users](https://groups.google.com/forum/#!forum/flocker-users)
