### ISSUE TITLE
VMs

### ISSUE THREAD

**Issue by davedoesdev** [ClusterHQ/flocker#1974]
Have you got any plans to manage storage for VMs (QEMU/KVM)?

**Comment by binocarlos** [comment]
@davedoesdev Hi - not presently (as far as I know) however we are always open to suggestions (and pull requests).  I'm interested - what is your use case for wanting this?

Another quick point is that Flocker is not container specific - it has a REST API that can be used from any application/provisioning system that can speak HTTP & TLS.  As long as there is a Flocker backend for the type of storage you want then it can be used without containers.

**Comment by davedoesdev** [comment]
Use case is KVM/Capstan with RBD (Ceph) disks.
Is the backend for the storage type or the thing the storage is being attached to?

**Comment by binocarlos** [comment]
@davedoesdev Hi - thanks for the info - the backend is an interface between generic Flocker commands like `CreateVolume` and the storage type being used.

We currently don't have a Ceph driver but there has been discussion around building one - keep an eye on our blog as if we implement one we will publish it there.

**Comment by davedoesdev** [comment]
OK so then the docker plugin calls the REST API to get the volumes etc?

**Comment by davedoesdev** [comment]
Closing this. I think I'll do the volume attaching etc at the orchestration level.
I can see value in the docker-plugin doing this automatically but (a) I'm going to try writing my own orchestrator and (b) I want to attach Ceph block devices to VMs.

**Comment by lukemarsden** [comment]
Hey @davedoesdev - just so I understand, does this mean you still plan to use Flocker but just not the Flocker Docker plugin? If you'd be interested in working on a Flocker Ceph driver, we'd love to support you doing that. Here are our latest docs on Flocker driver development: http://build.clusterhq.com/results/docs/driver-doc-update-FLOC-3011/build-9924/gettinginvolved/plugins/index.html

**Comment by davedoesdev** [comment]
@lukemarsden what does Flocker offer me over using the Ceph utilities and APIs directly?

**Comment by lukemarsden** [comment]
It offers a consistent REST API that supports many different types of underlying storage. For example, you may want to be able to deploy the same apps to your KVM/Ceph cluster as onto EC2/EBS. I'd be interested to hear more about your use case.

**Comment by davedoesdev** [comment]
I'm planning to do some orchestration using Salt, using Docker/Weave for containers and Capstan/Fold for VMs. I'm thinking about what to do about storage, hence my interest in Flocker.

I looked at the REST API but it seems only to be about containers (I may have missed something). Do I get the underlying storage details and can I talk about storage without having containers?

An alternative would to build the storage abstraction into the orchestration layer.

**Comment by lukemarsden** [comment]
Thanks! The dataset API is documented here, and is independent of containers: https://docs.clusterhq.com/en/1.4.0/reference/api.html#dataset-api-endpoints

**Comment by davedoesdev** [comment]
Thanks @lukemarsden. How does one get the underlying block device from the dataset?

**Comment by binocarlos** [comment]
@davedoesdev Flocker automatically attaches block devices (in the case of AWS EBS and OpenStack Cinder) and mounts them formatted with a filesystem.  You could ask the REST API for a list of datasets - this will show you the host path it has been mounted to (usually a path under `/flocker`) then compare the hosts mount table to find the underlying block device.  Does this help?

**Comment by davedoesdev** [comment]
Probably not: I need the rbd upfront and qemu is best off using librbd directly  http://docs.ceph.com/docs/master/rbd/qemu-rbd/

> QEMU can pass a block device from the host on to a guest, but since QEMU 0.15, there’s no need to
> map an image as a block device on the host. Instead, QEMU can access an image as a virtual block 
> device directly via librbd. This performs better because it avoids an additional context switch, and can 
> take advantage of RBD caching
