### ISSUE TITLE
Diagnose why renaming a filesystem fails.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#199]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-199

When changing the owner of a filesystem, we assume that any error renaming the filesystem is due to the target already existing, and report it as such. There are probably other reasons this could fail. We should determine the cause and report it as such.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-199. You are welcome to file additional issues in GitHub if that's easier for you.
