### ISSUE TITLE
Verifying cluster setup

### ISSUE THREAD

**Issue by aedades** [ClusterHQ/flocker#2050]
Hello,

I followed the docs to create a simple configuration of one control node, and two cluster nodes, AWS EC2 instances.  The control node has the following files:
cluster.crt  control-service.crt  control-service.key
and the cluster nodes have:
agent.yml  cluster.crt  node.crt  node.key

Two issues so far:
* The flocker-container-agent is not starting on one node.  I issue the start command and it just hangs.  Not sure what logs would be helpful here - All I have is the flocker-dataset-agent logs on that node (it starts fine).

* The other node has both the dataset agent and the container agent running, but when I issue the flocker-deploy command, it appears to run fine, but the container is never deployed to the node.

Please advise if it is possible something is wrong with the initial set up...  I am ultimately just interested in using the Flocker Docker plugin, which I have installed on the nodes now, but I need a working cluster to use it.

user@ubuntu:~/flocker$ flocker-deploy 10.190.88.218 test.yml docker-compose.yml
The cluster configuration has been updated. It may take a short while for changes to take effect, in particular if Docker images need to be pulled.

Where the files are defined:

user@ubuntu:~/flocker$ cat test.yml
"version": 1
"nodes":
  "10.190.88.219": ["redis"]
user@ubuntu:~/flocker$ cat docker-compose.yml
redis:
  image: dockerfile/redis
  ports:
  - "6379:6379"
  volumes: ["/data"]

The flocker-control log shows:

{"task_uuid": "bf44d36f-c76d-4463-a900-578af9068ac0", "task_level": [1], "action_type": "api:request", "timestamp": 1444753987.648715, "method": "POST", "action_status": "started", "request_path": "/v1/configuration/_compose"}
{"task_uuid": "bf44d36f-c76d-4463-a900-578af9068ac0", "task_level": [3, 1], "action_type": "api:json_request", "timestamp": 1444753987.649337, "json": {"applications": {"redis": {"image": "dockerfile/redis", "ports": ["6379:6379"], "volumes": ["/data"]}}, "deployment": {"nodes": {"10.190.88.219": ["redis"]}, "version": 1}}, "action_status": "started"}
{"timestamp": 1444753987.651143, "task_uuid": "bf44d36f-c76d-4463-a900-578af9068ac0", "message_type": "flocker-control:persistence:unchanged-deployment-not-saved", "task_level": [3, 2]}
{"task_uuid": "bf44d36f-c76d-4463-a900-578af9068ac0", "code": 200, "task_level": [3, 3], "action_type": "api:json_request", "timestamp": 1444753987.651442, "json": null, "action_status": "succeeded"}
{"timestamp": 1444753987.651745, "task_uuid": "bf44d36f-c76d-4463-a900-578af9068ac0", "action_type": "api:request", "action_status": "succeeded", "task_level": [4]}
{"task_uuid": "8ae9d433-7585-47c9-974f-36fd18ac89c0", "error": false, "timestamp": 1444753987.652255, "message": "\"10.120.26.136\" - - [13/Oct/2015:16:33:07 +0000] \"POST /v1/configuration/_compose HTTP/1.1\" 200 4 \"-\" \"-\"", "message_type": "twisted:log", "task_level": [1]}
...

The logs on the node constantly show:

{"fsm_next_state": "<ConvergenceLoopStates=CONVERGING>", "task_level": [3], "action_type": "fsm:transition", "timestamp": 1444753949.569859, "fsm_output": ["<ConvergenceLoopOutputs=CONVERGE>"], "task_uuid": "ad7ddd1d-15fb-48e1-8c78-7480d5d6908f", "action_status": "succeeded"}
{"fsm_identifier": "<flocker.node._loop.ConvergenceLoop object at 0x7fe7e6f1be90>", "fsm_input": "<ConvergenceLoopInputs=ITERATION_DONE>", "timestamp": 1444753950.570602, "fsm_rich_input": null, "action_status": "started", "task_uuid": "1c6d83bd-0361-439a-ab6e-7d09f58335d9", "action_type": "fsm:transition", "fsm_state": "<ConvergenceLoopStates=CONVERGING>", "task_level": [1]}
{"task_uuid": "1c6d83bd-0361-439a-ab6e-7d09f58335d9", "cluster_state": "DeploymentState(nodes=NodestatePSet([NodeState(applications=None, paths=None, manifestations=None, hostname=u'10.190.88.219', uuid=UUID('afbea1a9-6569-4e0d-a322-b5b6db0b4752'), devices=None)]), nonmanifest_datasets=UnicodeDatasetPMap({}))", "action_type": "flocker:agent:converge", "desired_configuration": "Deployment(nodes=NodePSet([Node(applications=ApplicationPSet([Application(environment=pmap({}), volume=AttachedVolume(mountpoint=FilePath('/data'), manifestation=Manifestation(primary=True, dataset=Dataset(deleted=False, dataset_id=u'86a1b907-d54b-4701-8394-bf316e183e67', maximum_size=None, metadata=pmap({u'name': u'redis'})))), memory_limit=None, running=True, image=DockerImage(tag=u'latest', repository=u'dockerfile/redis'), restart_policy=RestartNever(), command_line=None, ports=PortPSet([Port(internal_port=6379, external_port=6379)]), name=u'redis', links=LinkPSet([]), cpu_shares=None)]), manifestations=UnicodeManifestationPMap({u'86a1b907-d54b-4701-8394-bf316e183e67': Manifestation(primary=True, dataset=Dataset(deleted=False, dataset_id=u'86a1b907-d54b-4701-8394-bf316e183e67', maximum_size=None, metadata=pmap({u'name': u'redis'})))}), uuid=UUID('afbea1a9-6569-4e0d-a322-b5b6db0b4752'))]), leases=Leases({}))", "timestamp": 1444753950.571258, "action_status": "started", "task_level": [2, 1]}
{"timestamp": 1444753950.5728, "task_uuid": "1c6d83bd-0361-439a-ab6e-7d09f58335d9", "message_type": "flocker:agent:converge:actions", "task_level": [2, 2], "calculated_actions": "_Sequentially(changes=pvector([]))"}
{"timestamp": 1444753950.573313, "task_uuid": "1c6d83bd-0361-439a-ab6e-7d09f58335d9", "action_type": "flocker:agent:converge", "action_status": "succeeded", "task_level": [2, 3]}
{"fsm_next_state": "<ConvergenceLoopStates=CONVERGING>", "task_level": [3], "action_type": "fsm:transition", "timestamp": 1444753950.573675, "fsm_output": ["<ConvergenceLoopOutputs=CONVERGE>"], "task_uuid": "1c6d83bd-0361-439a-ab6e-7d09f58335d9", "action_status": "succeeded"}
...

**Comment by rongnguyen** [comment]
Hi aedades,

Have you resolved this issue?
