### ISSUE TITLE
New install of Vagrant image: flocker-docker-plugin: Error looking up volume plugin flocker

### ISSUE THREAD

**Issue by matt-deboer** [ClusterHQ/flocker#2112]
Upon a fresh vagrant install, attempting to verify whether the flocker-docker-plugin is working (by issuing the suggested command `docker run -v apples:/data --volume-driver flocker busybox sh -c "echo hello > /data/file.txt"` ), the following output is generated:
    
    Error response from daemon: Error looking up volume plugin flocker: Plugin not found

I found this after first seeing similar results on my own installation against 2 fresh centos 7.1 nodes (running docker 1.8.3). The docker plugin docs seem to mention that socket files should be placed at /run/docker/plugins, but I don't see any files being placed there in either the vagrant setup, or on standard machine install.

I noticed that the /run/docker/plugins, /etc/docker/plugins, and /usr/lib/docker/plugins directories don't exist by default after a docker install, and none of them exist or were populated by an install of the flocker-docker-plugin.

Do I need to link any of the flocker sockets into one of the docker plugin folders to make this work?

**Comment by wallnerryan** [comment]
@matt-deboer, did you install with our latest vagrant instructions? Not sure this includes the flocker docker plugin install yet. You may need to install the flocker-docker-plugin in the centos machines.

I assume you have `node1` and `node2` vagrant machines when you run `vagrant status`

**Comment by wallnerryan** [comment]
also, running ```systemctl status flocker-docker-plugin``` should let you know if its installed.

**Comment by matt-deboer** [comment]
Indeed; it was not installed on the vagrant image. 
going through the additional config/install steps for plugin gets me past it.
btw--anything changed for docker 1.9?
