### ISSUE TITLE
Installation instructions missing controller setup

### ISSUE THREAD

**Issue by stmcginnis** [ClusterHQ/flocker#2155]
Previous versions of the Flocker installation instructions walked through installing the controller node and configuring the cluster certificates. Current (1.6.1) documentation only contains:

* Installing the Flocker Client
* Installing Flocker Node Services
* Installing the Flocker Plugin for Docker

There is no mention of how to install the controller nor how to set up the certificates. It's not until you get to the Flocker Plugin for Docker section that you are instructed to run a flocker-ca command that fails with a reference to running flocker-ca initialize.

Earlier versions of the installation instructions walked through controller node setup and certificate generation.

**Comment by dwgebler** [comment]
Hi,
Thank you for raising an issue; the information you're looking for is now contained in the "Configuring Flocker" portion of the docs, found at https://docs.clusterhq.com/en/latest/config/index.html

**Comment by stmcginnis** [comment]
Thanks @dwgebler. So that should probably be reorganized, since the earlier section for configuring the Docker plugin assumes that piece has already been complete.

**Comment by davidoliverSP2** [comment]
Hi @stmcginnis
Thanks for bringing this to our attention. I've created a high-priority issue for us to address it - https://clusterhq.atlassian.net/browse/FLOC-3420

**Comment by davidoliverSP2** [comment]
Hi @stmcginnis 

FLOC-3420 is now complete, and we've released 1.7.2 which addresses the problems seen when installing the plugin.

The installation of the plugin is now a step (step 3) in the Installing the Node Services instructions: https://docs.clusterhq.com/en/1.7.2/install/install-node.html

The generation of certificates for the plugin now has its own page in the configuring section:
https://docs.clusterhq.com/en/1.7.2/config/generate-api-plugin.html 

This step now comes after the `flocker-ca initialize` instruction in https://docs.clusterhq.com/en/1.7.2/config/configuring-authentication.html, which was the cause of the issues yourself and others had reported.

The final configuration steps relating to the plugin (enabling and testing), are now found in the Enabling Flocker Agent service: https://docs.clusterhq.com/en/1.7.2/config/enabling-agent-service.html

These changes mean that users are not having to revisit each node to install and enable the plugin - its done at the same time as the other Flocker node services. Hopefully it will make our documentation a lot easier to follow page by page.

Thanks again for bringing this to our attention - if you have any other problems with the documentation, or any suggestions for making it easier to follow, please do not hesitate to contact me.

Cheers,
Dave

PS: If you email me your address (david.oliver@clusterhq.com) I'll send you a Flocker t-shirt as a thanks for your contribution!! Alternatively, if you're still at DockerCon, look for our stand - they should have a big box of tees and will be able to discuss Flocker in more depth!
