### ISSUE TITLE
For Storage  backend option, does it supports IBM Softlayer storage options ? 

### ISSUE THREAD

**Issue by wzymaster** [ClusterHQ/flocker#2164]
We have some dockerized app running on IBM Softlayer VM and we plan to leverage Docker swarm for cluster provisioning/orchestration. However, I am wondering if there is any plan to support SoftLayer storage options, like Block storage (iSCSI storage) option ?

If not,  is it possible to manually create my own NFS share on a master node and share it across all nodes and then Flocker works with it ? 

thanks !

**Comment by wallnerryan** [comment]
Here is a list of our current storage backends. They do support iSCSI. If Softlayer runs on OpenStack, we support OpenStack cinder, but nothing specific to IBM.

We do not support the NFS use-case that you mention but will hopefully support NAS/NFS options in the future.

Thanks
