### ISSUE TITLE
Trouble installing flocker-volumes

### ISSUE THREAD

**Issue by jonathan-kosgei** [ClusterHQ/flocker#2178]
I'm having trouble setting up kubernetes with flocker for volume management on centos 7.0. I've set up a cluster to completeness, however I lack the flocker-volumes command, which I need to create persistent disks for kubernetes.

**Comment by lukemarsden** [comment]
This thread continued here: https://groups.google.com/forum/#!topic/flocker-users/I4PGAJI3bhQ

**Comment by Stephenitis** [comment]
Hello @jonathan-kosgei 
I believe our docs has a hole here for users doing their manual installing this locally and pointing it to your control-service

1. locally run `curl -sSL https://get.flocker.io/ | sh` to install the variety of tools
you should see this line
```
Installed /usr/local/bin/uft-flocker-volumes
```

2. use the `uft-flocker-volumes` command or the alias `flocker-volumes`
```sh
$   flocker-volumes --control-service=52.91.104.245 list-nodes
# take node id example 443b87ed
# create volume
$   flocker-volumes --control-service=52.91.104.245 create -n 443b87ed -s 50G -m name=my-flocker-volume

# list your volumes
$   flocker-volumes --control-service=52.91.104.245 list
```


The flocker-volumes command is really a wrapper around a docker container that executes your command.

```
cat /usr/local/bin/uft-flocker-volumes
docker run -ti --rm -v /:/host -v $PWD:/pwd clusterhq/uft:latest flocker-volumes <YOUR COMMAND>
```

You should be able to work with it either way.
