### ISSUE TITLE
VolumeHub installation should be in Flocker docs

### ISSUE THREAD

**Issue by Stephenitis** [ClusterHQ/flocker#2218]
Steps to install and setup Flocker with VolumeHub should be placed in our docs.

only currently supports aws

### to install a new cluster using amazon easy installer (uft-tools)

1. sign up at volumehub
2. make sure you have downloaded latest uft-flocker-tools and follow the installation instructions
2. execute this last step
$ `TOKEN="<VOLUME_HUB_TOKEN>" volume-hub-agents-install cluster.yml`

### To install Volume Hub Agents on an existing cluster
The Volume Hub Agents push metadata about your cluster (which hosts, datasets and containers are running) into the Volume Hub. This is how to install them.

On the control service node, run:

$ TARGET=control-service TOKEN="<VOLUME_HUB_TOKEN>" \
    sh -c 'curl -ssL https://get-volumehub.clusterhq.com/ |sh'
On exactly one of the agent nodes, run:

$ TARGET=agent-node RUN_FLOCKER_AGENT_HERE=1 \
    TOKEN="<VOLUME_HUB_TOKEN>" \
    sh -c 'curl -ssL https://get-volumehub.clusterhq.com/ |sh'
On all the rest of the agent nodes, run:

$ TARGET=agent-node TOKEN="<VOLUME_HUB_TOKEN>" \
    sh -c 'curl -ssL https://get-volumehub.clusterhq.com/ |sh'

**Comment by davidoliverSP2** [comment]
This issue will be handled by https://clusterhq.atlassian.net/browse/FLOC-3549

Thanks @Stephenitis
