### ISSUE TITLE
quickstart installer docs needs streamlining

### ISSUE THREAD

**Issue by Stephenitis** [ClusterHQ/flocker#2219]
currently user goes on this path
1. http://doc-dev.clusterhq.com/install/installer.htm
2. http://doc-dev.clusterhq.com/labs/installer.html#labs-installer
3. http://doc-dev.clusterhq.com/labs/installer-getstarted.html

Page 1. does not provide much value and has alot of distracting links. We should redirect them to 2. immediately with a greater visual emphases on getting started.

**Comment by davidoliverSP2** [comment]
Clean up the number of clicks before the user gets to the information.

**Comment by davidoliverSP2** [comment]
This issue will be handled by https://clusterhq.atlassian.net/browse/FLOC-3548

Thanks @Stephenitis
