### ISSUE TITLE
there is no single page referencing flocker docker plugin by itself

### ISSUE THREAD

**Issue by Stephenitis** [ClusterHQ/flocker#2221]
http://doc-dev.clusterhq.com/install/install-node.html

It is referenced as *the optional clusterhq-flocker-docker-plugin package* 

I suggest isolating it in a subsection(is that the right term) on the install-node page. and placing a additional link in the sidebar.
![installing the flocker node services 2015-11-23 10-58-45](https://cloud.githubusercontent.com/assets/1712162/11346396/502208fe-91d1-11e5-8b5c-143e17e39ba3.png)

**Comment by Stephenitis** [comment]
testing response.

**Comment by davidoliverSP2** [comment]
we should explain why it is an optional install? or not mention that it is optional?

**Comment by davidoliverSP2** [comment]
Link back from here to the Flocker introduction page

**Comment by davidoliverSP2** [comment]
The issue will be handled by https://clusterhq.atlassian.net/browse/FLOC-3546.

Closing. Thanks @Stephenitis
