### ISSUE TITLE
Run pod on different nodes(using flocker volume, Push and handoff to another node), mount data dir is error in k8s?

### ISSUE THREAD

**Issue by ttllyy** [ClusterHQ/flocker#2234]
flocker version:1.7.1
backend:zfs
node1 uuid: cat /etc/flocker/volume.json
{"version": 1, "uuid": "b083f1ba-75b0-41dd-8b2a-33bd4e624e81"}
node2 uuid: cat /etc/flocker/volume.json
{"version": 1, "uuid": "1172eee5-35e1-406c-9ad4-863609b51291"}

I create  dataset on node1:
DATASET                                SIZE    METADATA            STATUS         SERVER
3cac6429-0d25-4eda-a595-3e93898a2150   5.00G   name=my-vol-demo3   attached ✅   eb4f2b7d (node1)

I run pod(mount dataset) on node1, and add some files in mount path.
add 1.txt and 2.txt file to mount path.
ls /flocker/b083f1ba-75b0-41dd-8b2a-33bd4e624e81.default.3cac6429-0d25-4eda-a595-3e93898a2150
1.txt    2.txt

I delete pod and run pod(same created yml) on node2, yml 
push and handoff
node1:
remove /flocker/b083f1ba-75b0-41dd-8b2a-33bd4e624e81.default.3cac6429-0d25-4eda-a595-3e93898a2150
create new dir  /flocker/1172eee5-35e1-406c-9ad4-863609b51291.default.3cac6429-0d25-4eda-a595-3e93898a2150

node2: /etc 
1172eee5-35e1-406c-9ad4-863609b51291.default.3cac6429-0d25-4eda-a595-3e93898a2150
1.txt  2.txt 

b083f1ba-75b0-41dd-8b2a-33bd4e624e81.default.3cac6429-0d25-4eda-a595-3e93898a2150
empty

Pod(on node2) mount path is b083f1ba-75b0-41dd-8b2a-33bd4e624e81.default.3cac6429-0d25-4eda-a595-3e93898a2150.
So path is empty, but I want to visit 1.txt and 2.txt.

Create same pod (same pod.yml) on different nodes, how to mount same data path?

**Comment by wallnerryan** [comment]
hey @ttllyy let me test this out on my k8s cluster. What are you using to create the pod? Kubectl? Also what versions of flocker and k8s are you using?

**Comment by ttllyy** [comment]
@wallnerryan 
k8s version: 1.1.2
flocker version: 1.7.1
command: kubectl create -f  yml
I am create pod by running kubectl create command. using k8s guide ngnix pod example.

**Comment by wallnerryan** [comment]
@ttllyy kubernetes + flocker should handle remounting and giving the mountpath back to the container automatically. All you need to do is stop the POD and start the POD.

Are you actually changing the mount manually in your example above?
```
push and handoff
node1:
remove /flocker/b083f1ba-75b0-41dd-8b2a-33bd4e624e81.default.3cac6429-0d25-4eda-a595-3e93898a2150
create new dir /flocker/1172eee5-35e1-406c-9ad4-863609b51291.default.3cac6429-0d25-4eda-a595-3e93898a2150
```

**Comment by wallnerryan** [comment]
closing as ZFS is deprecated. Any other specific Kuberentes issues can be files as a new issue.
