### ISSUE TITLE
Use a key-value store to coordinate ssh authentication for zfs peer-to-peer storage

### ISSUE THREAD

**Issue by F21** [ClusterHQ/flocker#2295]
Having to ensure that all nodes can access each other using private key ssh authentication can be extremely difficult to automate and keep the `/root/.ssh/authorized_key` in sync on every host, especially in large deployments where nodes can come and go quite often.

It would be extremely useful if flocker can use a key-value store to coordinate this. Maybe an automated workflow like so:
1. When the node flocker is on launches, flocker automatically registers with the k/v store. 
2. When a node needs to contact another node, it uses the k/v store to discover the other node and uses that to broker access.

Something like [docker/libkv](https://github.com/docker/libkv) can be used to easily provide support for consul, etcd, boltdb and zookeeper.

Users of zfs peer-to-peer storage most likely already have a k/v store running to support docker's overlay networking, so I think it's a feature that would fit in quite well.

Another thing that would be nice to have is to be able to have flocker use a user other than root to log into different nodes to transfer data.

**Comment by wallnerryan** [comment]
@F21 thank you for your feedback. ZFS is currently experimental and not recommended for production and has many known bugs. I will bring your suggestion back to the team.

**Comment by wallnerryan** [comment]
Closing as ZFS support is currently deprecated.
