### ISSUE TITLE
Can't delete dataset.

### ISSUE THREAD

**Issue by ttllyy** [ClusterHQ/flocker#2309]
@wallnerryan 

flocker version:1.8.0
backend: zfs

truncate --size 100G /var/lib/pool-0
ZFS_MODULE_LOADING=yes zpool create flocker /var/lib/pool-0

create two dataset successful.

delete dataset:
uft-flocker-volumes destroy -d 4a6b05f1-3583-4944-b01f-a4af0873a78f
uft-flocker-volumes destroy -d 1ca54b5c-4860-4c3b-bf40-abbfe10bfba2 
marked dataset as deleted. poll list manually to see it disappear.

delete successful

But I reboot ubuntu system.
list dataset: uft-flocker-volumes list
DATASET                                SIZE     METADATA                                        STATUS     SERVER
4a6b05f1-3583-4944-b01f-a4af0873a78f   75.00G   name=demo0                deleting   eb4f2b7d (xx.xx.xx.xx)
1ca54b5c-4860-4c3b-bf40-abbfe10bfba2   5.00G    name=my-vol-demo1      deleting   eb4f2b7d (xx.xx.xx.xx)

datasets status is always deleting. I can't realy delete dataset. 
If I can't delete dataset, so I can't destroy zfs's pool..
run: zpool destroy flocker
umount2: Device or resource busy
umount: /flocker: device is busy.

**Comment by ttllyy** [comment]
Where to save metadata? I think delete manual flocker's metadata and reboot system and restart flocker service. So can solve the problem?

**Comment by ttllyy** [comment]
Get /v1/state/datasets 
All dataset deleted is true. But uft-flocker-volumes list command: status is deleting.

**Comment by ttllyy** [comment]
delete dataset, dataset status is always  deleting.

**Comment by ttllyy** [comment]
@wallnerryan 
dataset is always deleting.

**Comment by wallnerryan** [comment]
The hold onto the metadata of deleted datasets, so datasets existing with `deleted` after deleting them is OK. However, if they still say `deleting` it sounds like ZFS is having issues deleting the dataset. ZFS is experimental and has many issues, ill bring your feedback to the team. Thank you

**Comment by wallnerryan** [comment]
closing as ZFS support is deprecated.
