### ISSUE TITLE
Error occurs, when deploying Tutorial: Deploying and Migrating MongoDB

### ISSUE THREAD

**Issue by drngsl** [ClusterHQ/flocker#2340]
Hi!
I want to do the test according to the steps on https://docs.clusterhq.com/en/1.8.0/tutorials_examples/tutorial/exposing-ports.html.
Of course, I deploy the application successfully with command flocker-deploy,
but where I want to connect to the mongo DB of container, the error is printed like
root@ubuntu50:/# mongo 103.30.0.50
MongoDB shell version: 2.4.9
connecting to: 103.30.0.50/test
Sun Dec 13 04:28:18.190 Error: couldn't connect to server 103.30.0.50:27017 at src/mongo/shell/mongo.js:147
exception: connect failed

Here , the container was deployed on host 103.30.0.50

So, why this error occured?

**Comment by wallnerryan** [comment]
Hi @drngsl Did you make sure the container is successfully running? Sometimes it takes a little for the container to start. What is the ouput of `docker ps -a` and `docker logs <name of mongo container>`

**Comment by drngsl** [comment]
@wallnerryan , Sorry for replying you so late.
I create this container again with docker cmd and image clusterhq/mongodb.
and the the output of docker ps -a like this:
root@ubuntu:~# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                                 NAMES
3a0f67ab6bc8        clusterhq/mongodb   "/bin/sh"           18 minutes ago      Up 18 minutes       27017/tcp, 0.0.0.0:27107->27107/tcp   romantic_torvalds
and of course, the when execute cmd docker logs romantic_torvalds, I can see all the history cmd I have executed in the container.

**Comment by wallnerryan** [comment]
@drngsl looks like your container is running on port `27107` and your trying to connect to `27017`


3a0f67ab6bc8 clusterhq/mongodb "/bin/sh" 18 minutes ago Up 18 minutes **27017/tcp, 0.0.0.0:27107->27107/tcp** romantic_torvalds

root@ubuntu50:/# mongo 103.30.0.50
MongoDB shell version: 2.4.9
connecting to: 103.30.0.50/test
Sun Dec 13 04:28:18.190 Error: couldn't connect to server **103.30.0.50:27017** at
