### ISSUE TITLE
There is a bug about deleting dataset for loopback

### ISSUE THREAD

**Issue by ttllyy** [ClusterHQ/flocker#2342]
flocker version: 1.8.0
backend: loopback
config root_path: /var/lib/docker/zfs_flocker/flocker
On node1, loop device:
/dev/loop0 ~ /dev/loop7
I create more than 8 dataset and delete all dataset. But I create dataset, the dataset status is always pending or detached, not attached. So the new created dataset can't use for docker.

losetup -a:
/dev/loop0: [0811]:8323074 (/var/lib/docker/zfs_flocker/flocker/attached/dd4cbca8-45b8-4ffe-8fa9-e46f12daaabd/block-e3eb29ec-6228-4dbf-805a-d908bf7649c7_1073741824 (deleted))
/dev/loop1: [0811]:8323078 (/var/lib/docker/zfs_flocker/flocker/attached/dd4cbca8-45b8-4ffe-8fa9-e46f12daaabd/block-2e520088-c9f3-49b4-8aaa-b049691541a7_3221225472 (deleted))
/dev/loop2: [0811]:8323080 (/var/lib/docker/zfs_flocker/flocker/attached/dd4cbca8-45b8-4ffe-8fa9-e46f12daaabd/block-e6496921-2e64-4bd5-9f1c-21ada1f18e08_5368709120 (deleted))
/dev/loop3: [0811]:8323081 (/var/lib/docker/zfs_flocker/flocker/attached/dd4cbca8-45b8-4ffe-8fa9-e46f12daaabd/block-933a4a6f-3ddf-4252-b878-d93652ba5cf0_2147483648 (deleted))
/dev/loop4: [0811]:8323082 (/var/lib/docker/zfs_flocker/flocker/attached/dd4cbca8-45b8-4ffe-8fa9-e46f12daaabd/block-e1bc2f9e-e114-4f53-bebb-28a309c8252c_2147483648 (deleted))
/dev/loop5: [0811]:8323083 (/var/lib/docker/zfs_flocker/flocker/attached/dd4cbca8-45b8-4ffe-8fa9-e46f12daaabd/block-e04451d3-9ca3-41aa-becf-70344f474ebb_3221225472 (deleted))
/dev/loop6: [0811]:8323084 (/var/lib/docker/zfs_flocker/flocker/attached/dd4cbca8-45b8-4ffe-8fa9-e46f12daaabd/block-08da20c4-c67a-4cf2-a92f-4b24e779d5f1_3221225472 (deleted))
/dev/loop6: [0811]:8323084 (/var/lib/docker/zfs_flocker/flocker/attached/dd4cbca8-45b8-4ffe-8fa9-e46f12daaabd/block-08da20c4-c67a-4cf2-a92f-4b24e779d5f1_3221225472 (deleted))
/dev/loop7: [0811]:8323085 (/var/lib/docker/zfs_flocker/flocker/attached/dd4cbca8-45b8-4ffe-8fa9-e46f12daaabd/block-80e0b195-c75f-48ea-8dfa-7fbb28ff72cd_1073741824 (deleted))

find unused loop device:
losetup -f
losetuplosetup: command not found

So I think flocker is not detach realy loop device. 
I run command:  losetup -d /dev/loop7
Realy detach /dev/loop7.
run command: losetup -f
/dev/loop7

So delete dataset, but don't detach loop device.

**Comment by wallnerryan** [comment]
@ttllyy the loopback is not meant to be used at scale and really is only meant for trying out flocker. To clarify, let me know if I have your question correct. Are saying that your running into a hard limit with the amount of loopback devices because they do not seem to be removed when a dataset it deleted?
