### ISSUE TITLE
Debian Jessie Support

### ISSUE THREAD

**Issue by lattwood** [ClusterHQ/flocker#2355]

**Comment by wallnerryan** [comment]
Thanks for the feedback @lattwood

**Comment by DanielDent** [comment]
+1 :)

**Comment by BastienM** [comment]
+1, any update on this ?

**Comment by fabMrc** [comment]
:+1:

**Comment by gonzalomarcote** [comment]
This definitely would be great. Ubuntu packages are not installable in Debian Jessie

**Comment by battuashwik** [comment]
Any update on this. Kubernetes has removed support for ubuntu trusty and debian jessie is not supported by flocker. The only option is to move to centos or rhel.

**Comment by wallnerryan** [comment]
No updates yet guys, sorry.

**Comment by backnight** [comment]
The Debian Jessie support would be very appreciated ;)

**Comment by antakar** [comment]
Do you have any eta for debian jessie support?
