### ISSUE TITLE
Connection was refused by other side: 111

### ISSUE THREAD

**Issue by xingyixun** [ClusterHQ/flocker#2356]
I followed the tutorial to install the docker plugin,
https://docs.clusterhq.com/en/1.8.0/install/install-node.html#installing-flocker-node
and then I create the agent.yml in /etc/flocker.and my angent.yml is like this
"version": 1
"control-service":
   "hostname": "10.1.241.130"
   "port": 4524
"dataset":
   "backend": "loopback"
   "root_path": "/var/lib/flocker/loopback"

then I enable flocker-plugin and start it ,but I got message like this 

{"task_uuid": "8f1f075f-a1ea-4e5d-8d89-f7a37027b3a9", "error": false, "timestamp": 1450321779.403943, "message": "Log opened.", "message_type": "twisted:log", "task_level": [1]}
{"request_body": null, "url": "https://10.1.241.130:4523/v1/state/nodes/by_era/fcf96c84-3a2d-4ab7-a0a6-21eb8f1063ba", "timestamp": 1450321780.32824, "action_status": "started", "task_uuid": "2c1f1349-8a5b-4d21-b413-097983b1d59e", "action_type": "flocker:apiclient:http_request", "method": "GET", "task_level": [1]}
{"task_uuid": "2c1f1349-8a5b-4d21-b413-097983b1d59e", "error": false, "timestamp": 1450321780.371869, "message": "Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x3b6d878>", "message_type": "twisted:log", "task_level": [3]}
{"exception": "twisted.internet.error.ConnectionRefusedError", "task_level": [4], "action_type": "flocker:apiclient:http_request", "reason": "Connection was refused by other side: 111: Connection refused.", "timestamp": 1450321780.37318, "task_uuid": "2c1f1349-8a5b-4d21-b413-097983b1d59e", "action_status": "failed"}
{"task_uuid": "53518178-00d1-4eb7-8490-5d5f987596d1", "error": true, "timestamp": 1450321780.373919, "message": "Unhandled Error\nTraceback (most recent call last):\nFailure: twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.\n", "message_type": "twisted:log", "task_level": [1]}
{"task_uuid": "658c0f2b-3e8f-4308-b9db-960952669fbb", "error": true, "timestamp": 1450321780.374476, "message": "main function encountered error\nTraceback (most recent call last):\nFailure: twisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.\n", "message_type": "twisted:log", "task_level": [1]}
{"task_uuid": "60ec1217-7e34-486c-8e1e-88a94241e3ce", "error": false, "timestamp": 1450321780.375019, "message": "Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x3b6d878>", "message_type": "twisted:log", "task_level": [1]}
{"task_uuid": "a3aeedfd-a083-4937-b700-a31d4c3e6c6b", "error": false, "timestamp": 1450321780.375878, "message": "Main loop terminated.", "message_type": "twisted:log", "task_level": [1]}

and I found that the error:true Connection was refused by other side: 111.
my environment is centos ,and I installed flocker by yum

**Comment by wallnerryan** [comment]
@xingyixun did you make sure you have ports `4523` and `4524` open in your firewall? See here https://docs.clusterhq.com/en/1.8.0/config/enabling-control-service.html?highlight=firewall#enabling-the-flocker-control-service

**Comment by xingyixun** [comment]
@wallnerryan I just close the firewall

**Comment by wallnerryan** [comment]
Can you verify that the control service is successfully running?

On your control service node you can run `systemctl status -l flocker-control` and look for any errors, if their are some, post here.

**Comment by xingyixun** [comment]
flocker-control.service - Flocker Control Service
   Loaded: loaded (/usr/lib/systemd/system/flocker-control.service; disabled)
   Active: inactive (dead)

Dec 21 14:34:30 mesos-slave6 systemd[1]: [/usr/lib/systemd/system/flocker-control.service:11] Unknown lvalue 'PrivateDev' in section 'Service'
Dec 21 14:34:30 mesos-slave6 systemd[1]: [/usr/lib/systemd/system/flocker-control.service:13] Unknown lvalue 'ProtectSystem' in section 'Service'
Dec 21 14:34:30 mesos-slave6 systemd[1]: [/usr/lib/systemd/system/flocker-control.service:14] Unknown lvalue 'ProtectHome' in section 'Service'
Dec 21 14:34:30 mesos-slave6 systemd[1]: [/usr/lib/systemd/system/flocker-control.service:15] Unknown lvalue 'ReadonlyDirectories' in section 'Service'

I just got this .I followed the docker flocker plugin tutorial.

**Comment by wallnerryan** [comment]
Looks like the control service is disabled. Try.

```
systemctl enable flocker-control
systemctl start flocker-control
```
Please output the status once you do this.

There is also some odd errors `Unknown ...`, could you copy-paste the `/usr/lib/systemd/system/flocker-control.service` file here?

Also, per "I followed the docker flocker plugin tutorial." which totorial is this? [This](https://docs.clusterhq.com/en/1.8.0/introduction/flocker-plugin.html#get-started-with-the-flocker-plugin-for-docker) is a good place to start.

**Comment by xingyixun** [comment]
when I try start flocker-control ,I happened this error 
```
Dec 22 09:34:35 mesos-slave6 systemd[1]: Starting Flocker Docker Plugin...
Dec 22 09:34:35 mesos-slave6 systemd[1]: Started Flocker Docker Plugin.
Dec 22 09:34:36 mesos-slave6 flocker-docker-plugin[8301]: {"task_uuid": "4889aa29-cfae-4fef-8b82-55b0c19cf9e9", "error": false, "timestamp": 1450748076.5904...l": [1]}
Dec 22 09:34:37 mesos-slave6 flocker-docker-plugin[8301]: {"request_body": null, "url": "https://10.1.241.130:4523/v1/state/nodes/by_era/fcf96c84-3a2d-4ab7-a0a6-21e...
Dec 22 09:34:37 mesos-slave6 flocker-docker-plugin[8301]: {"task_uuid": "aecc7073-d174-4100-b047-462f8094c4a1", "error": false, "timestamp": 1450748077.5856...l": [3]}
Dec 22 09:34:37 mesos-slave6 flocker-docker-plugin[8301]: {"exception": "twisted.internet.error.ConnectionRefusedError", "task_level": [4], "action_type": "flocker:...
Dec 22 09:34:37 mesos-slave6 flocker-docker-plugin[8301]: {"task_uuid": "1651037f-1545-47b4-818d-f0a58b68bd39", "error": true, "timestamp": 1450748077.587722, "mess...
Dec 22 09:34:37 mesos-slave6 flocker-docker-plugin[8301]: {"task_uuid": "e7f4598d-d529-4fa2-88fb-df7a90a3d771", "error": true, "timestamp": 1450748077.588395, "mess...
Dec 22 09:34:37 mesos-slave6 flocker-docker-plugin[8301]: {"task_uuid": "0cc19db1-c1d1-4e97-a598-3ca0209d8a97", "error": false, "timestamp": 1450748077.5892...l": [1]}
Dec 22 09:34:37 mesos-slave6 flocker-docker-plugin[8301]: {"task_uuid": "780ca2f0-05af-4930-ba1b-06f74717506f", "error": false, "timestamp": 1450748077.5900...l": [1]}
Dec 22 09:34:37 mesos-slave6 systemd[1]: flocker-docker-plugin.service: main process exited, code=exited, status=1/FAILURE
Dec 22 09:34:37 mesos-slave6 systemd[1]: Unit flocker-docker-plugin.service entered failed state.
Dec 22 09:34:37 mesos-slave6 systemd[1]: flocker-docker-plugin.service holdoff time over, scheduling restart.
Dec 22 09:34:37 mesos-slave6 systemd[1]: Stopping Flocker Docker Plugin...
Dec 22 09:34:37 mesos-slave6 systemd[1]: Starting Flocker Docker Plugin...
```
This my /usr/lib/systemd/system/flocker-control.service file
```
[Unit]
Description=Flocker Control Service

[Service]
ExecStart=/usr/sbin/flocker-control -p systemd:INET:0 -a systemd:INET:1 --journald
Sockets=flocker-control-api.socket flocker-control-agent.socket
NonBlocking=true
Restart=always

PrivateTmp=true
PrivateDev=true
PrivateNetwork=true
ProtectSystem=true
ProtectHome=true
ReadonlyDirectories=/
ReadWriteDirectories=/var/lib/flocker

[Install]
WantedBy=multi-user.target

```
and I just followed the same tutorial you mentioned.and thank you.

**Comment by wallnerryan** [comment]
Your logs seem truncated. Can you add `-a` to journalctl like `journalctl -a -u flocker-docker-plugin` and put them here. 

Also `flocker-docker-plugin[8301]: {"exception": "twisted.internet.error.ConnectionRefusedError", "task_level": [4], "action_type": "flocker:...` is specific to the `flocker-docker-plugin` service not `flocker-control` and it likely because it cannot reach the control service because it is not starting. 

Could you send the output of  `journalctl -a -u flocker-control`

**Comment by xingyixun** [comment]
I got the error message like this 
```
Dec 23 11:12:12 mesos-slave6 systemd[1]: Starting Flocker Control Service...
Dec 23 11:12:12 mesos-slave6 systemd[1]: Started Flocker Control Service.
Dec 23 11:12:14 mesos-slave6 flocker-control[1323]: {"task_uuid": "3544ec5a-cb55-47ec-85d9-05ab5d6a1e00", "error": false, "timestamp": 1450840334.288948, "message": "Log opened.", "message_type": "twisted:log", "task_level": [1]}
Dec 23 11:12:14 mesos-slave6 flocker-control[1323]: {"task_uuid": "d2b42824-7543-4197-84d5-6abac637daf8", "error": true, "timestamp": 1450840334.312346, "message": "Unhandled Error\nTraceback (most recent call last):\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/control/script.py\", line 118, in flocker_control_main\n    options=ControlOptions()\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 257, in main\n    self._react(run_and_log, [], _reactor=self._reactor)\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/task.py\", line 875, in react\n    finished = main(_reactor, *argv)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 248, in run_and_log\n    d = maybeDeferred(self.script.main, reactor, options)\n--- <exception caught here> ---\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py\", line 140, in maybeDeferred\n    result = f(*args, **kw)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/control/script.py\", line 62, in main\n    certificates_path, b\"service\")\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/ca/_ca.py\", line 561, in from_path\n    b\"control-{}.crt\".format(hostname)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/ca/_ca.py\", line 276, in load_certificate_from_path\n    certificate = load_certificate_file(cert_path)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/ca/_ca.py\", line 232, in load_certificate_file\n    e.filename, code, failure\nflocker.ca._ca.PathError: Certificate file could not be opened. No such file or directory /etc/flocker/control-service.crt\n", "message_type": "twisted:log", "task_level": [1]}
Dec 23 11:12:14 mesos-slave6 flocker-control[1323]: {"task_uuid": "efc6a981-1d9f-4b7e-87a4-cefe70708c36", "error": true, "timestamp": 1450840334.31359, "message": "main function encountered error\nTraceback (most recent call last):\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/control/script.py\", line 118, in flocker_control_main\n    options=ControlOptions()\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 257, in main\n    self._react(run_and_log, [], _reactor=self._reactor)\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/task.py\", line 875, in react\n    finished = main(_reactor, *argv)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 248, in run_and_log\n    d = maybeDeferred(self.script.main, reactor, options)\n--- <exception caught here> ---\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py\", line 140, in maybeDeferred\n    result = f(*args, **kw)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/control/script.py\", line 62, in main\n    certificates_path, b\"service\")\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/ca/_ca.py\", line 561, in from_path\n    b\"control-{}.crt\".format(hostname)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/ca/_ca.py\", line 276, in load_certificate_from_path\n    certificate = load_certificate_file(cert_path)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/ca/_ca.py\", line 232, in load_certificate_file\n    e.filename, code, failure\nflocker.ca._ca.PathError: Certificate file could not be opened. No such file or directory /etc/flocker/control-service.crt\n", "message_type": "twisted:log", "task_level": [1]}
Dec 23 11:12:14 mesos-slave6 flocker-control[1323]: {"task_uuid": "9746f8c4-5532-4c8e-90b4-68fb25a92926", "error": false, "timestamp": 1450840334.314324, "message": "Main loop terminated.", "message_type": "twisted:log", "task_level": [1]}
Dec 23 11:12:14 mesos-slave6 systemd[1]: flocker-control.service: main process exited, code=exited, status=1/FAILURE
Dec 23 11:12:14 mesos-slave6 systemd[1]: Unit flocker-control.service entered failed state.
Dec 23 11:12:14 mesos-slave6 systemd[1]: flocker-control.service holdoff time over, scheduling restart.
```

**Comment by xingyixun** [comment]
merry christmas

**Comment by wallnerryan** [comment]
` file could not be opened. No such file or directory /etc/flocker/control-service.crt\n", "message_type": "twisted:log", "task_level": [1]}` suggests you do not have the certificates setup prior to starting the control service. See https://docs.clusterhq.com/en/1.8.0/config/configuring-authentication.html#steps for more information on creating the files you need.
