### ISSUE TITLE
User stories for roadmap

### ISSUE THREAD

**Issue by lukemarsden** [ClusterHQ/flocker#236]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-236

Include some descriptive user stories for future roadmap work.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-236. You are welcome to file additional issues in GitHub if that's easier for you.
