### ISSUE TITLE
Flocker uses Cinder backend

### ISSUE THREAD

**Issue by drngsl** [ClusterHQ/flocker#2372]
agent.yml conf
"version": 1
"control-service":
    "hostname": "103.30.0.50"
    "port": 4524

dataset:
    backend: openstack
    verify_peer: false
    auth_plugin: password
    auth_url: http://103.30.0.50:5000/v2.0
    region: RegionOne
    tenant_name: admin
    username: admin
    password: ******

After scanning the source code, specially flocker.node.agents.cinder.py(class CinderBlockDeviceAPI). I really confuse how flocker interacts with cinder.
In the cinder.py, there are three method like compute_instance_id, attach_volume and detach_volume. 
Here, def compute_instance_id(self):  I see that flocker interacts with nova to get instance info from nova. And it requires the length of matching_instances must equal to 1. so why need flocker to interact to nova? why should the len of matching_instances be only 1?
And then about attach_volume and detach_volume, they both complete by invoking the method of nova. It means that the containers/VM here are created by nova, other than docker api or flocker_deploy cmd?

thanks!

**Comment by drngsl** [comment]
Here, I print some log.
root@ubuntu50:/var/log/flocker# nova list
+--------------------------------------+------+--------+------------+-------------+-------------------+
| ID                                   | Name | Status | Task State | Power State | Networks          |
+--------------------------------------+------+--------+------------+-------------+-------------------+
| a9666940-18e1-4743-a915-bb0ad7cd6dab | doc2 | ACTIVE | -          | Running     | private=10.0.0.11 |
+--------------------------------------+------+--------+------------+-------------+-------------------+

some fields in method of compute_instance_id
api_addresses set([IPv4Address('10.0.0.11')])
matching_instances []
api_ip_map {IPv4Address('10.0.0.11'): u'a9666940-18e1-4743-a915-bb0ad7cd6dab'}

{"exception": "flocker.node.agents.blockdevice.UnknownInstanceID", "reason": "Could not find valid instance ID for <flocker.node.agents.cinder.CinderBlockDeviceAPI object at 0x7f45f158a490>", "timestamp": 1450682622.733713, "traceback": "Traceback: <class 'flocker.node.agents.blockdevice.UnknownInstanceID'>: Could not find valid instance ID for <flocker.node.agents.cinder.CinderBlockDeviceAPI object at 0x7f45f158a490>\n/opt/flocker/local/lib/python2.7/site-packages/machinist/_logging.py:102:receive\n/opt/flocker/local/lib/python2.7/site-packages/machinist/_fsm.py:534:receive\n/opt/flocker/local/lib/python2.7/site-packages/machinist/_fsm.py:592:output\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/_loop.py:464:output_CONVERGE\n--- <exception caught here> ---\n/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py:140:maybeDeferred\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:1400:discover_state\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:1355:_discover_raw_state\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:1782:compute_instance_id\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/cinder.py:470:compute_instance_id\n", "message_type": "eliot:traceback", "task_uuid": "fadac606-3b61-4ec3-b247-b7afc7937f50", "task_level": [2, 4]}

**Comment by drngsl** [comment]
Here, I print some log.
root@ubuntu50:/var/log/flocker# nova list
+--------------------------------------+------+--------+------------+-------------+-------------------+
| ID                                   | Name | Status | Task State | Power State | Networks          |
+--------------------------------------+------+--------+------------+-------------+-------------------+
| a9666940-18e1-4743-a915-bb0ad7cd6dab | doc2 | ACTIVE | -          | Running     | private=10.0.0.11 |
+--------------------------------------+------+--------+------------+-------------+-------------------+

some fields in method of compute_instance_id
api_addresses set([IPv4Address('10.0.0.11')])
matching_instances []
api_ip_map {IPv4Address('10.0.0.11'): u'a9666940-18e1-4743-a915-bb0ad7cd6dab'}

{"exception": "flocker.node.agents.blockdevice.UnknownInstanceID", "reason": "Could not find valid instance ID for <flocker.node.agents.cinder.CinderBlockDeviceAPI object at 0x7f45f158a490>", "timestamp": 1450682622.733713, "traceback": "Traceback: <class 'flocker.node.agents.blockdevice.UnknownInstanceID'>: Could not find valid instance ID for <flocker.node.agents.cinder.CinderBlockDeviceAPI object at 0x7f45f158a490>\n/opt/flocker/local/lib/python2.7/site-packages/machinist/_logging.py:102:receive\n/opt/flocker/local/lib/python2.7/site-packages/machinist/_fsm.py:534:receive\n/opt/flocker/local/lib/python2.7/site-packages/machinist/_fsm.py:592:output\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/_loop.py:464:output_CONVERGE\n--- <exception caught here> ---\n/opt/flocker/local/lib/python2.7/site-packages/twisted/internet/defer.py:140:maybeDeferred\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:1400:discover_state\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:1355:_discover_raw_state\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/blockdevice.py:1782:compute_instance_id\n/opt/flocker/local/lib/python2.7/site-packages/flocker/node/agents/cinder.py:470:compute_instance_id\n", "message_type": "eliot:traceback", "task_uuid": "fadac606-3b61-4ec3-b247-b7afc7937f50", "task_level": [2, 4]}

**Comment by itamarst** [comment]
Is this machine running Flocker an OpenStack Nova instance?

**Comment by drngsl** [comment]
@itamarst. Sorry, I'am confused. you means that Flocker is deployed in Openstack Nova instance(VM)? If so, How does flocker interact with Openstack Nova and Cinder?

In this machine, I deploy Docker, Flocker and Openstack.
I want to know if I configure Flocker with Cinder backend, when use flocker-deploy or docker run --volume-driver flocker to create run, why does Flocker need to interact with Nova?

**Comment by wallnerryan** [comment]
"I want to know if I configure Flocker with Cinder backend, when using flocker-deploy or docker run --volume-driver command"

 - yes you can use openstack cinder backend in either case.

"why does Flocker need to interact with Nova?"

 - flocker runs as a cluster and manages storage devices that get attached to (in the openstack case) nova instances where containers run. Therefore the cinder backend needs to query the nova API about instance details.

**Comment by drngsl** [comment]
@wallnerryan，you means that the Openstack and Flocker specially Flocker control service are deployed on the physical machine . And then Openstack creates some virtual machine. in each of these VM, deploys Docker and Flocker agent.
In the VM, I can run an container by Docker, if I want to attach a volume created by Cinder to container, 
First, I need to create a volume and attach it to VM. 
Then, in the VM, I use this volume and attach it to Container through the "device_path" of volume.

**Comment by drngsl** [comment]
@wallnerryan，you means that the Openstack and Flocker specially Flocker control service are deployed on the physical machine . And then Openstack creates some virtual machine. in each of these VM, deploys Docker and Flocker agent.
In the VM, I can run an container by Docker, if I want to attach a volume created by Cinder to container, 
First, I need to create a volume and attach it to VM. 
Then, in the VM, I use this volume and attach it to Container through the "device_path" of volume.

**Comment by drngsl** [comment]
@wallnerryan，you means that the Openstack and Flocker specially Flocker control service are deployed on the physical machine . And then Openstack creates some virtual machine. in each of these VM, deploys Docker and Flocker agent.
In the VM, I can run an container by Docker, if I want to attach a volume created by Cinder to container, 
First, I need to create a volume and attach it to VM. 
Then, in the VM, I use this volume and attach it to Container through the "device_path" of volume.

**Comment by drngsl** [comment]
@wallnerryan，you means that the Openstack and Flocker specially Flocker control service are deployed on the physical machine . And then Openstack creates some virtual machine. in each of these VM, deploys Docker and Flocker agent.
In the VM, I can run an container by Docker, if I want to attach a volume created by Cinder to container, 
First, I need to create a volume and attach it to VM. 
Then, in the VM, I use this volume and attach it to Container through the "device_path" of volume.

**Comment by drngsl** [comment]
@wallnerryan，you means that the Openstack and Flocker specially Flocker control service are deployed on the physical machine . And then Openstack creates some virtual machine. in each of these VM, deploys Docker and Flocker agent.
In the VM, I can run an container by Docker, if I want to attach a volume created by Cinder to container, 
First, I need to create a volume and attach it to VM. 
Then, in the VM, I use this volume and attach it to Container through the "device_path" of volume.

**Comment by drngsl** [comment]
@wallnerryan，you means that the Openstack and Flocker specially Flocker control service are deployed on the physical machine . And then Openstack creates some virtual machine. in each of these VM, deploys Docker and Flocker agent.
In the VM, I can run an container by Docker, if I want to attach a volume created by Cinder to container, 
First, I need to create a volume and attach it to VM. 
Then, in the VM, I use this volume and attach it to Container through the "device_path" of volume.

**Comment by drngsl** [comment]
@wallnerryan，you means that the Openstack and Flocker specially Flocker control service are deployed on the physical machine . And then Openstack creates some virtual machine. in each of these VM, deploys Docker and Flocker agent.
In the VM, I can run an container by Docker, if I want to attach a volume created by Cinder to container, 
First, I need to create a volume and attach it to VM. 
Then, in the VM, I use this volume and attach it to Container through the "device_path" of volume.

**Comment by drngsl** [comment]
@wallnerryan，you means that the Openstack and Flocker specially Flocker control service are deployed on the physical machine . And then Openstack creates some virtual machine. in each of these VM, deploys Docker and Flocker agent.
In the VM, I can run an container by Docker, if I want to attach a volume created by Cinder to container, 
First, I need to create a volume and attach it to VM. 
Then, in the VM, I use this volume and attach it to Container through the "device_path" of volume.

**Comment by drngsl** [comment]
@wallnerryan，you means that the Openstack and Flocker specially Flocker control service are deployed on the physical machine . And then Openstack creates some virtual machine. in each of these VM, deploys Docker and Flocker agent.
In the VM, I can run an container by Docker, if I want to attach a volume created by Cinder to container, 
First, I need to create a volume and attach it to VM. 
Then, in the VM, I use this volume and attach it to Container through the "device_path" of volume.

**Comment by wallnerryan** [comment]
@drngsl 

What i mean is that Flocker Control Service can run outside or inside a VM. The Flocker Agents must run inside openstack virtual machines. 

When you want to create a docker container that wants a volume simply `docker run --volume-driver=flocker busybox sh" and **Flocker will automatically provision cinder volumes, attach them to the virtual machine and hand them to the container**. There is no need to manually create and attach volumes yourself.

Hope this helps.

**Comment by drngsl** [comment]
@wallnerryan 
Yes, it help a lot.
Tanks very much!
