### ISSUE TITLE
Debian installation repo has no packages for Ubuntu 15.10

### ISSUE THREAD

**Issue by sgnn7** [ClusterHQ/flocker#2373]
Only packages for Ubuntu 15.04 are available on https://clusterhq-archive.s3.amazonaws.com/ubuntu/ and 15.10 is already out so the instructions on https://docs.clusterhq.com/en/1.0.1/using/installing/index.html are not valid for that version

PS: It also would be nice if these could be browsable since I spent a good hour trying to figure out what endpoint to use.

**Comment by wallnerryan** [comment]
thanks @sgnn7, make sure your looking at up-to-date docs as well. Current versio is [1.8.0](https://docs.clusterhq.com/en/1.8.0/install/index.html). Our docs state only 15.04 and 14.04 are available there. 

Will look into and see if we can make this browsable.

**Comment by sgnn7** [comment]
@wallnerryan Cool, ty!

**Comment by wallnerryan** [comment]
The client now supports 15.10 in our most recent version 1.9. They are still not browsable though. https://docs.clusterhq.com/en/1.9.0/install/install-client.html#installing-on-ubuntu-15-10-64-bit

**Comment by sgnn7** [comment]
@wallnerryan Thanks! Upgrade to 1.9 worked great and it fixed systemd problems from 1.8. 

Btw, Ubuntu 15.04 is also systemd and 1.8 does not work well on that combo but your 15.04 repo has the 1.8 packages still (as of yesterday) that might need bumping up.

**Comment by wallnerryan** [comment]
Great and thanks!

**Comment by sgnn7** [comment]
Closing the issue since this got fixed at some point
