### ISSUE TITLE
Error response from daemon: Error looking up volume plugin flocker: Plugin not found

### ISSUE THREAD

**Issue by jonathan-kosgei** [ClusterHQ/flocker#2391]
I have 2 centos 7.1 nodes and I'm trying to get flocker running on it. I've followed the installation steps exactly however when it comes to running the following command to test to see if flocker-docker-plugin works:

`docker run -v apples:/data --volume-driver flocker busybox sh -c "echo hello > /data/file.txt"`

I get the error:

`Error response from daemon: Error looking up volume plugin flocker: Plugin not found`

The flocker-docker-plugin logs show the following:

```{"request_body": null, "url": "https://foo.bar.com:4523/v1/state/nodes/by_era/b72bb203-b174-4241-a03a-6171cbc10f30", "timestamp": 1451201332.659948, "action_status": "started", "task_uuid": "1ae63069-286c-44fa-9dd2-6751ca0efe63", "action_type": "flocker:apiclient:http_request", "method": "GET", "task_level": [1]}
{"task_uuid": "1ae63069-286c-44fa-9dd2-6751ca0efe63", "error": false, "timestamp": 1451201332.749499, "message": "Starting factory <twisted.web.client._HTTP11ClientFactory instance at 0x2fc7710>", "message_type": "twisted:log", "task_level": [3]}
{"exception": "twisted.web._newclient.ResponseNeverReceived", "task_level": [4], "action_type": "flocker:apiclient:http_request", "reason": "[<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]", "timestamp": 1451201333.050012, "task_uuid": "1ae63069-286c-44fa-9dd2-6751ca0efe63", "action_status": "failed"}
{"task_uuid": "c8d28668-f21b-4863-bf20-6c30f54c3d25", "error": true, "timestamp": 1451201333.05045, "message": "Unhandled Error\nTraceback (most recent call last):\nFailure: twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]\n", "message_type": "twisted:log", "task_level": [1]}
{"task_uuid": "36f1ddd5-c5fa-4438-85d7-131e7752f8d3", "error": true, "timestamp": 1451201333.050727, "message": "main function encountered error\nTraceback (most recent call last):\nFailure: twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]\n", "message_type": "twisted:log", "task_level": [1]}
{"task_uuid": "08bd8f13-0a8e-43f4-8b80-b4cf5b317f00", "error": false, "timestamp": 1451201333.051034, "message": "Stopping factory <twisted.web.client._HTTP11ClientFactory instance at 0x2fc7710>", "message_type": "twisted:log", "task_level": [1]}
{"task_uuid": "8f0fd1ef-19ca-4033-b16f-6d42e33eda1a", "error": false, "timestamp": 1451201333.052711, "message": "Main loop terminated.", "message_type": "twisted:log", "task_level": [1]}
flocker-docker-plugin.service: main process exited, code=exited, status=1/FAILURE
Unit flocker-docker-plugin.service entered failed state.
flocker-docker-plugin.service failed.
flocker-docker-plugin.service holdoff time over, scheduling restart.
Started Flocker Docker Plugin.
Starting Flocker Docker Plugin...
[truncated, repeat of the above, after each restart]
```
Also running `uft-flocker-volumes --control-service=foo.bar.net list-nodes` returns: 

```jonathan@ubuntu:~/Flocker/sc-test-cluster$ uft-flocker-volumes --control-service=foo.bar.com list-nodes
Unhandled Error
Traceback (most recent call last):
Failure: twisted.web._newclient.ResponseNeverReceived
[<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]```

Update:
I tried downgrading to docker 1.8.2 and tried rerunning the command, didn't work, same error.

**Comment by wallnerryan** [comment]
@jonathan-kosgei i believe we responded to this issue on another support channel. Let me know if you got our responses and we can chase down the fix there, when we do we can update this issue and close it so others on github can find it.

**Comment by jonathan-kosgei** [comment]
Right, working on it.

**Comment by sayasree** [comment]
Even, I am getting the same error when I run the command:

$ docker run -v apples:/data --volume-driver flocker busybox sh -c "echo hello > /data/file.txt"

It displayed the error:

Error response from daemon: Error looking up volume plugin flocker: Plugin not found

**Comment by wallnerryan** [comment]
@sayasree did you get your issue resolved? Please send your logs from this node using flocker-diagnostics` to support@clusterhq.com with a description of your issues. Thanks

**Comment by bal-mukund-chauhan** [comment]
I get the same error while creating docker containers. Below is my environment setup details.
I have also mailed to support@clusterhq.com along with the flocker-doagnostics logs.

Please help.


***Environment Setup:***
I have followed steps for creating flocker-cli, flocker-control and flocker-nodes from https://docs.clusterhq.com/en/latest/flocker-standalone/manual-install.html on Ubuntu 14.04 OS. I have created three vm's for flocker client, control and node respectively. I have used loop back dataset as mentioned in https://docs.clusterhq.com/en/latest/flocker-features/loopback-configuration.html#loopback-dataset-backend.

**Comment by wallnerryan** [comment]
@bal-mukund-chauhan, responded to your issue on the support ticket. Also closing this one as its mostly on older/known issue.
