### ISSUE TITLE
Launch an instance with flocker-deploy failed

### ISSUE THREAD

**Issue by drngsl** [ClusterHQ/flocker#2392]
yaml config
centos-dep.yml:
"version": 1
"nodes":
  "192.168.50.5": ["centos-example"]

centos-app.yml:
"version": 1
"applications":
  "centos-example":
    "image": "centos:latest"

When i launch an instance with cmd flocker-deploy --cacert /etc/flocker/cluster.crt --cert /etc/flocker/user.crt --key /etc/flocker/user.key 103.30.0.50 $DEPLOYER_PATH/centos-dep.yml $DEPLOYER_PATH/centos-app.yml,docker deamon prints following logs Cyclically.
INFO[67204] POST /v1.15/containers/create?name=flocker--centos-example 
INFO[67204] POST /v1.15/containers/flocker--centos-example/start 
INFO[67205] GET /v1.15/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[67205] GET /v1.15/containers/33f97002ebd47a51f531d90fdf84366b5392013f066d686820fd0887ea591a6c/json 
INFO[67205] POST /v1.15/containers/flocker--centos-example/stop?t=10 
ERRO[67205] Handler for POST /v1.15/containers/flocker--centos-example/stop returned error: Container already stopped 
ERRO[67205] HTTP Error                                    err=Container already stopped statusCode=304
INFO[67205] POST /v1.15/containers/flocker--centos-example/wait 
INFO[67205] DELETE /v1.15/containers/flocker--centos-example?link=False&force=False&v=False 
INFO[67205] POST /v1.15/containers/create?name=flocker--centos-example 
INFO[67205] POST /v1.15/containers/flocker--centos-example/start 
INFO[67205] GET /v1.15/containers/json?all=1&limit=-1&trunc_cmd=0&size=0 
INFO[67205] GET /v1.15/containers/329090df497e35308f42eb3a0bb4812d32473d9b6f4dbf69bad0f9d064bb7d20/json 
INFO[67205] POST /v1.15/containers/flocker--centos-example/stop?t=10 
ERRO[67205] Handler for POST /v1.15/containers/flocker--centos-example/stop returned error: Container already stopped 
ERRO[67205] HTTP Error                                    err=Container already stopped statusCode=304

Other configurations
Flocker version:
1.8.0

Docker version:
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

**Comment by wallnerryan** [comment]
Hi @drngsl this looks like the container is being started then stopped and the container agent is trying to make sure the container is started. Can you verify that you an run the centos:latest image without any issue just using `docker run`. If you can, then please run `flocker-diagnostics` and send your logs to support@clusterhq.com and i'll have a look at them.
