### ISSUE TITLE
Check for duplicate applications in the deployment configuration

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#240]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-240

The deployment configuration maps Flocker cluster nodes to lists of applications meant to run on those nodes.  An application may not currently appear in more than one of these lists (this feature may make sense in a future version of Flocker, but not now).

From the initial config loading branch:

```
     def test_error_on_duplicate_applications(self):
        """                                                                                                                                            
        ``_deployment_from_config`` raises a ``ValueError`` if the                                                                                     
        deployment_configuration contains duplicate applications.                                                                                      
        """
        self.fail("Not implemented")
    test_error_on_duplicate_applications.todo = (
        "Planned validation improvements")
```

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-240. You are welcome to file additional issues in GitHub if that's easier for you.
