### ISSUE TITLE
Check for validity of hostnames/addresses in deployment configuration

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#241]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-241

The deployment configuration has node identifiers, either hostnames or IP addresses, as keys.  It is an error for these to be malformed (eg `256.256.256.256`).

From the initial config loading branch:

```
    def test_error_on_invalid_node_hostname(self):
        """                                                                                                                                            
        ``_deployment_from_config`` raises an ``ValueError`` if the                                                                                    
        deployment_configuration contains invalid DNS hostnames.                                                                                       
        """
        self.fail("Not implemented")
    test_error_on_invalid_node_hostname.todo = (
        "Planned validation improvements")
```

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-241. You are welcome to file additional issues in GitHub if that's easier for you.
