### ISSUE TITLE
Follow install guide failed to run service

### ISSUE THREAD

**Issue by HackToday** [ClusterHQ/flocker#2422]
I have followed this guide:
https://docs.clusterhq.com/en/1.8.0/install/index.html

Frankly speaking that guide is not easy to understood..

I have used Ubuntu 14.04 version 
I have 2 nodes, let call them Node A and Node B

node A installed flocker-client and flocker node service
node B installed flocker node service.

As node A only installed flocker-client, so for the install guide, when it have command like:

flocker-ca create-node-certificate, it runs on node A, and I copied related to other nodes through scp,

After credentials creation finished,  the guide guide me to here:
https://docs.clusterhq.com/en/1.8.0/config/generate-api-certificates.html#generate-api

and I run 
 sudo curl --cacert $PWD/cluster.crt --cert $PWD/user.crt --key $PWD/user.key  https://<node A IP>:4523/v1/configuration/containers

It said connection refused, when I used netstat check, I even not find any process running on 4523.

So it seems something error happened

**Comment by wallnerryan** [comment]
Hi @HackToday did you enable/start the services after installing them? See https://docs.clusterhq.com/en/1.8.0/config/enabling-control-service.html#ubuntu.

**Comment by wallnerryan** [comment]
ping, did you ever get this resolved @HackToday

**Comment by HackToday** [comment]
hi @wallnerryan  I did not try that, which because busy with other issue, I suggest close it first, and when I have issue again, can reopen it. Thanks

**Comment by wallnerryan** [comment]
closing for now.
