### ISSUE TITLE
Remove look-before-you-leap error handling from DeployOptions.parseArgs

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#244]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-244

This code checks whether the two configuration files exist before it reads them.  Instead it should read them and handle the errors.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-244. You are welcome to file additional issues in GitHub if that's easier for you.
