### ISSUE TITLE
Use real docker images in examples.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#245]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-245

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-245. You are welcome to file additional issues in GitHub if that's easier for you.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-245. You are welcome to file additional issues in GitHub if that's easier for you.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-245. You are welcome to file additional issues in GitHub if that's easier for you.
