### ISSUE TITLE
Support alternate docker registries

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#246]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-246

We currently assume that a docker image name might contain 0 or 1 `:`s. And if it contains a `:`, that it separates the image name from the image tag. But you can also have a `:` as part of a port specification on the registry (for example `quay.io:80/hybridcluster/buildslave-fedora`). You can also have tags as well.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-246. You are welcome to file additional issues in GitHub if that's easier for you.
