### ISSUE TITLE
Unit test the configuration examples in our documentation

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#250]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-250

In the configuration documentation we have a few snippets of example configuration.  We should automatically verify these as much as possible.

An initial step could be to try to load them with `model_from_config` and verify the resulting structure is what's expected.

To make it possible to for a test to load the configuration it probably needs to be moved to a separate file and included into the configuration document.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-250. You are welcome to file additional issues in GitHub if that's easier for you.
