### ISSUE TITLE
Describe what we've learned from HybridCluster

### ISSUE THREAD

**Issue by lukemarsden** [ClusterHQ/flocker#253]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-253

And how that might help us build Flocker and solve problems for Docker containers and volumes.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-253. You are welcome to file additional issues in GitHub if that's easier for you.
