### ISSUE TITLE
Build vagrant images in buildbot.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#258]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-258

Once we have hardware to run vagrant on, we should automate the building of vagrant base images.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-258. You are welcome to file additional issues in GitHub if that's easier for you.
