### ISSUE TITLE
FlockerHub login broken

### ISSUE THREAD

**Issue by osobh** [ClusterHQ/flocker#2580]
Tried to create an account at https://id.clusterhq.com to test out the clustering interface but cant seem to register. Checked with Chrome and microsoft edge just in case and the same issue is present. It's asking for me to authorize data moving outside EEA....but no box to click to move past the login or registration page...
![flockerhub_login](https://cloud.githubusercontent.com/assets/1156319/12753867/72986cc6-c98e-11e5-89d6-e88c81d0a29b.png)

**Comment by itamarst** [comment]
Thanks for the bug report, we're looking into it.

**Comment by itamarst** [comment]
Hi,

Can you try now?

**Comment by osobh** [comment]
It works, thank you and i'm registered and logged in!
