### ISSUE TITLE
Fix the inter-package dependencies

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#259]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-259

To be able to have a minimal CLI package that can be installed on a range of platforms, we need to ignore some of the dependencies that only apply to the server side of Flocker.

Primarily this is `nomenclature` which won't build on many Linuxs, nor anything that's not Linux.

This can be addressed partially by not declaring/bundling the `nomenclature`  (or whatever) dependency in the CLI package.  The other part of this, though, is that the CLI has to actually not depend on these things - including not importing them as an unintentional side-effect when trying to import some other code.

Ultimately we probably can and should verify this on CI for the CLI packages.  As an intermediate step, we should probably restrict what Python modules/packages the CLI is implemented using (and consequently restrict what Python modules/packages those modules/packages depend on).

As a first pass, I suggest this means all CLI code must be in either `flocker.cli` or `flocker.common`.  Specifically (but not exclusively) this means `flocker.cli` may not import code from `flocker.node`. and that `flocker.cli` and `flocker.common` may not import any modules that can't reasonably be installed on all the target CLI platforms.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-259. You are welcome to file additional issues in GitHub if that's easier for you.
