### ISSUE TITLE
Flocker Docker Plugin Errors

### ISSUE THREAD

**Issue by osobh** [ClusterHQ/flocker#2593]
3.19.0-49-generic #55~14.04.1-Ubuntu SMP Fri Jan 22 11:24:31 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I'm seeing this in my logs non-stop:

init: flocker-docker-plugin main process (17759) terminated with status 1
init: flocker-docker-plugin main process ended, respawning

**Comment by wallnerryan** [comment]
Please include your logs when reporting issues. This is not enough information for me to help you debug. You can get the logs from all services on this node running `flocker-diagnostics`. You can attach them here or send them to support@clusterhq.com with a link to this issue.

Thanks

**Comment by wallnerryan** [comment]
@osobh are you still having issues with the plugin?

**Comment by osobh** [comment]
I will have to come back to testing this all out as currently i'm leveraging my own built system for migrating the data around and then attaching it to the needed containers. You can close this and i'll reopen a new one once I resume testing and if anything pops up. Thank You!

**Comment by wallnerryan** [comment]
No problem thanks
