### ISSUE TITLE
multiple storage pools support in zfs

### ISSUE THREAD

**Issue by zhenghc** [ClusterHQ/flocker#2597]
hi,

can flocker support multiple storage pools in same node ? for example, out applications requires both ssd  and hhd. if we can have 2 storage pools in the same node, then we can request volumes from either storage pools.

**Comment by wallnerryan** [comment]
Our ZFS backend is experimental and we do not recommend using it. It has known bugs and we are not currently working on updating the zfs backend. 

If you use one of our other supported backends or integrate your own, you can use our [Storage Profiles](https://docs.clusterhq.com/en/latest/flocker-features/storage-profiles.html) support to designate how you get SSD vs HHD

**Comment by wallnerryan** [comment]
Closing as ZFS is currently deprecated.
