### ISSUE TITLE
`set` datastructure that allows looking up by a key

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#266]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-266

In a number of places we have an idiom where a `set` contains items that have a unique key, e.g. nodes with unique hostnames. It would be nice to have a `set` variant that allowed looking up by the key so we don't have to write for-loops everywhere.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-266. You are welcome to file additional issues in GitHub if that's easier for you.
