### ISSUE TITLE
Can't login with Google: too many redirects

### ISSUE THREAD

**Issue by dobegor** [ClusterHQ/flocker#2691]
I can't login with Google to try flocker on your website: https://clusterhq.com/flocker/try-flocker
I've submitted a message via contact form on your website on 28 February, but got no response since that.

The exact error I get:
"The volumehub.clusterhq.com page isn’t working
volumehub.clusterhq.com redirected you too many times.
ERR_TOO_MANY_REDIRECTS"

**Comment by mdevilliers** [comment]
Thanks for reporting the issue.

Could you please detail your setup e.g. OS, browser plus plugins e.g AdBlock?

Thanks,

Mark

**Comment by dobegor** [comment]
@mdevilliers 
```
dobegor ) lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	15.12
Codename:	Capella
dobegor ) google-chrome-stable --version
Google Chrome 49.0.2623.87 
```
AdBlock is present, but disabled.

**Comment by mdevilliers** [comment]
@dobegor 

Thanks for the details - likewise I don't believe it to be browser-related.

However, whilst I am investigating would you be able to try logging in after [clearing your browsing data](https://support.google.com/chrome/answer/95582?hl=en-GB) in Chrome? Alternatively maybe try and use 'incognito mode'? These steps should further confirm that it isn't browser related.

Thanks,

Mark

**Comment by mdevilliers** [comment]
@dobegor 

Would you be able to try creating an account again? We believe we might have fixed the issue you were encountering.

Thanks for your patience and time.

Mark

**Comment by dobegor** [comment]
@mdevilliers 
Sorry for late response.
Yes, it works for me now. 
Thanks!

George
