### ISSUE TITLE
Proper directory for supported backends?

### ISSUE THREAD

**Issue by jsilberm** [ClusterHQ/flocker#2700]
We have completed the supported backend qualification tests and are getting ready to post our flocker driver code.

Looks like the norm has been for storage vendors to post in their own githubs.

Is there any thought for creating a proper "contrib" upstream directory in the tree for all supported backends?

**Comment by wallnerryan** [comment]
@jsilberm great! thanks for your (future) contribution. Right now we like to keep external drivers of third parties seperate. I can bring the idea of including a seperate contrib upstream. Are you suggesting something like how kubernetes does it here ? https://github.com/kubernetes/kubernetes/tree/master/contrib

**Comment by jsilberm** [comment]
@wallnerryan Actually I was thinking of something more like 'cinder':
https://github.com/openstack/cinder/tree/master/cinder/volume/drivers
But it doesn't sound like that's in the works for the short term, so we'll go ahead and post our driver on our own site.

I'll be posting backend support for Datera shortly.

**Comment by wallnerryan** [comment]
@jsilberm thanks, great! Yes, the debate is whether having the code bits included really matters. Users don't use them all when they get the bits. I've noted it for discussion. Thanks looking forward to it.
