### ISSUE TITLE
conflicting types error while building flocker client

### ISSUE THREAD

**Issue by npcode** [ClusterHQ/flocker#2722]
I tried to install flocker on [this instruction](https://docs.clusterhq.com/en/latest/docker-integration/install-client.html#installing-on-other-linux-distributions) and saw this error while running `pip install https://clusterhq-archive.s3.amazonaws.com/python/Flocker-1.10.2-py2-none-any.whl`:
```
  gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
  build/temp.linux-x86_64-2.7/_openssl.c:686:6: error: conflicting types for ‘BIO_new_mem_buf’
   BIO *BIO_new_mem_buf(void *, int);
        ^
  In file included from /usr/include/openssl/asn1.h:65:0,
                   from build/temp.linux-x86_64-2.7/_openssl.c:402:
  /usr/include/openssl/bio.h:692:6: note: previous declaration of ‘BIO_new_mem_buf’ was here
   BIO *BIO_new_mem_buf(const void *buf, int len);
        ^
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for cryptography
```

My linux distribution is arch linux.

**Comment by wallnerryan** [comment]
Hey @npcode this was fixed recently. see https://github.com/ClusterHQ/flocker/pull/1589. It is in master and you won't run into this with 1.10.3. The issue comments also has a small workaround if you want to get it to work.

**Comment by npcode** [comment]
Thanks, @wallnerryan. I installed flocker on centos instead.
