### ISSUE TITLE
Failover for master control service?

### ISSUE THREAD

**Issue by joe1chen** [ClusterHQ/flocker#2741]
Is there any way to configure a highly available master control service? I could not find any documentation regarding this.

**Comment by wallnerryan** [comment]
Hi @joe1chen the control service does not support HA yes. But you can back regular backups of /var/lib/flocker and the CA/Control Certificates and restoring these on a new control service with the same dns is how we typically tell folks to handle recovery. All services will continue to run when this happens.

Control Service HA is on our roadmap but its unclear when this will be completed yet.
