### ISSUE TITLE
Usage sub-commands (e.g. for `flocker-volume`) help output has some issues

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#275]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-275

1. Include bogus `--version` option that talks about Twisted.
2. Doesn't really document higher-level options. Maybe that's OK.

This is probably not essential for 0.1 unless it turns out sub-commands are being used in `flocker-deploy`.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-275. You are welcome to file additional issues in GitHub if that's easier for you.
