### ISSUE TITLE
flocker dataset agent start fail

### ISSUE THREAD

**Issue by Fangfenghua** [ClusterHQ/flocker#2761]
LOG:

4月 14 07:32:54 node2 systemd[1]: Starting Flocker Dataset Agent...
4月 14 07:32:55 node2 flocker-dataset-agent[3144]: {"task_uuid": "55e977ba-fd66-4568-94c0-1c2360ea2378", "error": false, "timestamp": 1460619175.641084, "message": "Log opened.", "message_type": "twisted:log", "task_level": [1]}
4月 14 07:32:55 node2 flocker-dataset-agent[3144]: {"task_uuid": "e07bfe3c-4279-4622-b9aa-325fdedeb7e1", "error": true, "timestamp": 1460619175.643405, "message": "Unhandled Error\nTraceback (most recent call last):\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 81, in flocker_dataset_agent_main\n    options=options,\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 295, in main\n    self._react(run_and_log, [], _reactor=self._reactor)\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/task.py\", line 882, in react\n    finished = main(_reactor, *argv)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 283, in run_and_log\n    d = maybeDeferred(self.script.main, reactor, options)\n--- <exception caught here> ---\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py\", line 150, in maybeDeferred\n    result = f(*args, **kw)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 292, in main\n    self.service_factory(reactor, options)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 590, in get_service\n    configuration = self.configuration_factory(options)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 362, in get_configuration\n    configuration = yaml.safe_load(agent_config.getContent())\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/__init__.py\", line 93, in safe_load\n    return load(stream, SafeLoader)\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/__init__.py\", line 71, in load\n    return loader.get_single_data()\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/constructor.py\", line 37, in get_single_data\n    node = self.get_single_node()\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/composer.py\", line 36, in get_single_node\n    document = self.compose_document()\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/composer.py\", line 55, in compose_document\n    node = self.compose_node(None, None)\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/composer.py\", line 84, in compose_node\n    node = self.compose_mapping_node(anchor)\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/composer.py\", line 127, in compose_mapping_node\n    while not self.check_event(MappingEndEvent):\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/parser.py\", line 98, in check_event\n    self.current_event = self.state()\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/parser.py\", line 428, in parse_block_mapping_key\n    if self.check_token(KeyToken):\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/scanner.py\", line 116, in check_token\n    self.fetch_more_tokens()\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/scanner.py\", line 220, in fetch_more_tokens\n    return self.fetch_value()\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/scanner.py\", line 580, in fetch_value\n    self.get_mark())\nyaml.scanner.ScannerError: mapping values are not allowed here\n  in \"<string>\", line 2, column 18:\n      control-service:\n                     ^\n", "message_type": "twisted:log", "task_level": [1]}
4月 14 07:32:55 node2 flocker-dataset-agent[3144]: {"task_uuid": "237d6cc2-ee44-40e8-912d-5dfb5cbf080e", "error": true, "timestamp": 1460619175.643855, "message": "main function encountered error\nTraceback (most recent call last):\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 81, in flocker_dataset_agent_main\n    options=options,\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 295, in main\n    self._react(run_and_log, [], _reactor=self._reactor)\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/task.py\", line 882, in react\n    finished = main(_reactor, *argv)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/common/script.py\", line 283, in run_and_log\n    d = maybeDeferred(self.script.main, reactor, options)\n--- <exception caught here> ---\n  File \"/opt/flocker/lib/python2.7/site-packages/twisted/internet/defer.py\", line 150, in maybeDeferred\n    result = f(*args, **kw)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 292, in main\n    self.service_factory(reactor, options)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 590, in get_service\n    configuration = self.configuration_factory(options)\n  File \"/opt/flocker/lib/python2.7/site-packages/flocker/node/script.py\", line 362, in get_configuration\n    configuration = yaml.safe_load(agent_config.getContent())\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/__init__.py\", line 93, in safe_load\n    return load(stream, SafeLoader)\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/__init__.py\", line 71, in load\n    return loader.get_single_data()\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/constructor.py\", line 37, in get_single_data\n    node = self.get_single_node()\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/composer.py\", line 36, in get_single_node\n    document = self.compose_document()\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/composer.py\", line 55, in compose_document\n    node = self.compose_node(None, None)\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/composer.py\", line 84, in compose_node\n    node = self.compose_mapping_node(anchor)\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/composer.py\", line 127, in compose_mapping_node\n    while not self.check_event(MappingEndEvent):\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/parser.py\", line 98, in check_event\n    self.current_event = self.state()\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/parser.py\", line 428, in parse_block_mapping_key\n    if self.check_token(KeyToken):\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/scanner.py\", line 116, in check_token\n    self.fetch_more_tokens()\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/scanner.py\", line 220, in fetch_more_tokens\n    return self.fetch_value()\n  File \"/opt/flocker/lib/python2.7/site-packages/yaml/scanner.py\", line 580, in fetch_value\n    self.get_mark())\nyaml.scanner.ScannerError: mapping values are not allowed here\n  in \"<string>\", line 2, column 18:\n      control-service:\n                     ^\n", "message_type": "twisted:log", "task_level": [1]}
4月 14 07:32:55 node2 flocker-dataset-agent[3144]: {"task_uuid": "7b675e0f-5b9c-42e6-8730-0af7a24fd5cf", "error": false, "timestamp": 1460619175.644134, "message": "Main loop terminated.", "message_type": "twisted:log", "task_level": [1]}
4月 14 07:32:55 node2 systemd[1]: flocker-dataset-agent.service: main process exited, code=exited, status=1/FAILURE
4月 14 07:32:55 node2 systemd[1]: Unit flocker-dataset-agent.service entered failed state.
4月 14 07:32:55 node2 systemd[1]: flocker-dataset-agent.service failed.
4月 14 07:32:55 node2 systemd[1]: flocker-dataset-agent.service holdoff time over, scheduling restart.
4月 14 07:32:55 node2 systemd[1]: start request repeated too quickly for flocker-dataset-agent.service
4月 14 07:32:55 node2 systemd[1]: Failed to start Flocker Dataset Agent.
4月 14 07:32:55 node2 systemd[1]: Unit flocker-dataset-agent.service entered failed state.
4月 14 07:32:55 node2 systemd[1]: flocker-dataset-agent.service failed.

**Comment by wallnerryan** [comment]
@Fangfenghua you error suggests something wrong with your `agent.yml`, can you send me the agent yaml?

Also, please include what version of Flocker, what OS and what backend you are using.

thanks.

**Comment by wallnerryan** [comment]
closing
