### ISSUE TITLE
All nodes are not listed

### ISSUE THREAD

**Issue by aliouba** [ClusterHQ/flocker#2776]
Hello,
I'm using Flocker with VMware Block Device Backend but the Flocker Control Service node don't see all nodes at the same time.

I have 3 nodes on CENTOS 7:
- [ ] node1: All  Flocker Agent Services are up. flocker-dataset-agent, flocker-container-agent and  flocker-docker-plugin are running well. Ip address is 10.20.20.1
- [ ] node2: All  Flocker Agent Services are up. flocker-dataset-agent, flocker-container-agent and  flocker-docker-plugin are running well. Ip address is 10.20.20.2
- [ ] node-control (node control only): The Flocker Control Service is Up. flocker-control is running well. Ip address is 10.20.20.3

flockerctl  list-nodes command shows: 
[root@machine flocker]# flockerctl  list-nodes
```
SERVER         ADDRESS     
56618826       10.20.20.2 
```

If I restart node1 services, then I run flockerctl  list-nodes command, I don't see node2
[root@machine flocker]# flockerctl  list-nodes
```
SERVER         ADDRESS     
56618826       10.20.20.1 
```

**Any ideas?
Why I can not see all the nodes at the same time?
This question concerns Flocker Services? VMware Block Device Backend?**

/opt/flocker/bin/pip freeze  on each node shows:

```
attrs==15.1.0
Babel==1.3
backports.ssl-match-hostname==3.4.0.2
bitmath==1.2.3.post4
boto==2.38.0
boto3==1.2.2
botocore==1.3.17
cffi==1.5.2
characteristic==14.3.0
cryptography==1.2.3
debtcollector==0.5.0
docker-py==1.6.0
docutils==0.12
effect==0.10
eliot==0.11.0
eliot-tree==15.3.0
enum34==1.0.4
Flocker==1.11.0
futures==2.2.0
google-api-python-client==1.4.2
httplib2==0.9.2
hypothesis==1.14.0
idna==2.0
ipaddr==2.1.11
ipaddress==1.0.7
iso8601==0.1.10
jmespath==0.9.0
jsonschema==2.4.0
klein==0.2.3
machinist==0.2.0
msgpack-python==0.4.6
ndg-httpsclient==0.4.0
netaddr==0.7.14
netifaces==0.10.4
oauth2client==1.5.2
oslo.config==1.12.1
oslo.i18n==1.7.0
oslo.serialization==1.6.0
oslo.utils==1.6.0
pbr==0.11.1
prettytable==0.7.2
psutil==2.1.2
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.14
pycrypto==2.6.1
pyOpenSSL==0.15.1
pyrsistent==0.11.12
python-cinderclient==1.1.1
python-dateutil==2.4.2
python-keystoneclient==1.4.0
python-keystoneclient-rackspace==0.1.3
python-novaclient==2.24.1
pytz==2015.4
pyvmomi==6.0.0.2016.4
PyYAML==3.10
repoze.lru==0.6
requests==2.7.0
rsa==3.3
service-identity==14.0.0
simplejson==3.7.3
six==1.9.0
stevedore==1.5.0
toolz==0.7.4
treq==0.2.1
Twisted==15.5.0
txeffect==0.9
uritemplate==0.6
vSphere-Flocker-driver==1.0
websocket-client==0.32.0
Werkzeug==0.10.4
wrapt==1.10.4
zope.interface==4.1.2
```

I have not seen any error of Flocker Agents Services and Flocker Control Service.

**Comment by wallnerryan** [comment]
Hi @aliouba,

I notice that in the case of seeing `10.20.20.1` or `10.20.20.2` the same server ID is used `56618826`. Did you by chance use the same `node.crt` and `node.key` for both servers.

Make sure to create a seperate `node.crt/key` for each server.

**Comment by aliouba** [comment]
You're right. My bad.

Thank you very much
