### ISSUE TITLE
Flocker control HA

### ISSUE THREAD

**Issue by jm66** [ClusterHQ/flocker#2777]
Hi,

We are testing a docker swarm with two managers (active and stand by) and three nodes using flocker with the vSphere driver. In this configuration there's only one flocker control node and I was wondering how to setup a secondary flocker control node or whether it is possible. 

Thanks
JM

**Comment by jm66** [comment]
Never mind. Found #2741

**Comment by wallnerryan** [comment]
@jm66 yes that method can be used to help recover a control node for HA, but its not active/active or active/standby. We know this has been asked for and it is on our roadmap but we dont have a date for it yet. 

Thanks

**Comment by wallnerryan** [comment]
closing this

**Comment by ferrantim** [comment]
@jm66 can you let us know if you run into any issues with the vSphere driver?  We worked through an issue with another user recently and it should be fixed, but please let us know if you have any issues.

Thanks!
