### ISSUE TITLE
Support internationalized domain names

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#281]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-281

We currently treat application hostnames as bytes, but it might be nice to support internationalized domain names. 

This will require hostnames to be `idna` encoded before we pass them to DNS client APIs and probably when we compare and sort hostnames.

It might be worth having a `DomainName` type with the necessary encoding and decoding methods and which can be sensibly compared and sorted.

See:
 * https://github.com/ClusterHQ/flocker/pull/232#discussion_r14667836
 * https://github.com/ClusterHQ/flocker/pull/280/files#discussion_r14869857

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-281. You are welcome to file additional issues in GitHub if that's easier for you.
