### ISSUE TITLE
Where in flocker code volume mounting occurs?

### ISSUE THREAD

**Issue by gufranmmu** [ClusterHQ/flocker#2815]
Could you please find me the file and line of code where flocker volume mounting is happening when a docker command is executed with --volume-driver=flocker ?

**Comment by wallnerryan** [comment]
Hi,

The answer is two fold. Each plugin that runs with Flocker must manage the "attach" of a block device, you can look at your particular plugin code under `flocker/node/agents/` or in the particular plugin code. Also, flocker will mount and put a filesystem on an attached block device here https://github.com/ClusterHQ/flocker/blob/master/flocker/node/agents/blockdevice.py#L577
