### ISSUE TITLE
Flocker datastore in physical machine

### ISSUE THREAD

**Issue by pmann91** [ClusterHQ/flocker#2816]
Hi,

I have worked with flocker on both physical and cloud machine. Flocker cluster works perfectly on cloud whereas on physical machines it sometimes not able to work properly. 

I have read [google group discussion](https://groups.google.com/forum/#!topic/flocker-users/l5wCW-U1zKs) in which Ryan Wallner has mentioned "zfs have been deprecated. There are known issues with using it that we aren't working on fixing right now. We will be supporting ceph soon"

Till Ceph is introduced as datastore, what can be used on physical machines?

**Comment by wallnerryan** [comment]
@pmann91 you can still use ZFS and Ceph for non-production usecases as they both still need more development. 

Here is the ceph driver - https://github.com/ClusterHQ/ceph-flocker-driver but note there are bugs.

If you are looking for a more enterprise ready solution, you can use something such as an sds solution like ScaleIO, OpenVStorage, ConvergeIO, Hedvig.

**Comment by wallnerryan** [comment]
closing

**Comment by pmann91** [comment]
Thanks @wallnerryan :)
