### ISSUE TITLE
Loopback w/ Swarm

### ISSUE THREAD

**Issue by vladfau** [ClusterHQ/flocker#2819]
Hi guys,

I installed and configured Flocker with Loopback driver as I don't have opportunity to use EC2/Openstack/etc. hosting. Is there any way how I can using Loopback backend and Swarm as it seems to not sync data if containers are on different hosts? 

Thanks.

**Comment by wallnerryan** [comment]
Loopback is ONLY for testing. It does not support data movement. Please choose a different backend. 

You can try to use ScaleIO, Ceph ok OpenvStorage which are open-source/free version of backends.
