### ISSUE TITLE
New Volume Driver - Metadata Unable to be Sent with JSON Request

### ISSUE THREAD

**Issue by tjb1019** [ClusterHQ/flocker#2843]
Hello,

I am looking to implement a Flocker volume driver for the [ProfitBricks](https://www.profitbricks.com/) provider.  When reading through the [contributing documentation](https://docs.clusterhq.com/en/latest/gettinginvolved/plugins/prereqs.html), I noticed that being able to store metadata on a volume is required.  Unfortunately, this is not currently possible with the ProfitBricks provider.  There isn't even another key that I can piggyback off of like "description".  They don't currently have any type of tagging system for volumes.  

Any suggestions as to how to get around this?  Would applying a tagging system to the volume's "name" key be acceptable?

**Comment by wallnerryan** [comment]
@tjb1019 yes, we are aware some providers dont allow storing metadata. There are a few approaches, you can use an external store to keep this info, are try and hash it into the name.

VMAX is an example of using an external store (redis)
https://github.com/emccode/flocker-drivers/tree/master/vmax#installation

Scaleio uses the chars available in the name of the volume to store just enough of the data.
https://github.com/emccode/flocker-drivers/blob/master/scaleio/scaleio_flocker_driver/emc_sio.py#L591

**Comment by tjb1019** [comment]
@wallnerryan Thanks for the help!

The ProfitBricks driver is now complete.  It can be found here: https://github.com/profitbricks/profitbricks-flocker-driver

How would one go about getting the driver added to the Community Drivers page? https://docs.clusterhq.com/en/latest/flocker-features/storage-backends.html#supported-backends

**Comment by wallnerryan** [comment]
@tjb1019 awesome great job. One thing we would need you to do is run the acceptance tests against your driver. https://docs.clusterhq.com/en/latest/gettinginvolved/acceptance-testing.html

Then, i will get you in touch with @ferrantim who can help you add it to the supported backends. Send me an email at ryan.wallner@clusterhq.com and we can take it from there. I am going to close this issue
