### ISSUE TITLE
How to configure and access the '--metadata' attribute in "flockerctl create" command?

### ISSUE THREAD

**Issue by akshaycalsoft** [ClusterHQ/flocker#2846]
Hello,

I am looking to implement a Flocker volume driver. In "flockerctl create" command I noticed that being able to store metadata on a volume is required. I have few questions about the 'metadata' attribute.
1) What kind of "key=value" pairs can we pass?
2) How to access and modify these parameters in my Flocker Driver?
3) How can we give user defined dataset_id to a volume being created using this command?

**Comment by wallnerryan** [comment]
@akshaycalsoft storing metadata is not required, it is optional for the user to associate k/v paris. Usually, there is not need to touch the metadata parameters in a flocker (plugin) driver, this is only for us for the end user. You cannot use `flockerctl` to use a user defined `dataset_id` but you may use the REST api interface to do so.

**Comment by akshaycalsoft** [comment]
@wallnerryan Thank you for the response.

**Comment by akhilcalsoft** [comment]
@wallnerryan,

Can we pass optional parameter via flockerctl command and get it in flocker driver ?
