### ISSUE TITLE
i use flocker with ceph ,run is ok but write ceph control cpu is hightest

### ISSUE THREAD

**Issue by 332054781** [ClusterHQ/flocker#2862]
i use  fio -ioengine=libaio -bs=4k -direct=1 -thread -rw=randwrite -size=512M -filename=ss.iso -name="CEPH 4KB randwrite test" -iodepth=32 -runtime=60 test iops 
but ceph control cpu is 99% when is not write cpu is 1%-10%.
please help me

**Comment by wallnerryan** [comment]
If ceph runs with high CPU, please reach out to their support.
