### ISSUE TITLE
Question  

### ISSUE THREAD

**Issue by RotemEmergi** [ClusterHQ/flocker#2883]
Hi , 

I want to install Floker and work with that .

I have some question before:

1.I Read your all doc and understand that your solution in stable after a restart or reboot for all the servers, this is true? No data loss?

2. Did your solution can work in a rancher?

3. Did you have backward compatible for docker? 

4. Did Your solution work on docker 1.12 and compose 1.8?

5. There is a way to work with your platform offline? 

6.There is a way to install Volume Hub on offline sever by docker? 

Best regards

**Comment by wallnerryan** [comment]
1.I Read your all doc and understand that your solution in stable after a restart or reboot for all the servers, this is true? No data loss?
>>correct, flocker does not hold any data bits. Therefore devices and volumes under flocker control converge when the control service comes back online, otherwise everything remains the same. 

Did your solution can work in a rancher?
>> No, not at the moment.

Did you have backward compatible for docker?
>> Yes. Flocker will work with all Docker versions. However you will need to use Docker 1.9 + if you want to use docker volume plugin integration.

Did Your solution work on docker 1.12 and compose 1.8?
>> Yes, but currently (1.13) there is a bug that doesnt work with 1.12 and has been fixed and should be in Flocker 1.14 which should be released today which supports Docker 1.12.

There is a way to work with your platform offline?
>>> What do you mean?

6.There is a way to install Volume Hub on offline sever by docker?
>>> Not, not today
