### ISSUE TITLE
Question : How to mention the volume profile in docker run command?

### ISSUE THREAD

**Issue by shay-berman** [ClusterHQ/flocker#2884]
it  looks like "docker run" cannot get the volume options flag:
#> docker run -it --volume-driver flocker -o profile=gold -v gold_volume:/data ubuntu bash
flag provided but not defined: -o

the alternative is to create the volume first with the relevant profile and then use the volume in the docker run command.
#> docker volume create -d flocker -o profile=gold --name gold_volume
#> docker run -it --volume-driver flocker -v gold_volume:/data ubuntu bash

But is there a way to use profiles in the same docker run command?

Thanks 
Shay

**Comment by wallnerryan** [comment]
@shay-berman no, this is the docker workflow. 

The below the the recommended workflow. You can open an issue with docker 
```
 docker volume create -d flocker -o profile=gold --name gold_volume
docker run -it  -v gold_volume:/data ubuntu bash
```

**Comment by shay-berman** [comment]
I think we should consider to improve that in the Docker project.
docker run -v will create the volume but with default profile, 
so it would be nice to add an option to specify the profile of the volume in the docker run command (instead of first create the volume with a specific profile and then docker run with this volume).

I agree its in the docker project and not in Flocker.
