### ISSUE TITLE
Doesn't work on ProjectAtomic

### ISSUE THREAD

**Issue by cten** [ClusterHQ/flocker#2891]
It appears that the RPMs install in the /opt directory which is emptied in the Atomic builds. Can support for Atomic compliant RPMs be started?

**Comment by wallrj** [comment]
We have no plans to create Project Atomic RPMs.

We have a side project where we package Flocker as a Docker image.
 * https://github.com/ClusterHQ/flocker-coreos/tree/master/flocker-bits

It's not well documented and it's not as well supported as other package formats.

We *are* planning to add better documentation and testing for the installation of Flocker-in-containers.
