### ISSUE TITLE
flocker volume didn't migrate with container to new host in kubernetes env.

### ISSUE THREAD

**Issue by hgsat123** [ClusterHQ/flocker#2894]
I have 3 node kubernetes cluster running on ubuntu 14.04
flocker is installed on top of these 3 nodes with one node as control.
created a flocker volume on one of the node & executed redis rc using kubectl. Attempted to migrate this redis container with mounted flocker volume to new host.  Though container migrated, volume remained on the host where it was created.  Attached is the detail command o/p. If you need any flocker process logs, please let me know. I accidently pasted this issue under https://github.com/binocarlos/flocker/issues
[flocker_fail.txt](https://github.com/ClusterHQ/flocker/files/451349/flocker_fail.txt)

**Comment by wallnerryan** [comment]
cc @wallrj

**Comment by hgsat123** [comment]
Hello Ryan,
I'm not clear on the behaviour of flocker with local storage. because, i tested this migration using flocker volume created from local storage. Thought of checking with Flocker team.

**Comment by hgsat123** [comment]
"flockerctl move" is failing.  the volume status is stuck at "detached" state on target node after move. Its not getting mounted or attached automatically after "flockerctl move".
Ex:
root@kube-host3:/etc# df -T | awk '{print $1,$2,$NF}' | grep "^/dev"
/dev/vda1 ext4 /
/dev/vdb ext4 /mnt

root@kube-host3:/etc# docker volume create --driver flocker -o type=ext4 -o device=/dev/vdb --name blr1 -o size=5GB

root@kube-host3:/etc# docker volume ls
DRIVER              VOLUME NAME
flocker             blr1

root@kube-host3:/etc# flockerctl list
DATASET                                SIZE    METADATA                            STATUS         SERVER
5cddd7b6-2606-49c3-8d9c-5cbc22331868   5.00G   maximum_size=5368709120,name=blr1   attached ✅   58f445f9 (10.222.245.40)

root@kube-host3:~# flockerctl list-nodes
SERVER     ADDRESS
58f445f9   10.222.245.40
b9b7ec2b   10.222.245.33

root@kube-host3:~# flockerctl move -d 5cddd7b6-2606-49c3-8d9c-5cbc22331868 -t b9b7ec2b
initiated move of dataset, please check state to observe it actually move.

root@kube-host3:~# flockerctl list
DATASET                                SIZE    METADATA                            STATUS     SERVER
5cddd7b6-2606-49c3-8d9c-5cbc22331868   5.00G   maximum_size=5368709120,name=blr1   detached   b9b7ec2b (10.222.245.33)

**Comment by wallrj** [comment]
In https://github.com/ClusterHQ/flocker/issues/2894#issuecomment-246346663 @hgsat123 wrote:
> I'm not clear on the behaviour of flocker with local storage. because, i tested this migration using flocker volume created from local storage. Thought of checking with Flocker team. 

If you're talking about the Loopback backend, no, it doesn't support migration of volumes.

 * https://docs.clusterhq.com/en/latest/flocker-features/loopback-configuration.html#loopback-dataset-backend

**Comment by hgsat123** [comment]
Thanks Richard.

I read the FAQ later as there was no clarity on Flocker behavior w.r.t volumes created using local (host) storage.
I will retest with external block storage.

Regards,
Satish
