### ISSUE TITLE
flocker and k8s , use k8s up docker container is ok but over time dataset status is pending

### ISSUE THREAD

**Issue by victorye88** [ClusterHQ/flocker#2897]
Flocker and k8s , use k8s up docker container is ok but over time volume( dataset) status is pending,I can't use it again：
1、use “flockerctl --control-service=nodeIP create –m name=my-volume –s 100M -n dataset ”，dataset will be attached;
2、But over time dataset status is pending（maybe 20 minutes）;
3、We need use “systemctl restart flocker-dataset-agent.service” to make sure that the volume(or dataset) status recovery to  attached.

Please help solve this problem，Thanks a lot！

**Comment by wallnerryan** [comment]
can you post the logs from the flocker-dataset-agent when the volume becomes "pending". Also, what backend are you using for flocker?

**Comment by victorye88** [comment]
● flocker-dataset-agent.service - Flocker Dataset Agent
   Loaded: loaded (/usr/lib/systemd/system/flocker-dataset-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2016-09-08 14:21:42 CST; 43min ago
 Main PID: 525 (flocker-dataset)
   CGroup: /system.slice/flocker-dataset-agent.service
           └─525 /opt/flocker/bin/python /usr/sbin/flocker-dataset-agent --journald

Sep 08 15:05:34 flocker-node.huawei.com flocker-dataset-agent[525]: {"timestamp": 1473318334.413439, "task_uuid": "bec86b82-e947-4f6e-b1f4-0731ed9a45f3", "message_type": "agent:blockdevice:raw_state", "raw_state": "RawState(compute_instance_id=u'flocker-node03', devices_with_filesystems=FilepathPSet([]), devices=UuidToFilepathPMap({}), system_mounts=FilepathToFilepathPMap({FilePath('/dev/vda1'): FilePath('/')}), volumes=BlockdevicevolumePVector([]), _live_instances=None)", "task_level": [2, 2, 6]}
Sep 08 15:05:34 flocker-node.huawei.com flocker-dataset-agent[525]: {"task_uuid": "bec86b82-e947-4f6e-b1f4-0731ed9a45f3", "task_level": [2, 2, 7], "action_type": "flocker:agent:discovery", "timestamp": 1473318334.416771, "state": "BlockDeviceDeployerLocalState(node_uuid=UUID('67530cae-df6d-41c1-8a30-9733532dd9ce'), datasets=UuidToDiscovereddatasetPMap({UUID('bfec9bc2-d9a2-4abe-b170-110a32a9cc42'): DiscoveredDataset(blockdevice_id=u'225', state=<DatasetStates=REGISTERED>, dataset_id=UUID('bfec9bc2-d9a2-4abe-b170-110a32a9cc42')), UUID('085fc9b9-40be-4f25-8d1a-85c7ca6ae6e1'): DiscoveredDataset(blockdevice_id=u'225', state=<DatasetStates=REGISTERED>, dataset_id=UUID('085fc9b9-40be-4f25-8d1a-85c7ca6ae6e1')), UUID('3b976bde-9a8c-493a-aec3-ff21283f5e75'): DiscoveredDataset(blockdevice_id=u'65', state=<DatasetStates=REGISTERED>, dataset_id=UUID('3b976bde-9a8c-493a-aec3-ff21283f5e75')), UUID('d22f91c6-ba8c-479d-810b-f7ed429d1412'): DiscoveredDataset(blockdevice_id=u'222', state=<DatasetStates=REGISTERED>, dataset_id=UUID('d22f91c6-ba8c-479d-810b-f7ed429d1412')), UUID('a4073575-c4fb-4d36-b0bf-914f9b5fdbdc'): DiscoveredDataset(blockdevice_id=u'222', state=<DatasetStates=REGISTERED>, dataset_id=UUID('a4073575-c4fb-4d36-b0bf-914f9b5fdbdc')), UUID('e250b103-e9a7-4e06-92ac-35682761d517'): DiscoveredDataset(blockdevice_id=u'65', state=<DatasetStates=REGISTERED>, dataset_id=UUID('e250b103-e9a7-4e06-92ac-35682761d517'))}), hostname=u'10.63.125.174')", "action_status": "succeeded"}
Sep 08 15:05:34 flocker-node.huawei.com flocker-dataset-agent[525]: {"timestamp": 1473318334.420628, "task_uuid": "bec86b82-e947-4f6e-b1f4-0731ed9a45f3", "message_type": "flocker:agent:converge:actions", "task_level": [2, 3], "calculated_actions": "NoOp(sleep=datetime.timedelta(0, 3))"}
Sep 08 15:05:34 flocker-node.huawei.com flocker-dataset-agent[525]: {"timestamp": 1473318334.421259, "task_uuid": "bec86b82-e947-4f6e-b1f4-0731ed9a45f3", "action_type": "flocker:change:noop", "action_status": "started", "task_level": [2, 4, 1]}
Sep 08 15:05:34 flocker-node.huawei.com flocker-dataset-agent[525]: {"timestamp": 1473318334.421704, "task_uuid": "bec86b82-e947-4f6e-b1f4-0731ed9a45f3", "action_type": "flocker:change:noop", "action_status": "succeeded", "task_level": [2, 4, 2]}
Sep 08 15:05:34 flocker-node.huawei.com flocker-dataset-agent[525]: {"delay": 3.098140844426936, "task_uuid": "bec86b82-e947-4f6e-b1f4-0731ed9a45f3", "log_level": "INFO", "timestamp": 1473318334.422739, "message": "Delaying until next convergence loop.", "message_type": "flocker:node:_loop:CONVERGE:delay", "task_level": [2, 5]}
Sep 08 15:05:34 flocker-node.huawei.com flocker-dataset-agent[525]: {"fsm_identifier": "<flocker.node._loop.ConvergenceLoop object at 0x3e42f50>", "fsm_input": "<ConvergenceLoopInputs=SLEEP>", "timestamp": 1473318334.42335, "fsm_rich_input": "<_Sleep>", "action_status": "started", "task_uuid": "bec86b82-e947-4f6e-b1f4-0731ed9a45f3", "action_type": "fsm:transition", "fsm_state": "<ConvergenceLoopStates=CONVERGING>", "task_level": [2, 6, 1]}
Sep 08 15:05:34 flocker-node.huawei.com flocker-dataset-agent[525]: {"fsm_next_state": "<ConvergenceLoopStates=SLEEPING>", "task_level": [2, 6, 2], "action_type": "fsm:transition", "timestamp": 1473318334.423887, "fsm_output": ["<ConvergenceLoopOutputs=SCHEDULE_WAKEUP>"], "task_uuid": "bec86b82-e947-4f6e-b1f4-0731ed9a45f3", "action_status": "succeeded"}
Sep 08 15:05:34 flocker-node.huawei.com flocker-dataset-agent[525]: {"timestamp": 1473318334.424433, "task_uuid": "bec86b82-e947-4f6e-b1f4-0731ed9a45f3", "action_type": "flocker:agent:converge", "action_status": "succeeded", "task_level": [2, 7]}
Sep 08 15:05:34 flocker-node.huawei.com flocker-dataset-agent[525]: {"fsm_next_state": "<ConvergenceLoopStates=SLEEPING>", "task_level": [3], "action_type": "fsm:transition", "timestamp": 1473318334.424959, "fsm_output": ["<ConvergenceLoopOutputs=CLEAR_WAKEUP>", "<ConvergenceLoopOutputs=CONVERGE>"], "task_uuid": "bec86b82-e947-4f6e-b1f4-0731ed9a45f3", "action_status": "succeeded"}

**Comment by victorye88** [comment]
journalctl log :

Sep 08 15:01:38 flocker-node.huawei.com flocker-dataset-agent[525]: {"timestamp": 1473318098.008371, "task_uuid": "f0b7bc6f-c6ca-4dda-822d-33b60d777409", "message_type": "agent:blockdevice:raw_state", "raw_state": "RawState(compute_instance_id=u'flocker-node03', devices_with_filesystems=FilepathPSet([]), devices=UuidToFilepathPMap({}), system_mounts=FilepathToFilepathPMap({FilePath('/dev/vda1'): FilePath('/')}), volumes=BlockdevicevolumePVector([]), _live_instances=None)", "task_level": [2, 2, 6]}
Sep 08 15:01:38 flocker-node.huawei.com flocker-dataset-agent[525]: {"task_uuid": "f0b7bc6f-c6ca-4dda-822d-33b60d777409", "task_level": [2, 2, 7], "action_type": "flocker:agent:discovery", "timestamp": 1473318098.012021, "state": "BlockDeviceDeployerLocalState(node_uuid=UUID('67530cae-df6d-41c1-8a30-9733532dd9ce'), datasets=UuidToDiscovereddatasetPMap({UUID('bfec9bc2-d9a2-4abe-b170-110a32a9cc42'): DiscoveredDataset(blockdevice_id=u'225', state=<DatasetStates=REGISTERED>, dataset_id=UUID('bfec9bc2-d9a2-4abe-b170-110a32a9cc42')), UUID('085fc9b9-40be-4f25-8d1a-85c7ca6ae6e1'): DiscoveredDataset(blockdevice_id=u'225', state=<DatasetStates=REGISTERED>, dataset_id=UUID('085fc9b9-40be-4f25-8d1a-85c7ca6ae6e1')), UUID('3b976bde-9a8c-493a-aec3-ff21283f5e75'): DiscoveredDataset(blockdevice_id=u'65', state=<DatasetStates=REGISTERED>, dataset_id=UUID('3b976bde-9a8c-493a-aec3-ff21283f5e75')), UUID('d22f91c6-ba8c-479d-810b-f7ed429d1412'): DiscoveredDataset(blockdevice_id=u'222', state=<DatasetStates=REGISTERED>, dataset_id=UUID('d22f91c6-ba8c-479d-810b-f7ed429d1412')), UUID('a4073575-c4fb-4d36-b0bf-914f9b5fdbdc'): DiscoveredDataset(blockdevice_id=u'222', state=<DatasetStates=REGISTERED>, dataset_id=UUID('a4073575-c4fb-4d36-b0bf-914f9b5fdbdc')), UUID('e250b103-e9a7-4e06-92ac-35682761d517'): DiscoveredDataset(blockdevice_id=u'65', state=<DatasetStates=REGISTERED>, dataset_id=UUID('e250b103-e9a7-4e06-92ac-35682761d517'))}), hostname=u'10.63.125.174')", "action_status": "succeeded"}
Sep 08 15:01:38 flocker-node.huawei.com flocker-dataset-agent[525]: {"timestamp": 1473318098.016293, "task_uuid": "f0b7bc6f-c6ca-4dda-822d-33b60d777409", "message_type": "flocker:agent:converge:actions", "task_level": [2, 3], "calculated_actions": "NoOp(sleep=datetime.timedelta(0, 3))"}
Sep 08 15:01:38 flocker-node.huawei.com flocker-dataset-agent[525]: {"timestamp": 1473318098.01705, "task_uuid": "f0b7bc6f-c6ca-4dda-822d-33b60d777409", "action_type": "flocker:change:noop", "action_status": "started", "task_level": [2, 4, 1]}
Sep 08 15:01:38 flocker-node.huawei.com flocker-dataset-agent[525]: {"timestamp": 1473318098.017535, "task_uuid": "f0b7bc6f-c6ca-4dda-822d-33b60d777409", "action_type": "flocker:change:noop", "action_status": "succeeded", "task_level": [2, 4, 2]}
Sep 08 15:01:38 flocker-node.huawei.com flocker-dataset-agent[525]: {"delay": 3.5709816607563827, "task_uuid": "f0b7bc6f-c6ca-4dda-822d-33b60d777409", "log_level": "INFO", "timestamp": 1473318098.018296, "message": "Delaying until next convergence loop.", "message_type": "flocker:node:_loop:CONVERGE:delay", "task_level": [2, 5]}
Sep 08 15:01:38 flocker-node.huawei.com flocker-dataset-agent[525]: {"fsm_identifier": "<flocker.node._loop.ConvergenceLoop object at 0x3e42f50>", "fsm_input": "<ConvergenceLoopInputs=SLEEP>", "timestamp": 1473318098.018892, "fsm_rich_input": "<_Sleep>", "action_status": "started", "task_uuid": "f0b7bc6f-c6ca-4dda-822d-33b60d777409", "action_type": "fsm:transition", "fsm_state": "<ConvergenceLoopStates=CONVERGING>", "task_level": [2, 6, 1]}
Sep 08 15:01:38 flocker-node.huawei.com flocker-dataset-agent[525]: {"fsm_next_state": "<ConvergenceLoopStates=SLEEPING>", "task_level": [2, 6, 2], "action_type": "fsm:transition", "timestamp": 1473318098.019574, "fsm_output": ["<ConvergenceLoopOutputs=SCHEDULE_WAKEUP>"], "task_uuid": "f0b7bc6f-c6ca-4dda-822d-33b60d777409", "action_status": "succeeded"}
Sep 08 15:01:38 flocker-node.huawei.com flocker-dataset-agent[525]: {"timestamp": 1473318098.020178, "task_uuid": "f0b7bc6f-c6ca-4dda-822d-33b60d777409", "action_type": "flocker:agent:converge", "action_status": "succeeded", "task_level": [2, 7]}
Sep 08 15:01:38 flocker-node.huawei.com flocker-dataset-agent[525]: {"fsm_next_state": "<ConvergenceLoopStates=SLEEPING>", "task_level": [3], "action_type": "fsm:transition", "timestamp": 1473318098.020692, "fsm_output": ["<ConvergenceLoopOutputs=CLEAR_WAKEUP>", "<ConvergenceLoopOutputs=CONVERGE>"], "task_uuid": "f0b7bc6f-c6ca-4dda-822d-33b60d777409", "action_status": "succeeded"}

**Comment by victorye88** [comment]
The backend I using for flocker is HuaWei OceanStor18000.Thanks!

**Comment by wallnerryan** [comment]
I dont see anything in the logs on the flocker side of things why it would become pending overtime, is there anything in the oceanstore logs? Only thing I could think of is a network issue with FC or iSCSI between the host with the volume and the oceanstore array. Anything in the system logs about a iscsi or FC connection being flappy or anything?


I noticed you opened an issue here too, maybe worth adding more information about logs etc
https://github.com/huaweistorage/huawei-oceanstor-flocker-plugin/issues/1

**Comment by wallrj** [comment]
We can't debug this further without seeing the full logs from all Flocker processes on all nodes. 

It looks like the OceanStore plugin logs some useful information:
 * https://github.com/huaweistorage/huawei-oceanstor-flocker-plugin/blob/master/huawei_oceanstor_flocker_plugin/huawei_oceanstor_blockdevice.py

Glancing at the code it looks like the REST API connection is only established during class initialisation, so perhaps the HTTP session fails and is not re-established.

And I notice that the FC / iSCSI connection is initialised during attachment but not during detachment, but I'm not sure if that's important.

Please re-open this issue if you are still encountering the problem and please include complete `flocker-diagnostic` files from all nodes.

 * https://docs.clusterhq.com/en/latest/administering/debugging.html
