### ISSUE TITLE
flocker with two node , when node1 down and use flockerctl move volume to node2,but  volume status always pending

### ISSUE THREAD

**Issue by 332054781** [ClusterHQ/flocker#2903]
flocker with two node , when node1 down and use flockerctl move volume to node2,but  volume status always pending，
i use flocker version 1.15.0

**Comment by wallrj** [comment]
You'll need to look through the logs for information about where it's failing.
 * https://docs.clusterhq.com/en/latest/administering/debugging.html

If you still can't find the cause of the problem, re-open this issue and provide as much detail as you can about the environment using the `flocker-diagnostics` tool or by collecting the information manually:
 * https://docs.clusterhq.com/en/latest/administering/debugging.html#export-logs-using-flocker-diagnostics

(don't upload the logs to Github if they contain sensitive information)
