### ISSUE TITLE
 Flocker driver for Ceph storage - error

### ISSUE THREAD

**Issue by rajkumar49** [ClusterHQ/flocker#2904]
Hi,
 How to configure the flocker driver for Ceph ?
i have seen the below in your website :

> version: 1
>   control-service:
>     hostname: "user.controlserver.example.com"
>   dataset:
>     backend: "ceph_flocker_driver"
>     cluster_name: "Ceph cluster name, defaults to ''"
>     user_id: "Ceph user ID, defaults to 'admin'"
>     ceph_conf_path: "path to ceph conf for rados, defaults to '/etc/ceph/ceph.conf'"
>     storage_pool: "name of storage pool to use, defaults to 'rbd'
1. here Cluster_name is IP address of Ceph server?
2. error in current ceph /flocker setup: 
   **command:** docker run -v test1:/data --volume-driver flocker busybox sh -c "echo hello > /data/file.txt"
   **response** : docker: Error response from daemon: Timed out waiting for dataset to mount..

**Comment by wallnerryan** [comment]
1. it is actually, just the cluster name. http://docs.ceph.com/docs/jewel/rados/deployment/ceph-deploy-new/#naming-a-cluster

2. This isnt really helpful. Please provide a full set of logs for us to help you. You can find more about how to do that here https://docs.clusterhq.com/en/latest/administering/debugging.html#debugging-flocker

**Comment by rajkumar49** [comment]
Hi @wallnerryan , if we can use just the Cluster name here , where we have to give the IP of the Ceph cluster?

**Comment by wallnerryan** [comment]
@rajkumar49 the ceph driver is not ready for production so it may not have all the bells and whistles yet. Right now I think it assumes it can talk to `rbd` client on the localhost which in turn runs against the cluster.

**Comment by galindro** [comment]
@wallnerryan is there an ETA for the ceph flocker driver to be production ready?

**Comment by adamtheturtle** [comment]
@galindro ClusterHQ has closed down and is therefore no longer working on Flocker or drivers for Flocker. However, a group of ex-ClusterHQ engineers are offering support plans and feature development at http://scatterhq.com.
