### ISSUE TITLE
ebs.py badly formed hexadecimal string

### ISSUE THREAD

**Issue by gufranmmu** [ClusterHQ/flocker#2950]
Hi,

When for some reason an EBS volume has 'None' as the cluster_id or anything other than a hexadecimal string, flocker is failing.

https://github.com/ClusterHQ/flocker/blob/master/flocker/node/agents/ebs.py#L824-L826  
As a quick fix, here is what i did.

```
    if actual_cluster_id:
        actual_cluster_id = UUID(actual_cluster_id.pop())
        if actual_cluster_id == cluster_id:
            return True
return False


To

    if actual_cluster_id:
        if actual_cluster_id[0] != 'None':
            actual_cluster_id = UUID(actual_cluster_id.pop())
            if actual_cluster_id == cluster_id:
                return True
return False

```

I think it should be checked first that if the string is a hexadecimal formatted string: actual_cluster_id.pop()

**Comment by wallnerryan** [comment]
@gufranmmu would you be interested to submit this as a PR ? We would love to have your contribution.

cc @wallrj

**Comment by wallrj** [comment]
Hey @gufranmmu 
Sorry I missed this conversation and thanks for taking the time to report the issue.
The same problem was reported by another user last week and we fixed it in https://github.com/ClusterHQ/flocker/issues/2950
Like @wallnerryan, I too would like to know how the cluster ID got set to `"None"`.
Were you changing the EBS volume tags from AWS / manually?
