### ISSUE TITLE
Unknown lvalue 'PrivateDev' in section 'Service'

### ISSUE THREAD

**Issue by KeithTt** [ClusterHQ/flocker#2979]
Dec 16 17:32:01 k8s-master systemd[1]: [/usr/lib/systemd/system/flocker-control.service:9] Unknown lvalue 'PrivateDev' in section 'Service'
Dec 16 17:32:01 k8s-master systemd[1]: [/usr/lib/systemd/system/flocker-control.service:12] Unknown lvalue 'ReadonlyDirectories' in section 'Service'

when i start flocker-control service, there always appear this infomation, but i can see the ports 4523,4524.

tcp        0      0 0.0.0.0:4523            0.0.0.0:*               LISTEN      22799/python        
tcp        0      0 0.0.0.0:4524            0.0.0.0:*               LISTEN      22799/python

**Comment by wallrj** [comment]
@keith4743 We test and support Flocker on the following operating systems: Centos-7, Ubuntu-14.04, Ubuntu-16.04 and RHEL-7.

What operating system are you using? (`cat /etc/os-release`)

And what version of `systemd` does it have? (`systemctl --version`)

**Comment by keith4743** [comment]
@wallrj  CentOS7.2 and systemd 219

**Comment by man4j** [comment]
I have same issue ((( Ubuntu 16.04 systemd 229

**Comment by fogray** [comment]
I have the same issue. My OS is centos7:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
