### ISSUE TITLE
flocker can't connect to a Vagrant-assisted VM setup

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#298]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-298

Vagrant starts sets up some SSH servers on localhost:<not port 22>.

`configure_ssh` and `ProcessNode.using_ssh` both want to connect to the SSH server on port 22.

This is a problem when the CLI needs to connect to a node: it won't be able to.

This is also a problem when one node wants to connect to another node.

One solution is to write a Vagrantfile that puts SSH on port 22 (and somehow assigns some unique addresses, too, so these don't conflict).  I'm not sure how you do this with the vagrant config language, exactly.

A different, partial solution is to not specify the port number if it is 22 (ie, the default) and let people write an ssh config file that specifies the correct port number to use.  This is awkward and slightly annoying but it solves the cli->node issue.  It doesn't solve the node->node issue (even if you put a config file on your nodes, I think, because you have no address to connect to to reach other nodes).  Perhaps this could be worked around by proxying even more ports or some other more complicated network configuration (but this sounds complex and we probably want to avoid it).

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-298. You are welcome to file additional issues in GitHub if that's easier for you.
