### ISSUE TITLE
Failed to start Flocker Docker Plugin

### ISSUE THREAD

**Issue by keith4743** [ClusterHQ/flocker#2980]
Failed to start Flocker Container Agent.
Failed to start Flocker Dataset Agent.

all the agent service failed to start, i followed the official guide:
https://flocker-docs.clusterhq.com/en/latest/index.html

**Comment by wallrj** [comment]
@keith4743 Please look at https://flocker-docs.clusterhq.com/en/latest/administering/debugging.html#debugging which describes how to diagnose problems with Flocker processes.

Re-open this issue if you find a bug in Flocker.
