### ISSUE TITLE
how to get user.crt and user.key

### ISSUE THREAD

**Issue by timchenxiaoyu** [ClusterHQ/flocker#2985]
I see the docs,call api need user.crt and user.key
curl --cacert $PWD/cluster.crt --cert $PWD/user.crt --key $PWD/user.key \
     https://172.16.255.250:4523/v1/configuration/containers

how to generate these?

**Comment by wallnerryan** [comment]
These are the same certificates you created during the flocker installation/configuration using the cli tools.

FYI, This project is moving to https://github.com/ScatterHQ/flocker, a small number of the clusterhq folks will try to maintain it to a certain degree if the community wants it.
