### ISSUE TITLE
Will this repo be maintained given that clusterHQ is shutting down?

### ISSUE THREAD

**Issue by kant111** [ClusterHQ/flocker#2989]
Will this repo be maintained given that clusterHQ is shutting down?

**Comment by wallrj** [comment]
Some of the Flocker developers may be available to provide continuing support and development.
Drop me an email if you have a specific requirement.

**Comment by wallrj** [comment]
@kant111 a band of Flocker developers will be maintaining Flocker here:

 * https://github.com/ScatterHQ
 * https://www.scatterhq.com/

If you need Flocker support and consultancy please contact us.
