### ISSUE TITLE
Some functional tests overwrite /etc/flocker/volume.json

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#301]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-301

Writing out global state in tests is not cool.

Some locations this happens are indicated in the code, but likely not all.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-301. You are welcome to file additional issues in GitHub if that's easier for you.
