### ISSUE TITLE
Set up and document a security contact for the project

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#307]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-307

If folks find security issues with our software, they should be able to find a private channel for communicating it to us easily.  This can be as simple as a `security@clusterhq.com` address which is routed appropriately inside the company and documented somewhere (in the package docs, on the website, etc).

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-307. You are welcome to file additional issues in GitHub if that's easier for you.
