### ISSUE TITLE
flocker.route.INetwork should be a non-blocking API

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#320]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-320

`INetwork` currently describes a blocking API and the `iptables` implementation uses the blocking `subprocess.check_call` function.

If this was a non-blocking API it would be easier to integrate with other non-blocking APIs used in the `flocker.node.Deployer` class.

Raised while working in https://github.com/ClusterHQ/flocker/tree/configure-ports-247 on a fix for #247

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-320. You are welcome to file additional issues in GitHub if that's easier for you.
