### ISSUE TITLE
Move DeployerChangeNodeStateTests tests to DeployerApplyChangesTests

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#321]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-321

Some of the tests in DeployerChangeNodeStateTests are exercising code which has now been refactored into `IStateChange` objects and `calculate_necessary_changes`.

As such, they can be simplified to merely check `calculate_necessary_changes` output.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-321. You are welcome to file additional issues in GitHub if that's easier for you.
