### ISSUE TITLE
Document how RPMs of dependencies are built and updated.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#327]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-327

Most of them are built from spec files in https://github.com/hybridcluster/fedora-packages. SRPMs are built and uploaded to http://data.hybridcluster.net/fedora-scratch/, and then built at https://copr.fedoraproject.org/coprs/tomprince/hybridlogic/

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-327. You are welcome to file additional issues in GitHub if that's easier for you.
