### ISSUE TITLE
Document how to build from source.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#328]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-328

This should cover both git and tarballs (but they are probably the same after unpacking).

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-328. You are welcome to file additional issues in GitHub if that's easier for you.
