### ISSUE TITLE
SSHProcessNodeTests.test_runs_command doesn't demonstrate SSH is involved

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#330]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-330

This test runs `/bin/echo -n hello > /some/absolute/path`.  Then it reads the contents of the path and asserts it contains `b"hello"`.  This will pass whether the node object uses SSH or not (it would work just as well with `sh -c 'command'`).

A fix for this could be to use a relative path and then resolve that relative to the SSH server's "home" directory.  Since that isn't the test process's working directory it's less likely that the contents could get into that file unless SSH is really being used.

Another fix could be to make an assertion about what command the SSH server was instructed to execute.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-330. You are welcome to file additional issues in GitHub if that's easier for you.
