### ISSUE TITLE
`IProcessNode` interface is confusing with respect to shell-syntax command strings vs argument lists

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#331]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-331

Sometimes `IProcessNode` APIs are used by passing them a list like `[program, argv1, argv2, ...]`.  Other times they're used by passing them a list like `[b"program argv1 argv2"]` (and sometimes in the latter case, shell interpretation is assumed - eg `program > filename`).

Only one or the other of these uses is likely to actually work on a given `IProcessNode` provider.  `ProcessNode.using_ssh` will create an object which works with the latter form.  If a program that doesn't imply/insert shell interpretation - like `ssh` or `sh` - is not inserted into the prefix argument list then only the former style will work.

A better interface would make the use (or disuse) of ssh transparent.  The "use a shell" interface is quite wide (you can do a ton of stuff with shells) so it might not be practical to make such an interface, in which case perhaps we should stop pretending that local and remote access are the same kind of thing.

Marking this as a bug because any use of `[b"program argv1 ..."]` will break if you happen to use it against a non-shell-interpreting provider.  This isn't an issue yet but it could become one in the future.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-331. You are welcome to file additional issues in GitHub if that's easier for you.
