### ISSUE TITLE
Format the per-platform tutorial requirements more nicely

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#334]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-334

Requirements vary depending on which OS you're on.  Some platforms definitely already have all of the SSH-related requirements installed, for example.  On others, there's a package of some name that needs to be installed.

Put the details of all of this setup into the tutorial setup document.  Format it so that the user can click on their platform name (or have some javascript detect it woooooooo) and be shown instructions specifically for them.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-334. You are welcome to file additional issues in GitHub if that's easier for you.
