### ISSUE TITLE
Combine all of the tutorial configuration files into a single archive

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#335]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-335

The tutorial has the user download three files now.  It would be nice to offer them a single download that can be unpacked to give them all these dependencies.  Ideally this should be generated automatically as part of the sphinx build process from the `:download:...` directives in the document.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-335. You are welcome to file additional issues in GitHub if that's easier for you.
