### ISSUE TITLE
Automate running examples in tutorial

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#338]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-338

Running examples manually and copy/pasting results has some issues: output will become obsolete as things change, it's not reproducable, etc.. It would be nice to generate this automatically.

One alternative to link into is Dexy, e.g. http://blog.journeythatcounts.nl/posts/living-documentation-with-dexy.html

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-338. You are welcome to file additional issues in GitHub if that's easier for you.
