### ISSUE TITLE
Delete duplicate MutatingProcessNode

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#339]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-339

In #287 (and the PR #299) I forgot to delete `MutatingProcessNode` from `flocker.common.functional.test_ipc`. It's only needed for the `flocker.volume` functional tests.

```
(318)(ssh-quoting-318 ? =)[~/.../HybridLogic/flocker]$ ack 'class MutatingProcessNode'
flocker/volume/functional/test_ipc.py
22:class MutatingProcessNode(ProcessNode):

flocker/common/functional/test_ipc.py
182:class MutatingProcessNode(ProcessNode):
```

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-339. You are welcome to file additional issues in GitHub if that's easier for you.
