### ISSUE TITLE
Volumes' filesystems should be owned by the user which the corresponding container will run as

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#34]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-34

The process running in a container runs as a specific user. E.g. http://docs.docker.io/reference/api/docker_remote_api_v1.11/#22-images - "Inspect an image" API includes user name the image will run under. The filesystem mounter for the container must therefore be writeable by this user.

Our current solution is `chmod 777`, but that's not secure. Better to chown the filesystem to (or maybe tell ZFS about) the appropriate user.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-34. You are welcome to file additional issues in GitHub if that's easier for you.
