### ISSUE TITLE
`flocker-deploy` completes while docker is still downloading images

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#341]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-341

If a deployment requires downloading a docker image (which may be very large) then by the time `flocker-deploy` completes the desired containers may not actually have started up.

They should start eventually but this will only be after an unknown delay to finish downloading the image.

`flocker-deploy` gives no indication that this is what's going on so it gives the appearance of having not worked.

Blocked on:
- [x] #361 Better structured StateChanges object

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-341. You are welcome to file additional issues in GitHub if that's easier for you.
