### ISSUE TITLE
Deployment configuration is required to list all nodes, but it's easy to mistakenly omit one

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#345]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-345

It's easy to mistakenly omit a node from the deployment configuration if it's not running anything (this happened in the first tutorial section, for example).

We can either document that you should at least mention every node or we could have an explicit top-level key in the deployment config whose job is just to enumerate the nodes you want to participate.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-345. You are welcome to file additional issues in GitHub if that's easier for you.
