### ISSUE TITLE
flocker-deploy breaks if number of free threads in thread pool is smaller than number of nodes

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#347]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-347

The current communication method is blocking, therefore uses a thread pool, and requires all connections to happen in parallel. This is not a good combination.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-347. You are welcome to file additional issues in GitHub if that's easier for you.
