### ISSUE TITLE
create FAQ in documents

### ISSUE THREAD

**Issue by ferrantim** [ClusterHQ/flocker#348]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-348

Story: https://www.pivotaltracker.com/story/show/75420734

As we talk to people about Flocker, the same questions are repeatedly coming up so we should have an FAQ that we can point people too.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-348. You are welcome to file additional issues in GitHub if that's easier for you.
