### ISSUE TITLE
Changes in the mountpoint of an existing volume should be applied

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#351]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-351

If the application configuration changes the mountpoint of a volume, this should be reflected in the relevant container.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-351. You are welcome to file additional issues in GitHub if that's easier for you.
