### ISSUE TITLE
Addition or removal of a volume to an existing application should be applied

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#352]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-352

If the application configuration adds or removes a volume from an existing application, these changes should be reflected in the running container (e.g. by restarting it with new configuration).

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-352. You are welcome to file additional issues in GitHub if that's easier for you.
