### ISSUE TITLE
Functional test for volume exposure in orchestration

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#367]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-367

Functional tests are good at catching real world external issues not caught by unit tests. We should write one for exposing a volume to a container in the deployment code path.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-367. You are welcome to file additional issues in GitHub if that's easier for you.
