### ISSUE TITLE
flocker-deploy should provide error handling

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#370]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-370

`flocker-deploy` can fail due to communication problems when talking to the nodes. Right now it's not clear what happened, which node had the issue, etc.. We should provide nice friendly error reporting to help users figure out what's going on.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-370. You are welcome to file additional issues in GitHub if that's easier for you.
