### ISSUE TITLE
flocker-deploy script tests use monkey patching

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#371]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-371

It would be good to avoid monkey patching everywhere. The `effects` library might be useful here, or something like it.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-371. You are welcome to file additional issues in GitHub if that's easier for you.
