### ISSUE TITLE
Read-only access to remotely owned volumes

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#375]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-375

The plan for accessing data that is remotely owned has been to use a "branching" operation (which is effectively free in ZFS) which we're planning on adding in a future release. So you would branch a remotely owned volume and now you have your own local copy you can both read and write to.  However, once you've branched you stop getting updates to this branch.

It would be useful to have a read-only continuously updated access to a remote volume, for e.g. a web server serving files.

One way to do this is just mount the volume read-only. I have observed that mounting in ZFS often seems to actually end up writing some data, and therefore diverging from the origin, even if you haven't written any data to the filesystem. So at that point what you have is no longer a clean replica and further incremental pushes (pending #46) become problematic. We should figure out out why this is (`atime` maybe? any ideas @avg-I ?), and it may be that mounting read-only will fix this.

Alternatively the ZFS clone mechanism could be used to simulate read-only volumes if the mounting-mutates-ZFS-dataset problem is not solvable.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-375. You are welcome to file additional issues in GitHub if that's easier for you.
