### ISSUE TITLE
Persist network configuration (routes) for containers across system reboots

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#38]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-38

Any time we set up a proxy on a port to get traffic routed to the right host so it can arrive at the right container, we need to make sure the proxy is going to be running the next time the system boots.  At least, assuming we want containers to automatically start on the next boot (which is how gear sets them up, so probably).

Current proxying strategy uses iptables rules.  These won't necessarily persist across boots.  Perhaps we should write them to a systemd unit file - or maybe we just need to invoke `iptables-save` (or the systemd unit responsible for this) at the right time.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-38. You are welcome to file additional issues in GitHub if that's easier for you.
