### ISSUE TITLE
Setting new proxies should happen last, not first, in the orchestration process

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#380]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-380

There's no point redirecting traffic if the new application hasn't been setup yet.

OTOH the real way to do it would be to wait until the other nodes are done, lacking that I imagine we might end up with loops...

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-380. You are welcome to file additional issues in GitHub if that's easier for you.
