### ISSUE TITLE
Custom mongodb docker image for tutorial

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#383]
Default one we're using isn't very good:
1. Huge download, slowing down tutorial setup.
2. Requires lots of disk space to run (`mongod` needs to be run with `--noprealloc --smallfiles` to fix this). I have workaround for this in #131 but it isn't great insofar as the resulting image is local only and can't be downloaded outside the vagrant env.

http://blog.docker.com/2013/06/create-light-weight-docker-containers-buildroot/ is a possible technique to try.

**Comment by johnlonganecker** [comment]
So you guys made your own custom mongo images. Is there anyway we can add some other version tags to this image on docker hub?

**Comment by itamarst** [comment]
Hi,

This image is mostly for demo purposes. Any reason you can't use the official image?

**Comment by wayneeseguin** [comment]
@itamarst When we try to run the official docker hub mongo 2.6.7 and 2.6.6 they fail to run when deployed via Flocker so we are looking into what you guys did differently.
