### ISSUE TITLE
If default backend is not virtualbox, vagrant fails to start second node

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#385]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-385

Luke had vmware as default provider, and manually specified virtualbox, but apparently that doesn't affect second one:

https://www.dropbox.com/s/y5q2qu8dorez37e/Screenshot%202014-07-29%2023.27.49.png

Requiring manual selection of virtualbox also is avenue for user failure, so we should see if we can just hardcode it in the `Vagrantfile`.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-385. You are welcome to file additional issues in GitHub if that's easier for you.
