### ISSUE TITLE
Write introduction to ZFS's relevant functionality and benefits

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#386]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-386

ZFS is a lot of why our product is cool; filesystem-level replication etc.. We should really discuss it in the documentation for marketing purposes, but to also to help people understand what we're building on technically. It would be nice to have this in 0.1.

This should probably be done by someone with the relevant expertise, so @avg-I @lukemarsden or Richard Yao.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-386. You are welcome to file additional issues in GitHub if that's easier for you.
