### ISSUE TITLE
Volume change calculation logic does not recalculate local volumes, it relies on passed in current state

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#389]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-389

The passed in current state gathered by `flocker-deploy` is currently what is used to determine the local state of volumes when calculating volume changes. This information may be out of date, in theory. We should use the volume service to figure out local volumes state, not rely on possibly stale information.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-389. You are welcome to file additional issues in GitHub if that's easier for you.
