### ISSUE TITLE
Path to private ssh key (/etc/flocker/id_rsa_flocker) is repeated in both flocker.node and flocker.cli

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#390]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-390

Duplication of config isn't great, we should remove the duplication.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-390. You are welcome to file additional issues in GitHub if that's easier for you.
