### ISSUE TITLE
Make disk available on tutorial vagrant images larger

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#392]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-392

Currently image is 9GB and it's very easy to run out of space, which tends to break everything going forward. Increasing available size won't increase download time so there's no real cost.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-392. You are welcome to file additional issues in GitHub if that's easier for you.
