### ISSUE TITLE
flocker-changestate should log current known state, desired state and calculated changes

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#393]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-393

In combination with #423 which will print logs to stderr we gain both useful debugging info and the user gets some sense of what's going on.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-393. You are welcome to file additional issues in GitHub if that's easier for you.
