### ISSUE TITLE
Run flake8 on admin scripts

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#397]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-397

eg https://github.com/ClusterHQ/flocker/blob/release-process-292/admin/upload-rpms

See https://github.com/ClusterHQ/flocker/pull/293/files#r15531224

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-397. You are welcome to file additional issues in GitHub if that's easier for you.
