### ISSUE TITLE
Document how to update the clusterhq-release package

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#398]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-398

I removed this section from the release-process-292 branch because the spec file seemed to be missing and it wasn't clear that it was necessary for the first release.

See https://github.com/ClusterHQ/flocker/pull/293/files#r15635783

```
clusterhq-release package
~~~~~~~~~~~~~~~~~~~~~~~~~

This is a meta-package that contains the yum repository definitions.

::

   rpmbuild --define="_sourcedir ${PWD}" --define="_rpmdir ${PWD}/results" -ba clusterhq-release.spec
   gsutil cp -a public-read results/noarch/clusterhq-release-1-1.fc20.noarch.rpm gs://archive.clusterhq.com/fedora/clusterhq-release.fc20.noarch.rpm

```

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-398. You are welcome to file additional issues in GitHub if that's easier for you.
