### ISSUE TITLE
Find a better test for a running ssh-agent in tutorial/vagrant-setup

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#414]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-414

Contrary to what the tutorial says, when agent is running you're quite likely to get a prompt for your private key password.

```
$ ssh-add
Enter passphrase for /home/richard/.ssh/id_rsa: 
```

`ssh-add -l` might be a better test.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-414. You are welcome to file additional issues in GitHub if that's easier for you.
