### ISSUE TITLE
Document debugging tools

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#425]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-425

There are a variety of ways to figure out what went wrong. We should document them. They include:

* `zfs list`
* `docker ps -a`
* `docker images`
* `/var/log/flocker`
* ~~`gear list-units -a`~~
* Running `flocker-reportstate` directly.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-425. You are welcome to file additional issues in GitHub if that's easier for you.
