### ISSUE TITLE
Documented method for setting the PATH may cause confusion

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#447]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-447

The installation suggests this method of setting the `PATH`

`export PATH="${PATH:+${PATH}:}${PWD}/bin"`

But that caused me some confusion until I found the relevant section in the Bash man page.

```
${parameter:+word}
              Use Alternate Value.  If parameter is null or unset, nothing is substituted,  otherwise
              the expansion of word is substituted.
```

I think it would be simpler, and more compatible with non-Bash shells, if we simply suggest:

`export "PATH=${PWD}/bin:${PATH}"`

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-447. You are welcome to file additional issues in GitHub if that's easier for you.
