### ISSUE TITLE
Support more than one volume for a container

### ISSUE THREAD

**Issue by robhaswell** [ClusterHQ/flocker#49]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-49

Our current implementation has a 1:1 mapping between containers and volumes:

> For example, for a container named "myapp-mongodb" a volume called "myapp-mongodb" will be created.

It's likely that users will want the ability to mount multiple volumes within their containers.  Each volume would need a different mountpoint. Flocker should have syntax and support for this.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-49. You are welcome to file additional issues in GitHub if that's easier for you.

**Comment by ianwalter** [comment]
+1 for this.
I have 2 volumes for my Nginx container. One for configuration and one for public static assets that need to be served.

**Comment by itamarst** [comment]
Thanks for the feedback, @ianwalter. We're currently working towards a much more flexible configuration model which will allow fixing this and other related issues.
