### ISSUE TITLE
Remove bullets for TOC sidebar

### ISSUE THREAD

**Issue by ferrantim** [ClusterHQ/flocker#504]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-504

The bullets in the TOC sidebar are a little much given the number of nests and the number of items we have.  We can achieve the same effect of clearly delineating the nested lists with fonts.

See http://documentation.mailgun.com/ as an example. 

This is not a blocker for the 0.1 release.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-504. You are welcome to file additional issues in GitHub if that's easier for you.
