### ISSUE TITLE
Post-0.1, pre-releases should *not* be uploaded to the canonical RPM repository

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#506]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-506

Our tutorial `Vagrantfile` (and any users who are installing the Flocker RPMs manually) download RPMs from the canonical repository. We should therefore not upload pre-releases there, only stable releases.

Blocked on:
- [ ] #662 A mechanism for building RPMs with pre-release version numbers

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-506. You are welcome to file additional issues in GitHub if that's easier for you.
