### ISSUE TITLE
Document or automate the generation of a NEWS file at release

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#523]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-523

We might use something like Newsbuilder or we might simply document a process for selecting suitable entries for the NEWS file at release time.

See:
 * https://github.com/ClusterHQ/flocker/pull/489#issuecomment-51586269
 * https://github.com/twisted/newsbuilder
 * https://twistedmatrix.com/trac/wiki/ReviewProcess#Newsfiles

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-523. You are welcome to file additional issues in GitHub if that's easier for you.
