### ISSUE TITLE
Determine download statistics

### ISSUE THREAD

**Issue by robhaswell** [ClusterHQ/flocker#541]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-541

We need to be able to report on download statistics for the `flocker-cli` package. These can be determined by processing the logs located on Google Cloud Storage:

https://console.developers.google.com/project/apps~hybridcluster-docker/storage/archive_access_logs/?authuser=1

Downloads appear as a GET operation:

```
"1407519997224000","108.49.162.79","1","","GET","/archive.clusterhq.com/fedora/20/x86_64/flocker-cli-0.0.6-1.fc20.noarch.rpm","200","0","5143","101000","storage.googleapis.com","","urlgrabber/3.10.1 yum/3.4.3,gzip(gfe)","AEnB2UoNSvw1slrVLI4xJzCrnxmOCjBh4wTK_up-LLflBmheu8_akn2sAS0ukA1N2P4_D9FDfMQw2nSV1Kic7RTVYrJep9Ai9w","GET_Object","archive.clusterhq.com","fedora/20/x86_64/flocker-cli-0.0.6-1.fc20.noarch.rpm"
```

Write a small tool which can be used to count the occurrences of these lines. This will be used internally only.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-541. You are welcome to file additional issues in GitHub if that's easier for you.
