### ISSUE TITLE
Deleting a volume should delete all remote instances of that volume

### ISSUE THREAD

**Issue by robhaswell** [ClusterHQ/flocker#55]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-55

Remote copies of volumes should aim to track the masters - so that if the master is deleted all remote copies are deleted as well. This would avoid confusing conflicts when a volume is deleted and created again with the same name.

To protect against the scenario that a local node has been compromised by an attacker, remote volume destruction could take the form of renaming the filesystem into the trash. This is the approach taken in HybridCluster.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-55. You are welcome to file additional issues in GitHub if that's easier for you.
