### ISSUE TITLE
Mark all Flocker-created iptables rules with a comment

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#56]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-56

Forwarding a port involves creating three iptables rules.  One of these gets a comment reflecting that Flocker created it.  The other two should as well.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-56. You are welcome to file additional issues in GitHub if that's easier for you.
