### ISSUE TITLE
Figure out how we can update documentation without doing release

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#561]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-561

Currently documentation updates require a new release. This is not ideal.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-561. You are welcome to file additional issues in GitHub if that's easier for you.
