### ISSUE TITLE
Automate testing of documentation (tutorial, etc.)

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#577]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-577

We shoudl be able to automatically test installation of client, vagrant setup etc. from a release  - basically running through the tutorial.

Possibly we only have to do whole thing on one platform, and on others just ensure the client gets installed OK.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-577. You are welcome to file additional issues in GitHub if that's easier for you.
