### ISSUE TITLE
Public routes configured via iptables won't survive reboots

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#581]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-581

We're not recreating routes on startup.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-581. You are welcome to file additional issues in GitHub if that's easier for you.
