### ISSUE TITLE
Expand `IStoragePool.create` to document expected error results

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#59]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-59

Some errors (e.g. creating already-existing filesystem) are pretty standard and should be explicitly exposed and documented.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-59. You are welcome to file additional issues in GitHub if that's easier for you.
