### ISSUE TITLE
Update release process to explain how to do pre-releases

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#599]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-599

E.g.:

* Version numbers should be "0.2.0pre1".
* #506 - pre-releases should not go into production repository.

Blocked on:
- [x] #662 A mechanism for building RPMs with pre-release version numbers

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-599. You are welcome to file additional issues in GitHub if that's easier for you.
