### ISSUE TITLE
flocker.node.functional.test_script.ReportStateScripts is... empty

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#601]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-601

Either this shouldn't exist or we're missing tests, not sure which.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-601. You are welcome to file additional issues in GitHub if that's easier for you.
