### ISSUE TITLE
documentation depends on non-local resources not tracked in the repository

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#603]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-603

The theme links to the image `//clusterhq.com/wp-content/themes/hybrid-cluster-v3/assets/img/hc-logo.png`.

The favicon is also referenced at `//clusterhq.com/wp-content/themes/hybrid-cluster-v3/assets/img/favicon.ico`.

When building and viewing documentation locally these references can't be resolved.  Additionally, since they're not part of the repository, they can't easily be changed.

The cases where some part of the documentation should live outside of the repository will be few and far between.  Neither of these images seems like a case where it makes sense.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-603. You are welcome to file additional issues in GitHub if that's easier for you.
