### ISSUE TITLE
Flocker fails with SELinux problems on standard Fedora servers

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#619]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-619

Try to use flocker-node on a Fedora host with SELinux enabled and you'll encounter the errors described on <https://github.com/ClusterHQ/flocker/pull/532#issuecomment-51805815>.

The Vagrant image avoids this problem by disabling SELinux entirely.

We'll need to figure something out before it will be practical to use Flocker in production.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-619. You are welcome to file additional issues in GitHub if that's easier for you.
