### ISSUE TITLE
Support IPv6 routing

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#62]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-62

Any and every public API in `flocker.route` that accepts an IPv4 address should be made to work if it is called with an IPv6 address instead.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-62. You are welcome to file additional issues in GitHub if that's easier for you.
