### ISSUE TITLE
StoragePool.startService repeatedly sets storage pool properties

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#635]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-635

Because we don't have any code that runs exactly at pool creation time, we have no good place to put one-off configuration tasks like "set the readonly property".  So we're doing that every time we start a `StoragePool` now, in `flocker/volume/filesystems/zfs.py`.

It would be simpler and better if we could do these things just once.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-635. You are welcome to file additional issues in GitHub if that's easier for you.
