### ISSUE TITLE
Deal with pyyaml's mixed use of `bytes` and `str`.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#636]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-636

Depending on whether a value has non-ascii characters, it will return either `bytes` or `unicode`, for string values. We don't want to deal with that ambiguity, so we should post-process the output of `yaml.safe_load` to normalize strings.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-636. You are welcome to file additional issues in GitHub if that's easier for you.
