### ISSUE TITLE
The instructions for pre-populating RPM Repository wipes out links to our RPMs.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#637]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-637

Since we don't download the files already in the repository, only the RPMs used to repopulate the repository are in the repo-data. Since we have releases there now, the instructions should be changed so that the data is updated, rather than overwritten.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-637. You are welcome to file additional issues in GitHub if that's easier for you.
