### ISSUE TITLE
Steam line callout boxes in docs

### ISSUE THREAD

**Issue by ferrantim** [ClusterHQ/flocker#666]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-666

We use callout boxes in docs to call attention to important instructions when regularly formatted text is not sufficient. We have these callouts inconsistently spaced throughout the docs, and sometimes use a word like "note" or "warning" at the beginning of the callout, and other times we don't.  Since the callout box itself draws the users attention, we should remove these words.

![image](https://cloud.githubusercontent.com/assets/3068350/4162747/0adc34a4-34df-11e4-8fdf-315a6685d594.png)

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-666. You are welcome to file additional issues in GitHub if that's easier for you.
