### ISSUE TITLE
Switch to a structured representation of snapshots

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#668]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-668

Currently flocker.volume.filesystems.zfs.Snapshot has a unicode name.  If we're going to have structured encoded in snapshot names then the structure should be represented in the Python representation of the snapshot name.  First we need to decide what that structure should be, though. It's not yet obvious these are the pieces of information Flocker wants to associate with each snapshot.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-668. You are welcome to file additional issues in GitHub if that's easier for you.
