### ISSUE TITLE
Guard against concurrent deployment attempts

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#670]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-670

If a user runs `flocker-deploy` and it is interrupted somehow - network error, programming error, or malicious user action (eg Ctrl-C) - but the nodes themselves continue make progress towards the intended deployment, the situation should not be made worse if the user re-runs `flocker-deploy`.

For example, perhaps `flocker-changestate` and `flocker-reportstate` should acquire and respect a lock before taking any action.  Or, once we replace CLI-over-SSH with an API, the implementation of the API can serialize actions somehow.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-670. You are welcome to file additional issues in GitHub if that's easier for you.
