### ISSUE TITLE
The instructions for the release process comingle getting an environment setup to do a release, and actually doing the release

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#672]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-672

There are things like setting up gsutil, and a virtualenv, that only need to be done once. And then there are the steps to actually do the release. They are currently mixed together, and should be seperated.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-672. You are welcome to file additional issues in GitHub if that's easier for you.
