### ISSUE TITLE
ZFS filesystem manually sets up the mountpoint

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#679]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-679

In tests, the mountpoint for the ZFS pool is one path, and then the volume layer sets a different one. This is reflected in actual code which presumes it needs to manually set the mountpoint for each dataset it creates. In real environment there's only one mountpoint (`/flocker`).

It's rather silly to have two different mountpoints for the ZFS pool in general and for the datasets the volume manager is creating within that pool. We can simplify the code by removing this "feature".

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-679. You are welcome to file additional issues in GitHub if that's easier for you.
