### ISSUE TITLE
Flocker purge state tool

### ISSUE THREAD

**Issue by dwgebler** [ClusterHQ/flocker#682]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-682

Flocker does not currently have a way to purge state from deployment nodes, i.e. removing gear units, ZFS volumes and Docker containers. We are currently documenting the manual workaround for this. As `flocker-deploy` is the only user-facing portion of the software at the moment, we may wish to add a command line option or `deployment.yml` config to accomplish these cleanup tasks.

One such example in `deployment.yml` might be a "purge" option, e.g.

```
"version": 1
"action": "purge"
"nodes":
  "172.16.255.251": []
  "172.16.255.250": ["wordpress","mysql"]
```

could have the effect of removing the containers, volumes and units associated with the applications `wordpress` and `mysql` on the target node.

Or alternative options for exposing this functionality to the user can be considered.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-682. You are welcome to file additional issues in GitHub if that's easier for you.
