### ISSUE TITLE
Applications are stopped for far too long in some cases

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#685]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-685

Node 1 has application `A` with volume `Va`. Node 2 has application `B`. If we swap the applications between the nodes `B` will be shutdown immediately, even though it's going to be awhile before node 1 starts any applications as it first needs to copy all the data in `Va`.

One solution is to wait until all data has been pushed on all nodes before stopping anything. Another solution is to parallelize things better: node 1 should realize it can start application `B` while it is still pushing volume `Va`. Then the fact that node 2 has shutdown `B` immediately is not a problem.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-685. You are welcome to file additional issues in GitHub if that's easier for you.
