### ISSUE TITLE
Warning boxes in docs should all be the same color

### ISSUE THREAD

**Issue by ferrantim** [ClusterHQ/flocker#690]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-690

We have 2 different color schemes for warnings, red and yellowish.  One box is coded as a note, and one is codes as a warning. We should standardize on the yellow-ish warning style which is the most common in our docs.

![image](https://cloud.githubusercontent.com/assets/3068350/4203792/f9ddffb0-3831-11e4-89ae-2dceeb8cac8a.png)

![image](https://cloud.githubusercontent.com/assets/3068350/4203806/1575e968-3832-11e4-9adb-0e62006fd15e.png)

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-690. You are welcome to file additional issues in GitHub if that's easier for you.
