### ISSUE TITLE
Remove Python documentation intersphinx config

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#695]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-695

Building docs does this:

```
loading intersphinx inventory from http://docs.python.org/objects.inv...
```

We are unlikely to need to link to Python documentation, and this means:
1. We need network access to build docs locally.
2. Building docs is often slowed down.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-695. You are welcome to file additional issues in GitHub if that's easier for you.
