### ISSUE TITLE
New volume configuration model with first class volumes

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#697]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-697

The current volume configuration model suffers from the lack of first-class volumes:
* If somehow a volume exists on a node but a corresponding application doesn't, `flocker-volume` will not realize the volume exists, will try to recreate it and then fail.
* Multiple volumes are not supported.
* It's not possible to move a volume from one application to another.

New config proposal TBD, I suspect it will be somewhat influenced by the 0.3 data management use case, and that this issue will be required for that to happen.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-697. You are welcome to file additional issues in GitHub if that's easier for you.
