### ISSUE TITLE
test suite leaks ssh-agent processes

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#698]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-698

The test suite starts ssh-agent in order to facilitate some functional testing.  Somehow it fails to clean these up and they remain running even after the test suite has completed.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-698. You are welcome to file additional issues in GitHub if that's easier for you.
