### ISSUE TITLE
Benchmark the volume push API

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#70]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-70

People will enjoy Flocker more if it completes the requested operations quickly.  Shoveling ZFS snapshot data streams between storage pools is one operation Flocker will be executing (and somewhat frequently).  It would be beneficial for this to be as fast as possible.

Measure how fast it is as a first step towards making sure it is and stays as fast as possible.

It's likely not possible to transfer the snapshot data at a rate greater than the lesser of either the disks holding the storage pools (or perhaps half that if the storage pools share disks as might be the case for a "loopback" benchmark) or the network connecting two hosts between which the transfer is occurring.  If the benchmark reveals we're not close to that  - say, within 20% - then we should consider doing some optimization work

See #69 for an earlier version of this issue.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-70. You are welcome to file additional issues in GitHub if that's easier for you.
