### ISSUE TITLE
Link directly to archive.clusterhq.com rather than storage.googleapis.com

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#701]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-701

We have various links to https://storage.googleapis.com/archive.clusterhq.com/ which could be replaced with shorter and more consistent  https://archive.clusterhq.com

```
[~/.../HybridLogic/flocker]$ ack 'storage.googleapis.com'
docs/gettingstarted/tutorial/Vagrantfile
18:yum localinstall -y https://storage.googleapis.com/archive.clusterhq.com/fedora/clusterhq-release$(rpm -E %dist).noarch.rpm
23:yum install -y https://storage.googleapis.com/archive.clusterhq.com/fedora/20/x86_64/python-flocker-0.1.2-1.fc20.noarch.rpm https://storage.googleapis.com/archive.clusterhq.com/fedora/20/x86_64/flocker-node-0.1.2-1.fc20.noarch.rpm

docs/gettingstarted/linux-install.sh
14:flocker-tutorial/bin/pip install --quiet https://storage.googleapis.com/archive.clusterhq.com/downloads/flocker/Flocker-0.1.2-py2-none-any.whl
```

But I don't think Google Cloud Storage allows us to upload a custom certificate.

So if we want to use TLS links we could set up archive.clusterhq.com on cloudflare...with Google Cloud Storage as the backend.

But that might affect our download statistics (#541) unless we can disable cloudflare caching.

Perhaps there are other options.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-701. You are welcome to file additional issues in GitHub if that's easier for you.
