### ISSUE TITLE
Allow environment variables to be specified outside the application config.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#706]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-706

Environment variables often contain sensitive data, where as other environment variables and the rest of the configuration isn't. For example https://github.com/ClusterHQ/build.clusterhq.com has passwords to various services in the environment. It should be possible to store the sensitive information separately from the rest of the configuration.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-706. You are welcome to file additional issues in GitHub if that's easier for you.
