### ISSUE TITLE
Sign release artifacts

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#707]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-707

It should be possible for users to install the software we distribute without being vulnerable to attacks that might replace our software with someone else's.  The RPM toolchain supports GPG package signatures.  We should take advantage of this.

- [ ] Generate, safely maintain, and publicize the public part of a package signing key (probably signed by a company master key)
- [ ] Sign RPMs with it - All of the Python dependencies, the flocker-node rpm (Adjust the release process to include package signing)
- [ ] Re-enable GPG checks in the clusterhq-repository configuration

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-707. You are welcome to file additional issues in GitHub if that's easier for you.
