### ISSUE TITLE
Provide a Vagrant configuration for developing/testing against HEAD of dependencies

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#714]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-714

We provide a Vagrantfile that easily provides a VirtualBox VM with all of Flocker's dependencies installed on it already.  This makes for easier development and testing setup - particularly since one of our dependencies is a third-party kernel module.

We should have another one of these that tracks **future** versions of our dependencies so we can keep track of what's coming down the pipeline from other projects Flocker interacts with.

For example, this would be handy for testing out the recent ZFS deadlock issue we ran into and which should now be fixed upstream (but is not yet part of any release).

This should go along with some continuous integration configuration to automatically test against new versions of dependencies - but I'll file a separate ticket for that.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-714. You are welcome to file additional issues in GitHub if that's easier for you.
