### ISSUE TITLE
Inconsistent spell check results

### ISSUE THREAD

**Issue by msh100** [ClusterHQ/flocker#717]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-717

I believe that the bundled dictionary files with Enchant (or maybe the OS) are inconsistent. With the latest version of master I get spelling errors.

```
faq/index.rst:30:petabytes:q/index
faq/index.rst:65:app:
faq/index.rst:65:app:
faq/index.rst:65:app:
faq/index.rst:68:apps:
gettingstarted/mysql-example.rst:38:internet:-example
index.rst:4:app:. [ 90%] index
introduction.rst:7:app:] introduction
introduction.rst:7:apps:
introduction.rst:111:admin:
introduction.rst:160:sysadmin:
```

These do not fail on buildbot or @adamtheturtle's computer (we have matching versions of Enchant).

When testing with Enchant directly, Enchant believed that "app" was a spelling error when I use the `en_US` dictionary however the `en_GB` dictionary was fine. Therefore we added the line to `docs/conf.py`:

```
spelling_lang = 'en_GB'
```

However this then raised US spelling errors (such as words ending in 'ize'). http://sphinxcontrib-spelling.readthedocs.org/en/latest/customize.html?highlight=dictionary#input-options suggests that the language is by default `en_US`, and this does appear to be the case however we do not have the same `en_US` dictionaries on our hosts. Maybe we should bundle one or refer to one we know is consistent across hosts.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-717. You are welcome to file additional issues in GitHub if that's easier for you.
