### ISSUE TITLE
Switch DockerClient to use a custom thread pool instead of the global thread pool

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#718]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-718

This will probably involve making it a service so we can start/stop the thread pool.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-718. You are welcome to file additional issues in GitHub if that's easier for you.
