### ISSUE TITLE
Replace slow-shutdown docker image with one that uses Python instead of shell scripting

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#719]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-719

Shell scripting is terrible, we should avoid it.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-719. You are welcome to file additional issues in GitHub if that's easier for you.
