### ISSUE TITLE
Upgrade to newer version of Docker

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#721]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-721

Among other improvements newer versions have better API error reporting (see references to this issue in `flocker/node/_docker.py`).

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-721. You are welcome to file additional issues in GitHub if that's easier for you.
