### ISSUE TITLE
Internal links should be internal

### ISSUE THREAD

**Issue by robhaswell** [ClusterHQ/flocker#725]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-725

Currently, internal links expose a public port. Users may not want their internal services to be publicly exposed.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-725. You are welcome to file additional issues in GitHub if that's easier for you.
