### ISSUE TITLE
Encrypt traffic between datacentres

### ISSUE THREAD

**Issue by robhaswell** [ClusterHQ/flocker#726]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-726

Traffic traversing our routing layer over the Internet should be encrypted.

Weave may be useful for this: https://github.com/zettio/weave/

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-726. You are welcome to file additional issues in GitHub if that's easier for you.
