### ISSUE TITLE
Restart failed containers, perhaps based on user-specified policy

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#727]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-727

We should use/expose Docker's auto-restart policy feature.

Two parts:
* Load from deployment config.
* Expose feature in `IDockerClient`.

This will require docker-py 0.5.0, which will be easier to do if we do #508 first.

Depends on:
- [x] #608 rip out geard.
- [ ] #721 Newer Docker version.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-727. You are welcome to file additional issues in GitHub if that's easier for you.
