### ISSUE TITLE
Expose Docker's memory and CPU quotas feature

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#728]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-728

Two parts:
* Load from deployment config.
* Expose feature in `IDockerClient`.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-728. You are welcome to file additional issues in GitHub if that's easier for you.
