### ISSUE TITLE
Python bindings for libzfs_core

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#731]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-731

Currently we call `zfs` command line tool directly. This is not good.

This is the overall issue for the low-level bindings; it will presumably be split up into sub-issues for more reasonable chunks of work.

* We want CFFI based bindings.
* Good error handling.
* Logging of what is going on (via Eliot).
* Separate package so we can spin this off into separate project (`pylibzfs_core`).
* Validation that using `zfs` command line tool has same effects as `pylibzfs_core`.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-731. You are welcome to file additional issues in GitHub if that's easier for you.
