### ISSUE TITLE
Switch `flocker.volumes.zfs` to use pylibzfs_core bindings

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#732]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-732

Blocked on:
- [ ] #731 Bindings!

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-732. You are welcome to file additional issues in GitHub if that's easier for you.
