### ISSUE TITLE
Tutorial: cloning with custom images and links

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#736]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-736

This the second step of the tutorial demonstrating how to clone an environment.

Basic narrative:
1. We have a database. Database has some data in it.
2. We have web application linked to database, with some version of code.
3. We want to test new version of code with production data.
2. We clone, overriding web application with new image that has new code.
3. New web application is linked to new database, which is copy of old database.

Blocked on:
- [ ] #735 Custom images when cloning

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-736. You are welcome to file additional issues in GitHub if that's easier for you.
