### ISSUE TITLE
Expose quotas in the volume and filesystem levels

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#740]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-740

1. Volumes can be created with a quota.
2. `IStoragePool` allows creating a filesystem with a quota.
2. `IFilesystem` has a way to get and set the quota.

On ZFS this should use `refquota`.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-740. You are welcome to file additional issues in GitHub if that's easier for you.
