### ISSUE TITLE
User-facing tool to cleanup unused volumes in the cluster

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#742]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-742

Users should be able to delete all volumes on the cluster that are not being used for anything.

Blocked on:
- [ ] #14 Deleting a volume

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-742. You are welcome to file additional issues in GitHub if that's easier for you.
