### ISSUE TITLE
Delete push-related snapshots from ZFS volumes

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#75]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-75

Every time a push is done a new snapshot is created. These snapshots prevent old data from being removed, and the only really useful one to keep is the latest one that the push destination has (to allow doing partial pushes). Older snapshots should therefore be deleted at some point.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-75. You are welcome to file additional issues in GitHub if that's easier for you.
