### ISSUE TITLE
Support Fig directive: build

### ISSUE THREAD

**Issue by dwgebler** [ClusterHQ/flocker#751]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-751

Flocker does not support the fig build directive, used to specify a path to a Dockerfile and build that image, instead of using an existing image, for the deployment of an application.

http://www.fig.sh/yml.html

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-751. You are welcome to file additional issues in GitHub if that's easier for you.
