### ISSUE TITLE
Support Fig directive: command

### ISSUE THREAD

**Issue by dwgebler** [ClusterHQ/flocker#752]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-752

Flocker does not support the fig command directive, used to specify a command to run when launching an application, overriding any default command.

http://www.fig.sh/yml.html

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-752. You are welcome to file additional issues in GitHub if that's easier for you.
