### ISSUE TITLE
Support Fig directive: expose

### ISSUE THREAD

**Issue by dwgebler** [ClusterHQ/flocker#753]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-753

Flocker does not support the fig expose directive, used to expose ports internally in a container without publishing those ports to host.

http://www.fig.sh/yml.html

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-753. You are welcome to file additional issues in GitHub if that's easier for you.
