### ISSUE TITLE
Support Fig directive: volumes_from

### ISSUE THREAD

**Issue by dwgebler** [ClusterHQ/flocker#754]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-754

Flocker does not support the fig volumes_from directive, used to mount volumes from another service or container.

http://www.fig.sh/yml.html

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-754. You are welcome to file additional issues in GitHub if that's easier for you.
