### ISSUE TITLE
Support Fig directive: net

### ISSUE THREAD

**Issue by dwgebler** [ClusterHQ/flocker#755]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-755

Flocker does not support the fig net directive, used to specify networking mode in the same manner as the Docker client `--net` parameter.

http://www.fig.sh/yml.html

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-755. You are welcome to file additional issues in GitHub if that's easier for you.
