### ISSUE TITLE
Support Fig directive: dns

### ISSUE THREAD

**Issue by dwgebler** [ClusterHQ/flocker#756]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-756

Flocker does not support the fig dns directive, used to specify custom DNS servers in a container..

http://www.fig.sh/yml.html

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-756. You are welcome to file additional issues in GitHub if that's easier for you.
