### ISSUE TITLE
Flocker does not support user fig directive

### ISSUE THREAD

**Issue by dwgebler** [ClusterHQ/flocker#765]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-765

Flocker does not support the Fig `user` directive, a single value acting on a container in the same manner as its `docker run` counterpart.

http://www.fig.sh/yml.html

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-765. You are welcome to file additional issues in GitHub if that's easier for you.
