### ISSUE TITLE
External port should be able to be assigned automatically if excluded from configuration

### ISSUE THREAD

**Issue by dwgebler** [ClusterHQ/flocker#768]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-768

See https://github.com/ClusterHQ/flocker/pull/748#issuecomment-56366221

Fig-style configuration supports specifying `ports` without a host mapping to the port exposed in the container. It should be possible for Flocker to randomly choose a high range port number and assign it as the external (host) port mapped to the internal port, in the same manner as Docker's vanilla command-line behaviour, such that Fig-style `ports` can be properly supported.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-768. You are welcome to file additional issues in GitHub if that's easier for you.
