### ISSUE TITLE
Expose normal Docker from-root-filesystem volumes

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#773]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-773

We need to support standard Docker volume mounting.

For example, there's an idiom where you expose Docker control socket to a container:

```
<lnguyen> im trying to use https://github.com/progrium/registrator which has docker image that need -v /var/run/docker.sock:/tmp/docker.sock
```

Our volume manager is irrelevant to this use case.

Blocked on:
- [ ] #234 Better volume mounting API

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-773. You are welcome to file additional issues in GitHub if that's easier for you.
