### ISSUE TITLE
expose functionality equivalent to `zfs destroy -r dataset`

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#775]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-775

#14 and #55 depend on being able to destroy filesystems and all their snapshots.

Expose the libzfs_core functionality for doing so.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-775. You are welcome to file additional issues in GitHub if that's easier for you.
