### ISSUE TITLE
expose functionality equivalent to `zfs snapshot dataset@label`

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#776]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-776

The volume manager needs to be able to take snapshots in order to construct data streams for transfer between nodes.

It currently does this by running `zfs snapshot fs@uuid` as a child process.

Expose the libzfs_core functionality for doing this.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-776. You are welcome to file additional issues in GitHub if that's easier for you.
