### ISSUE TITLE
expose functionality equivalent to `zfs list -r -t snapshot -o name -s creation filesystem_name`

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#777]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-777

The volume managers on two nodes communicate with each other to determine a shared snapshot to use as the basis of an incremental data stream.  To do this, they need to be able to list the snapshots of the filesystem in question that exist in their own storage pool.  They need to know the names of the snapshots in order to refer to them in a later `zfs send` operation and they need to order the snapshots by creation time in order to pick the newest one to minimize the size of the data stream.

Expose libzfs_core functionality for accomplishing this.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-777. You are welcome to file additional issues in GitHub if that's easier for you.
