### ISSUE TITLE
expose functionality equivalent to `zfs list filesystem_name`

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#778]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-778

The volume manager needs to be able to determine the existence (or non-existence) of a filesystem of a particular name in its local storage pool.  It does this as part of the negotiation process with another node to determine if replicating the filesystem from one node to another requires a full data stream or if an incremental data stream can be constructed.

The implementation uses `zfs list` because that's an obvious way to use the command line tool to check if a filesystem exists.  If there's a better API for determining this that happens to have nothing to do with `zfs list`, that would be a fine resolution to this issue.

Expose libzfs_core functionality to accomplish this.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-778. You are welcome to file additional issues in GitHub if that's easier for you.
