### ISSUE TITLE
expose functionality equivalent to `zfs send filesystem_name@snapshot_name`

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#779]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-779

The initial step of the replication process employed by the volume manager is to do a `zfs send` of an entire filesystem up to a (very recently taken) snapshot.  This is necessary when the receiving volume manager knows nothing at all about the filesystem yet.  The snapshot is required so that future sends can be incremental.

Expose libzfs_core functionality equivalent to this.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-779. You are welcome to file additional issues in GitHub if that's easier for you.
