### ISSUE TITLE
expose functionality equivalent to `zfs send -i filesystem_name@first_snapshot second_snapshot`

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#780]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-780

After an initial "full" send, the volume manager performs incremental sends to continue to replicate filesystems across nodes.  It takes care to construct incremental sends which start at a snapshot that the two nodes share.

Expose libzfs_core functionality equivalent to this.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-780. You are welcome to file additional issues in GitHub if that's easier for you.
