### ISSUE TITLE
expose functionality equivalent to `zfs receive filesystem_name`

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#781]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-781

The volume manager uses this functionality on the receiving side of the replication process described in #779.

Expose libzfs_core functionality equivalent to this.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-781. You are welcome to file additional issues in GitHub if that's easier for you.
