### ISSUE TITLE
expose functionality equivalent to `zfs receive -F filesystem_name`

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#782]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-782

The volume manager uses this functionality on the receiving side of the replication process described in #780.

The "force" behavior is necessary in case the incremental data stream must be based on a snapshot that is not the absolute latest snapshot on the receiving side.  If libzfs_core doesn't expose this utility directly (for example, perhaps it requires you to explicitly destroy extra snapshots before performing the receive operation) that's fine too as long as whatever other steps are necessary to accomplish this task are also exposed.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-782. You are welcome to file additional issues in GitHub if that's easier for you.
