### ISSUE TITLE
expose functionality equivalent to `zfs set property=value filesystem_name`

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#783]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-783

The volume manager manipulates several properties of filesystems.

  * It sets the `readonly` property (sometimes to on, sometimes to off) to help avoid having the "slave" version of any filesystem diverge from the "master" version.
  * It sets the `mountpoint` property so the filesystem is available to be exposed to Docker containers.
  * It sets the `canmount` property to off (on the root dataset only) to avoid problematic interactions between readonly and mounting

Expose libzfs_core functionality sufficient to accomplish this.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-783. You are welcome to file additional issues in GitHub if that's easier for you.
