### ISSUE TITLE
expose functionality equivalent to `zfs inherit readonly filesystem_name`

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#784]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-784

The volume manager sometimes wants to clear the `readonly` property from a filesystem and let it inherit the value from its parent.  For our purposes, this is mostly equivalent to just setting the readonly property to the desired value (we know what value will be inherited).  However, this would still result in some filesystems inheriting readonly=on and some filesystems having readonly=on explicitly set on them.  `zfs inherit` is used to make the filesystems all consistent in this regard.

Expose libzfs_core functionality equivalent to this.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-784. You are welcome to file additional issues in GitHub if that's easier for you.
