### ISSUE TITLE
expose functionality equivalent to `zfs rename filesystem_old_name filesystem_new_name`

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#785]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-785

The volume manager encodes certain information in the names of filesystems.  It uses information in the name to reflect which volume manager is the "master" for that filesystem, for example.  The master can change, requiring the filesystem to be renamed.

Expose libzfs_core functionality equivalent to this.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-785. You are welcome to file additional issues in GitHub if that's easier for you.
