### ISSUE TITLE
Flocker does not support full range of Fig ports directive cases

### ISSUE THREAD

**Issue by dwgebler** [ClusterHQ/flocker#786]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-786

See #649 and #748 

Flocker does not have the ability to randomly assign an available port number in the high range 49153 to 65535 on a container's host, analogous to the `docker run -P` directive.

This means the current Fig compatibility layer can only handle ports specified in `host:container` format, whereas Fig can support the full Docker range, i.e. we're missing support for just the container port specified, or a host IP and port before the container port (`ip:hostPort:containerPort` format).

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-786. You are welcome to file additional issues in GitHub if that's easier for you.
