### ISSUE TITLE
expose functionality equivalent to `zfs clone`

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#787]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-787

The "lightweight cloning" feature (#733) depends on being able to create a cheap, writeable copy of an existing zfs filesystem.  The plan is to implement this with ZFS clones.

Expose libzfs_core functionality equivalent to `zfs clone existingfs@snapshot newfs`.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-787. You are welcome to file additional issues in GitHub if that's easier for you.
