### ISSUE TITLE
expose functionality equivalent to `zfs promote filesystem_name`

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#788]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-788

A likely future direction to go with the "lightweight cloning" (#733) functionality will be to turn a cloned environment into the canonical environment, destroying the no-longer needed/used original volumes which were cloned.  This will mean inverting the parent/child relationship between the snapshot which was cloned and the filesystem which was created by that clone operation.  Without doing this, the snapshot (and thus the original filesystem) cannot be destroyed (because it has a child, the filesystem created by the clone operation).  Using `zfs promote new_filesystem` reverses that relationship and makes it possible to destroy the original.

Expose libzfs_core functionality equivalent to this.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-788. You are welcome to file additional issues in GitHub if that's easier for you.
