### ISSUE TITLE
Write a man-page for flocker-volume

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#79]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-79

All our executables should have man-pages.

(Also, the man page will need to be added to the rpm).

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-79. You are welcome to file additional issues in GitHub if that's easier for you.
