### ISSUE TITLE
The documentation for `admin/build-vagrant-box` could be improved.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#792]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-792

See #723 for some comments.

In particular, it isn't clear that when testing a branch, you need to pass the branch name,

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-792. You are welcome to file additional issues in GitHub if that's easier for you.
