### ISSUE TITLE
`ssh-add` section of tutorial encourages users to add unrelated keys to their agent

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#809]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-809

`vagrant-setup` suggests that running `ssh-add` with no arguments is a good way to find out if an ssh agent is running and available.  It says if that is the case, the command will produce no output.

If the user has a key at the default location, though, this will instead add the key to the agent and tell the user it has done this.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-809. You are welcome to file additional issues in GitHub if that's easier for you.
