### ISSUE TITLE
Errors in the Building RPMs documentation

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#814]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-814

http://docs.clusterhq.com/en/latest/gettinginvolved/infrastructure/packaging.html

 * The spec filename is wrong. Should be `sudo yum-builddep python-flocker.spec`
 * ...also `rpmbuild -ba python-flocker.spec`
 * `yum-builddep python-flocker.spec` installs a version of Characteristic which is too new.
```
[vagrant@localhost flocker-662]$ yum info python-characteristic
Installed Packages
Name        : python-characteristic
Arch        : noarch
Version     : 14.1.0
Release     : 1.fc20
Size        : 127 k
Repo        : installed
From repo   : tomprince-hybridlogic
```
 * The `rpmbuild` step then fails

```
[vagrant@localhost flocker-662]$ rpmbuild -ba python-flocker.spec
error: Failed build dependencies:
	python-characteristic = 0.1.0 is needed by python-flocker-0.2.0-0.2.pre.fc20.noarch

```

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-814. You are welcome to file additional issues in GitHub if that's easier for you.
