### ISSUE TITLE
flocker.node._docker.Unit is a gearism; we should choose a better name

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#819]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-819

"Unit" is a systemd/geard term, and we're currently using neither. We should rename the class and relevant variables/attributes appropriately.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-819. You are welcome to file additional issues in GitHub if that's easier for you.
