### ISSUE TITLE
CLI should tell user if environmental requirements are missing

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#82]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-82

Flocker requires:

1. Running `docker` daemon.
2. ZFS installed and loaded into kernel.

It would be helpful to users if upon startup a check was made for all three on each node, and a warning printed if not. Having this happen early on is better than having some sort of failure occur once they actually try to do something, especially since that can leave the system in inconsistent state.

This is perhaps not necessary for the first release since we will be providing pre-configured Vagrant images.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-82. You are welcome to file additional issues in GitHub if that's easier for you.
