### ISSUE TITLE
Allow testing vagrant boxes with correct version.

### ISSUE THREAD

**Issue by tomprince** [ClusterHQ/flocker#823]
The `--box-version` argument doesn't work with local paths, and the bug (mitchellh/vagrant#4080), I filed to add this was closed with a cryptic comment. It turns out that you can pass a json file with the correct name, version and path instead.

**Comment by anzz1** [comment]
The linked issue is locked, so I'm posting in here. For anyone looking for this, the confusing part is that the JSON format is currently undocumented where the link redirects to as of some documentation rewrite.

https://docs.vagrantup.com/v2/boxes/format.html -> https://developer.hashicorp.com/vagrant/docs/boxes/format

Luckily the old documentation can still be found in archive.org : https://web.archive.org/web/20160110121600/https://docs.vagrantup.com/v2/boxes/format.html
