### ISSUE TITLE
Warn or fail if building untagged or dirty RPM packages

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#833]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-833

We probably don't ever want to build "dirty" RPM files ie where the source working directory has uncommitted changes.

The builder should probably be warned if they are building "untagged" RPM files ie where the source working directory does not exactly match a tag.

See https://github.com/ClusterHQ/flocker/pull/708#discussion_r18122202

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-833. You are welcome to file additional issues in GitHub if that's easier for you.
