### ISSUE TITLE
Make sure all tests are run by CI

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#84]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-84

Many of our functional tests will be skipped if e.g. the code is not running as root or some dependency is missing. We want to make sure all of these are actually run on Buildbot and not silently skipped.

My first thought:
1. Implement new decorator on top of `unittest.skipIf` that regardless of the given check always runs the tests if some environment variable is set. Use it for all optional tests.
2. Buildbot has a test setup that has all dependencies installed, runs as root (until we fix that requirement) etc.. The special environment variable is also set, ensuring that all tests are run.

Alternatively, maybe Buildbot can do a thing where it aggregates all tests runs and makes sure there's no test that is skipped in all of them.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-84. You are welcome to file additional issues in GitHub if that's easier for you.
