### ISSUE TITLE
Explain that Kibana web interface communicates directly with ElasticSearch using AJAX requests

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#840]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-840

The ELK example should explain that the Kibana application does not require links because its web UI uses AJAX requests to communicate directly with the ElasticSearch server.

Furthermore, we might mention that Flocker's routes allow these AJAX requests (which are sent to the same origin as the Kibana server) to be transparently forwarded to the node hosting ElasticSearch if it is moved.

XXX: Check how Kibana AJAX requests work. They connect to a different port than the web server so why aren't they restricted by same-origin policy? Web Sockets maybe?
 * http://en.wikipedia.org/wiki/Same-origin_policy

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-840. You are welcome to file additional issues in GitHub if that's easier for you.
