### ISSUE TITLE
admin/build-vagrant-box fails if an existing box file is found

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#844]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-844

If you run `admin/build-vagrant-box` (eg via the `vagrant/tutorial/build` symlink) it will fail if there is already a `.box` file with the same output name in that directory.

It would be better if the script checked up-front and failed early, giving the operator an opportunity to delete or move the existing file.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-844. You are welcome to file additional issues in GitHub if that's easier for you.
