### ISSUE TITLE
Current way functional tests in `flocker.volume` figure out if Docker is available is terrible

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#85]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-85

Importing a module really shouldn't run a subprocess.

Maybe open a unix socket to `/var/lib/docker.sock` and just assume that is the path on all platforms?

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-85. You are welcome to file additional issues in GitHub if that's easier for you.
