### ISSUE TITLE
Update clusterhq-repo without downloading and re-uploading all its packages

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#863]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-863

Modify `admin/upload-rpms` to avoid having to download all the existing RPMs before re-generating the repo metadata.

@tomprince  wrote:
> Unfortunately, createrepo needs all the RPMs that will be in the repository present, to build the appropriate metatdata. (I was asking about this in #yum last night, and it appears it might be possible to get around this with the python API).

This may also invalidate the caveat in our release process about not running the pre-populate step unless new dependency packages are required.
 * http://docs.clusterhq.com/en/latest/gettinginvolved/infrastructure/release-process.html#preliminary-step-pre-populating-rpm-repository

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-863. You are welcome to file additional issues in GitHub if that's easier for you.
