### ISSUE TITLE
flocker-node should be easily installable on modern Ubuntu

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#864]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-864

We originally considered packaging Flocker for Ubuntu in #86, but at the time we decided that it was easier to document the installation via pip and virtualenv instead. Those instructions were then reproduced in a simple `linux-install.sh` script.

But it would eventually be nice if flocker-node could be easily installed on an existing Ubuntu / Debian server and the easiest mechanism is probably by creating a deb file.

But we'll create a sumo style deb file which includes all the dependencies in a virtualenv. That's the strategy proposed for our flocker-node RPM package in #508

This is probably going to require some sub-issues. For example:
* Create Debian compatible version numbers
* Run `fpm` to build the deb package
* Create a Debian package repo. 
* Automate or document:
    * uploading the deb to our repo
    * regenerate the deb repo metadata

A followup ticket will be to package flocker-deploy in the same way.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-864. You are welcome to file additional issues in GitHub if that's easier for you.
