### ISSUE TITLE
fig compatibility layer should start containers in dependency order

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#873]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-873

It was pointed out that when containers have dependencies on each other (via links or "volumes from") fig will start the depended-on container before starting the depending-on container.  Flocker's fig compatibility layer supports links but doesn't do this startup ordering.

Flocker itself doesn't have this dependency functionality yet, either, so before this can be implemented, that will need to be implemented.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-873. You are welcome to file additional issues in GitHub if that's easier for you.
