### ISSUE TITLE
Document the process for backporting features from master to a release branch

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#877]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-877

During the `0.2.0` release we had to create our release branch from a specific, known-working commit ID in master.

We also then had to back port a change to the default IO scheduler, which had already been merged to master.

The process was fiddly and involved obscure `git` commands. We should document it.

Use `git log` to find the commit ID of the merge

```
git log --merges --first-parent
```

Branch from that specific merge commit

```
export VERSION=0.1.4

# Clone a clean copy of the repo
git clone git@github.com:ClusterHQ/flocker.git "flocker-${VERSION}"

# Create a release branch from the merge commit of the split-base-box branch
git checkout -b release/flocker-0.1.4 03cdfc7a3caa6fb45e2f348c60ca926b43c1f56b
```

Merge an un-merged branch into the release branch.

```
# Create a copy of the branch that we want to merge into our release (the donor branch)
git checkout -B noop-scheduler-235-0.1.4 origin/noop-scheduler-235

# Copy rebase that branch so that its changes are relative to the release branch
git rebase --onto release/flocker-0.1.4 origin

# Checkout the release branch and merge in the changes from the donor branch
git checkout release/flocker-0.1.4
git merge --no-ff noop-scheduler-235-0.1.4
```

Merge the changes for a merged branch into the release branch

> Richard Wall: Tom Prince The rebase command (above) doesn't yield any changes since the noop-scheduler branch got merged into master (yesterday).

> Richard Wall: So instead Adam Dangoor introduced me to the git cherry-pick command which I used as follows on the release/flocker-0.2.0 branch.

```
git cherry-pick -m1 9ed842d9a04f175ff263bec76c57c1fb36a8cd1c
```

> Richard Wall: (where 9ed842d9a04f175ff263bec76c57c1fb36a8cd1c is the merge commit of the noop-scheduler branch into master)
> Richard Wall: https://github.com/ClusterHQ/flocker/commit/9ed842d9a04f175ff263bec76c57c1fb36a8cd1c
> Richard Wall: git log now shows the following

```
commit edc825f4a590a70b3b2d2899145811221407a4ba
Author: Richard Wall <wallrj@users.noreply.github.com>
Date:   Mon Sep 29 15:03:37 2014 +0100

    Merge pull request #817 from ClusterHQ/noop-scheduler-235

    Force the use of noop ioscheduler in tutorial vagrant vms

    Authors: @wallrj, @ryao
    Reviewer: @exarkun

    Fixes #235

commit 03cdfc7a3caa6fb45e2f348c60ca926b43c1f56b
Merge: 84ad2e78 b6d8196
Author: Tom Prince <tom.prince@twistedmatrix.com>
Date:   Tue Sep 23 12:05:46 2014 -0600

    Merge pull request #723 from ClusterHQ/split-base-box

    Split the base box into one used for dev and one for the tutorial.
```

> Richard Wall: Which looks good to me, although we don't see the individual commits from the noop-scheduler branch....but I think that's a good thing.

The conversation then continued

> Jean-Paul Calderone: It Depends.
> Jean-Paul Calderone: Looks like it's okay. In the future we should avoid cherry-picking, though.
> Richard Wall: Cherry picking didn't bring all the individual commits into the release branch.
> Richard Wall: The rebasing command that I'd used in previous pre-releases ceased to work after the noop-scheduler had been merged to master.
> Jean-Paul Calderone: Right. Cherry-picking grabs only the changeset you specify.
> Jean-Paul Calderone: Right. We probably don't want to rebase, either. :)
> Jean-Paul Calderone: We want branches with a boring history that can be merged without special consideration.
> Richard Wall: Well I think Tom Prince 's rebase technique was done in such a way as to create the donor branch with a boring history...but I think his rebase command needs some modification to handle the case when the original branch has been merged.

So we need to finish that conversation and document the ideal way to backport changes from master whilst maintaining the complete commit history.

See https://github.com/ClusterHQ/flocker/pull/828#issuecomment-57328937

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-877. You are welcome to file additional issues in GitHub if that's easier for you.
