### ISSUE TITLE
Automate checking for up-to-date dependency packages

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#881]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-881

In http://doc-dev.clusterhq.com/gettinginvolved/infrastructure/release-process.html#preparing-for-a-release we manually "Check that all required versions of the dependency packages are built" by "Inspect the package versions listed in the install_requires section of setup.py" and comparing with the output of `repoquery --repoid clusterhq --repofrompath clusterhq,http://archive.clusterhq.com/fedora/20/x86_64/ "*"`

This would be much less error prone if it could be automated.

On the other hand, it may not be necessary if we switch to Sumo builds in #508.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-881. You are welcome to file additional issues in GitHub if that's easier for you.
