### ISSUE TITLE
Flocker unit port maps are agnostic of the host IP

### ISSUE THREAD

**Issue by dwgebler** [ClusterHQ/flocker#882]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-882

The `PortMap` model can only map internal container ports against host ports, but has no knowledge of any host IP binding that might be specified. The Docker API is able to return this information for a container. Flocker should respect specified host IP bindings.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-882. You are welcome to file additional issues in GitHub if that's easier for you.
