### ISSUE TITLE
Configure volume service with a Certificate Authority certificate

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#885]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-885

The volume manager API will need a way to authenticate incoming requests. We decided to validate client certificates are signed by a CA, which means we need a way to give this CA's certificate to the volume service.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-885. You are welcome to file additional issues in GitHub if that's easier for you.
