### ISSUE TITLE
Start HTTP server running API as part of volume manager server

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#887]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-887

#885 will introduce a TLS server into the volume service API server.  That server will need to actually expose the HTTP API by creating a properly initialized API server object (as introduced by #886).

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-887. You are welcome to file additional issues in GitHub if that's easier for you.
