### ISSUE TITLE
Generate TLS key-pair/self-signed certificate as part of flocker-node package installation

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#888]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-888

The volume manager API will listen via HTTPS using a TLS certificate. For now we're going with SSH-style authentication, so we should just generate a certificate as part of package installation.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-888. You are welcome to file additional issues in GitHub if that's easier for you.
