### ISSUE TITLE
Expose `VolumeService` functionality via HTTP API

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#889]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-889

This is tracking issue; will be broken up later.

* List all volumes - #904
* Get a specific volume - #905
* Create a volume. - #903
* Destroy a volume - #907 (pending #906)
* Push a volume to another node - #908
* Handoff a volume to another node? Or do we want the lower-level release and acquire?
* Clone a volume to a new volume.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-889. You are welcome to file additional issues in GitHub if that's easier for you.
