### ISSUE TITLE
Installing `flocker-node` should ensure the volume manager daemon runs as system service

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#896]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-896

Flocker volume manager should run as systemd/upstart/whatever service when `flocker-node` package is installed.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-896. You are welcome to file additional issues in GitHub if that's easier for you.
