### ISSUE TITLE
Certificate-based authorization for the `VolumeService` HTTPS API

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#902]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-902

The HTTPS API will be access controlled using client certificates.  Initially this will be limited to granting full access to a client or rejecting all access to that client based on whether the certificate is signed by the correct CA certificate or not.

Later we may want to offer finer-grained access control.  For example, we may want a class of user that has read-only access.  We could do this based on the client certificate we already plan to require.  We could also do it by adding an additional layer of credentials in the form of usernames and passwords.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-902. You are welcome to file additional issues in GitHub if that's easier for you.
