### ISSUE TITLE
HTTP API to create a volume

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#903]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-903

This will invoke `VolumeService.create`.

All URLs implicitly relative to the base for the volume API overall (eg `/v1/`)

Request:
```
POST /volumes HTTP/1.1

{"Name": "sometext"}
```

Response:
```
201 Created

{standard success boilerplate}
```

Points for consideration:

  * The proposed Docker API for volume creation includes `path` and `mode`.  These don't fit into our current volume model.
  * Maybe the request body should include a uuid (to safeguard against certain network failures - what if you submit the request, it is processed successfully, and your connection is lost before you receive the response?).  Not technically required now since names are required to be unique in our current system.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-903. You are welcome to file additional issues in GitHub if that's easier for you.
