### ISSUE TITLE
HTTP API to list all volumes

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#904]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-904

This will invoke `VolumeService.enumerate`.

All URLs implicitly relative to the base for the volume API overall (eg /v1/)

Request:
```
GET /volumes
```

Response:
```
200 OK

{success boilerplate, "volumes": [{volume info struct}, ...]}
```

No paging to start with (we have no access to any kind of paging in the underlying zfs layer anyway).

`{volume info struct}` looks roughly like:

`{"Name": <name, bytes>, "Created": <unix timestamp of creation, int>, "Size": <used space, int>}`

Compare to Docker API: https://github.com/docker/docker/pull/8484/files#diff-44a527ea72ea9572e1cf71c7f1e2a0f0R1163

Note in particular Docker makes `Size` optional (controlled by a query arg), presumably for runtime performance reasons.  And Docker includes a `Count` which is the number of containers the volume is mounted in to (which is sort of incompatible with our volume model).

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-904. You are welcome to file additional issues in GitHub if that's easier for you.
