### ISSUE TITLE
HTTP API to inspect a single volume

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#905]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-905

This will invoke `VolumeService.get` (and probably at least a couple extra methods beyond that, eg to retrieve size and creation time information).

All URLs implicitly relative to the base for the volume API overall (eg /v1/)

Request:
```
GET /volumes/<name>
```

Response:
```
200 Ok

{success boilerplate, "result": {volume information}}
```

`{volume information}` is roughly:

```
{
    "Name": <name, bytes>,
    "Created": <unix timestamp, int>,
    "Size": <used space, int>,
}
```

Compare to Docker API: https://github.com/docker/docker/pull/8484/files#diff-44a527ea72ea9572e1cf71c7f1e2a0f0R1179

Note several extra fields which we either don't have or are incompatible with our volume model.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-905. You are welcome to file additional issues in GitHub if that's easier for you.
