### ISSUE TITLE
HTTP API to destroy a volume

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#907]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-907

This will invoke `VolumeService.destroy` (to be implemented, see #906).

All URLs implicitly relative to the base for the volume API overall (eg /v1/)

Request:
```
DELETE /volumes/<name>
```

Response:
```
204 Ok
```

This is basically the same as the Docker API: https://github.com/docker/docker/pull/8484/files#diff-44a527ea72ea9572e1cf71c7f1e2a0f0R1193

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-907. You are welcome to file additional issues in GitHub if that's easier for you.
