### ISSUE TITLE
HTTP API schema and validation setup is somewhat verbose

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#910]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-910

Consider the following:

``` python
    @structured({}, {"$ref": "/endpoints.json#/definitions/volumes_output"}, V1_SCHEMAS)
    def volumes(self):         
        # ...                        
```

This is quite verbose - we keep repeating a whole bunch of boilerplate. A suitable helper and naming conventions would make this much shorter, e.g.

``` python
    @v1(b"/volumes")
    def volumes(self):
        # ...
```

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-910. You are welcome to file additional issues in GitHub if that's easier for you.
