### ISSUE TITLE
find_volume_changes needs a rewrite

### ISSUE THREAD

**Issue by dwgebler** [ClusterHQ/flocker#914]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-914

Once issues #289, #351 and #352 are closed, `flocker.node._deploy.find_volume_changes` will need rewriting, as its logic was implemented as a workaround to these issues.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-914. You are welcome to file additional issues in GitHub if that's easier for you.
