### ISSUE TITLE
Switch flocker.restapi docstrings from epytext to Sphinx-style ReST

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#915]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-915

This code as originally in HybridCluster, so uses wrong docstring formatting.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-915. You are welcome to file additional issues in GitHub if that's easier for you.
