### ISSUE TITLE
Switch all flocker.restapi code to PEP8 style underscore naming

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#916]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-916

This code was copied from HybridCluster so still has Twisted-style naming.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-916. You are welcome to file additional issues in GitHub if that's easier for you.
