### ISSUE TITLE
Delete klein monkeypatching once klein 0.2.4 is available

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#917]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-917

`flocker.restapi` test infrastructure patches klein; the fix was merged into klein but has yet to be released.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-917. You are welcome to file additional issues in GitHub if that's easier for you.
