### ISSUE TITLE
Re-enable some logging assertions in REST API tests

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#918]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-918

There's a few commented out `@validateLogging` assertions in `flocker.restapi` tests; they should be enabled, probably by adding some custom methods that can be passed to `@validateLogging`.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-918. You are welcome to file additional issues in GitHub if that's easier for you.
