### ISSUE TITLE
Move twisted.web testing fakes into Twisted

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#919]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-919

There's a bunch of useful functionality for testing `twisted.web` in `flocker.restapi`. We should move it upstream.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-919. You are welcome to file additional issues in GitHub if that's easier for you.
