### ISSUE TITLE
Port over documentation on using `flocker.restapi` from HybridCluster

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#920]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-920

There was some internal user-facing docs that are still useful with new code.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-920. You are welcome to file additional issues in GitHub if that's easier for you.
