### ISSUE TITLE
Port over Sphinx extension for generating HTTP API documentation from HybridCluster

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#921]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-921

HybridCluster had a Sphinx extension for generating API documentation for HTTP APIs for the code that is now `flocker.restapi`. We should port that over.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-921. You are welcome to file additional issues in GitHub if that's easier for you.
