### ISSUE TITLE
Figure out concurrency requirements and design for HTTP API

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#923]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-923

Various actions can happen at the same time. How does this work?

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-923. You are welcome to file additional issues in GitHub if that's easier for you.
