### ISSUE TITLE
Various ZFSFilesystem operations are not atomic

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#924]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-924

If we crash half way through some of the volume operations we can be left in inconsistent state. How do we deal with this?

Currently this only includes:
- #679 results in renames, but that'll be fixed in that issue.
- Marking things as read-only after changing owner or cloned.

We may be able to get away with just ad-hoc solution for the latter.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-924. You are welcome to file additional issues in GitHub if that's easier for you.
