### ISSUE TITLE
Stable identifiers for volumes

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#925]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-925

Volumes are now identified name... we probably want some sort of stable identity (UUID) beyond the user-facing one.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-925. You are welcome to file additional issues in GitHub if that's easier for you.
