### ISSUE TITLE
Storage level should have "schema" version information

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#926]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-926

We should be able to say "this is ZFS-based filesystem layer version 1.2", to allow for future upgradability.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-926. You are welcome to file additional issues in GitHub if that's easier for you.
