### ISSUE TITLE
Cloned volumes should indicate their parent in the HTTP API output

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#927]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-927

Clones have specific consequences on disk storage; knowing whether something is a clone and what its parent is useful.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-927. You are welcome to file additional issues in GitHub if that's easier for you.
