### ISSUE TITLE
A hosts entry should be added for each link

### ISSUE THREAD

**Issue by msh100** [ClusterHQ/flocker#929]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-929

In Docker links a hosts entry is added for each linked container. Flocker does not add these lines to `/etc/hosts`.

https://docs.docker.com/userguide/dockerlinks/#updating-the-etchosts-file

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-929. You are welcome to file additional issues in GitHub if that's easier for you.
