### ISSUE TITLE
An overview of Docker logs

### ISSUE THREAD

**Issue by msh100** [ClusterHQ/flocker#930]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-930

When we currently run `flocker-deploy`, there's no output and it may be nice to have the containers output sent the the client when trying to debug.

At the moment fig does this by default and you specify the `-d` flag to run as Flocker does at the moment. Maybe it would make sense to do this exactly the opposite, and have a flag to output the container logs for debugging.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-930. You are welcome to file additional issues in GitHub if that's easier for you.
