### ISSUE TITLE
Iptables rules shouldn't be created if a port is in use

### ISSUE THREAD

**Issue by msh100** [ClusterHQ/flocker#931]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-931

When you try to start a Docker container with `flocker-deploy` at the moment, and the port is already allocated, an error is returned from Docker.

`flocker-deploy` does not take currently allocated ports into consideration and will write iptables rules regardless of if the port is allocated.

Example: When trying to start a container on port 22, it will fail to create the container as the host SSH uses this port. Iptables rules are subsequently created on the other nodes to forward to the SSH server of the node you're deploying the container to (which failed).

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-931. You are welcome to file additional issues in GitHub if that's easier for you.
