### ISSUE TITLE
Simplify calculate necessary state changes

### ISSUE THREAD

**Issue by dwgebler** [ClusterHQ/flocker#932]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-932

https://github.com/ClusterHQ/flocker/pull/922

`Deployer.calculate_necessary_state_changes.find_differences` has become overly complex and should be broken down / simplified further, e.g. `_calculate_stop_containers`, `_calculate_start containers`, `_calculate_restart_containers`, `_calculate_volume_changes` or something like that.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-932. You are welcome to file additional issues in GitHub if that's easier for you.
