### ISSUE TITLE
`flocker-serve` should write out logs

### ISSUE THREAD

**Issue by itamarst** [ClusterHQ/flocker#936]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-936

Logging is good. Eliot is good at logging. We should do that.

Logs should possibly be written to standard out to be written by systemd, or perhaps to `/var/log/flocker`. At a guess the latter, since it's not clear if systemd etc. would actually DTRT with Eliot logs.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-936. You are welcome to file additional issues in GitHub if that's easier for you.
