### ISSUE TITLE
flocker.node._docker.Environment doesn't document the types of the keys or values in its `variables`

### ISSUE THREAD

**Issue by exarkun** [ClusterHQ/flocker#938]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-938

It should.  Right now it's not clear if these are bytes or unicode.

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-938. You are welcome to file additional issues in GitHub if that's easier for you.
