### ISSUE TITLE
Eliot required version mismatch between setup.py and python-flocker.spec.in

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/flocker#945]
**Replaced by** https://clusterhq.atlassian.net/browse/FLOC-945

The rpm version spec is a little more flexible and allows patch releases.

Presumably the python requirement should be the same.

```
$ grep -i eliot setup.py python-flocker.spec.in setup.py:        "eliot == 0.4.0",
python-flocker.spec.in:BuildRequires:  python-eliot >= 0.4.0, python-eliot < 0.5.0
python-flocker.spec.in:Requires:       python-eliot >= 0.4.0, python-eliot < 0.5.0
```

@adamtheturtle and I noticed this while performing the dependency checks during the 0.3.0 release process:
 * http://doc-dev.clusterhq.com/gettinginvolved/infrastructure/release-process.html#preparing-for-a-release

Refs #928 #933

**Comment by adamtheturtle** [comment]
We are moving our development planning to JIRA. This is issue is now being tracked at https://clusterhq.atlassian.net/browse/FLOC-945. You are welcome to file additional issues in GitHub if that's easier for you.
