### ISSUE TITLE
Support for attaching non-ZFS volumes?

### ISSUE THREAD

**Issue by praveenj83** [ClusterHQ/flocker#969]
Hi,
    Is there a plan/tentative timeline for when Flocker will support attaching non-ZFS external volumes to containers? I am looking at a scenario where I will need some ZFS volumes and perhaps a block device attached to a container. I am interested in the ZFS-volume migration capability of Flocker. I don't need migration for the non-ZFS volumes, but will need them attached to the Docker containers created. Is there a plan to support that? Thanks!

**Comment by aidanhs** [comment]
I'm quite interested in flocker being aware of containers with non-zfs volumes and having an option of refusing to move them. If I understand correctly (not having played with flocker) this would allow me to have a limited form of zero-downtime migration without having to have any zfs filesystems. 

Is this correct? How close is flocker to being able to do this? If there's some work to do, any pointers on where I'd need to start looking to make changes?

**Comment by exarkun** [comment]
> I'm quite interested in flocker being aware of containers with non-zfs volumes and having an option of refusing to move them. If I understand correctly (not having played with flocker) this would allow me to have a limited form of zero-downtime migration without having to have any zfs filesystems.

I think you probably have a different feature in mind than praveenj83 who seems to be interested in SANs.  Are you interested in SAN support or something else that's also not ZFS?  Defining features by exclusion is really tedious!  I don't want to have a conversation about non-ZFS, non-SAN Flocker functionality, so perhaps you could describe what you're interesting in instead of what you're not interested in? :wink:

If you'd like, perhaps we can arrange a real-time conversation to discuss the features you're interested in.

**Comment by aidanhs** [comment]
Ok, I've spend a bit of time reading the documentation and I think I've realised that what I want is pretty far out from what flocker has at the moment, so maybe I need to look elsewhere (/roll my own :( )

Concretely:
 - I have a webserver in a container C.
 - This webserver may write files into the container (not to a volume).
 - I want to migrate this 'dirty' container, with files it has added so far, from H1 to H2.

I hadn't really looked too hard at flocker before, so I hadn't grasped that flocker uses a stop and start process which works image names (i.e. dirty containers are lost) - I couldn't quite figure out how, but I assumed you'd managed to figure out how to migrate a `docker pause`d container. Of course, now I apply some thought I realise that this is really tricky without emulating memory addresses or restarting a process.

One of the nice things about this imaginary world is not having to install zfs (and containers with volumes would be intentionally 'pinned' to a host), though I saw this post on google groups about the cloud block device which looks interesting - https://groups.google.com/d/msg/flocker-users/azZ2qJufXkk/23w-XqWlP8MJ

Sorry for the noise, I need to read documentation better next time. Though it might be nice to make the start-stop behaviour and dirty-container loss more explicit - in particular, "In just a few seconds, you'll see that the Redis container is migrated to the other host, network traffic is re-routed, and your application is still online on both IPs!" from https://docs.clusterhq.com/en/0.3.2/gettingstarted/index.html misled me somewhat.

**Comment by itamarst** [comment]
You could perhaps integrate CRIU with Flocker as a way of moving both data and application.

Also, keep in mind that crashes will happen sooner or later, so if you're writing custom code "crash-only" recovery is a good way to design it. I.e. assume it's only ever kill -9ed and design around that. At which point starting from a "dirty" set of files is just the same as normal startup, and therefore hopefully quiet fast.

**Comment by binocarlos** [comment]
@aidanhs @praveenj83  Hey guys, I'm closing this issue but please re-open it if something crops up.
